//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::cell::UnsafeCell;
use core::ffi::*;
use core::marker::{PhantomData, PhantomPinned};
use core::ptr::NonNull;
#[cfg(feature = "dispatch2")]
use dispatch2::*;
#[cfg(feature = "objc2")]
use objc2::__framework_prelude::*;
#[cfg(feature = "objc2-core-foundation")]
use objc2_core_foundation::*;

use crate::*;

/// The chirality of an accessory.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessory_chirality_t?language=objc)
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct ar_accessory_chirality_t(pub isize);
impl ar_accessory_chirality_t {
    /// Unspecified (non-handed accessory, not associated with a hand).
    #[doc(alias = "ar_accessory_chirality_unspecified")]
    pub const unspecified: Self = Self(0);
    /// Left-handed accessory, or non-handed accessory held in left hand.
    #[doc(alias = "ar_accessory_chirality_left")]
    pub const left: Self = Self(1);
    /// Right-handed accessory, or non-handed accessory held in right hand.
    #[doc(alias = "ar_accessory_chirality_right")]
    pub const right: Self = Self(2);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ar_accessory_chirality_t {
    const ENCODING: Encoding = isize::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ar_accessory_chirality_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// Error codes specific to accessory tracking.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessory_tracking_error_code_t?language=objc)
#[cfg(feature = "error")]
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ar_accessory_tracking_error_code_t(pub ar_error_code_t);
#[cfg(feature = "error")]
impl ar_accessory_tracking_error_code_t {
    /// Error code indicating that an accessory failed to load.
    #[doc(alias = "ar_accessory_tracking_error_code_accessory_loading_failed")]
    pub const accessory_loading_failed: Self = Self(1200);
}

#[cfg(all(feature = "error", feature = "objc2"))]
unsafe impl Encode for ar_accessory_tracking_error_code_t {
    const ENCODING: Encoding = ar_error_code_t::ENCODING;
}

#[cfg(all(feature = "error", feature = "objc2"))]
unsafe impl RefEncode for ar_accessory_tracking_error_code_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// Tracking status for accessory anchors.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessory_anchor_tracking_state_t?language=objc)
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct ar_accessory_anchor_tracking_state_t(pub isize);
impl ar_accessory_anchor_tracking_state_t {
    /// Tracking status for accessory anchors.
    #[doc(alias = "ar_accessory_anchor_tracking_state_untracked")]
    pub const untracked: Self = Self(0);
    /// Tracking status for accessory anchors.
    #[doc(alias = "ar_accessory_anchor_tracking_state_orientation_tracked")]
    pub const orientation_tracked: Self = Self(1);
    /// Tracking status for accessory anchors.
    #[doc(alias = "ar_accessory_anchor_tracking_state_position_orientation_tracked")]
    pub const position_orientation_tracked: Self = Self(2);
    /// Tracking status for accessory anchors.
    #[doc(alias = "ar_accessory_anchor_tracking_state_position_orientation_tracked_low_accuracy")]
    pub const position_orientation_tracked_low_accuracy: Self = Self(3);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ar_accessory_anchor_tracking_state_t {
    const ENCODING: Encoding = isize::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ar_accessory_anchor_tracking_state_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// The type of input that was used to initialize an `ar_accessory_t`.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessory_source_type_t?language=objc)
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ar_accessory_source_type_t(pub isize);
impl ar_accessory_source_type_t {
    /// Accessory was initialized from a `GCDevice`.
    #[doc(alias = "ar_accessory_source_type_device")]
    pub const device: Self = Self(1);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ar_accessory_source_type_t {
    const ENCODING: Encoding = isize::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ar_accessory_source_type_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessory_t?language=objc)
#[repr(C)]
pub struct ar_accessory_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_accessory_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessories_t?language=objc)
#[repr(C)]
pub struct ar_accessories_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_accessories_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessory_anchor_t?language=objc)
#[repr(C)]
pub struct ar_accessory_anchor_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_accessory_anchor_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessory_anchors_t?language=objc)
#[repr(C)]
pub struct ar_accessory_anchors_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_accessory_anchors_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessory_tracking_configuration_t?language=objc)
#[repr(C)]
pub struct ar_accessory_tracking_configuration_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_accessory_tracking_configuration_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessory_tracking_provider_t?language=objc)
#[repr(C)]
pub struct ar_accessory_tracking_provider_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_accessory_tracking_provider_t {}
);

extern "C" {
    /// Pre-defined accessory location name for spatial gamepad grip surface.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessory_location_name_grip_surface?language=objc)
    pub static ar_accessory_location_name_grip_surface: NonNull<c_char>;
}

extern "C" {
    /// Pre-defined accessory location name for spatial gamepad grip.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessory_location_name_grip?language=objc)
    pub static ar_accessory_location_name_grip: NonNull<c_char>;
}

extern "C" {
    /// Pre-defined accessory location name for spatial gamepad and stylus aim point.
    ///
    /// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessory_location_name_aim?language=objc)
    pub static ar_accessory_location_name_aim: NonNull<c_char>;
}

impl ar_accessory_t {
    /// Indicates whether two accessories are equal.
    ///
    ///
    /// Parameter `accessory`: An accessory to be compared.
    ///
    /// Parameter `other_accessory`: The other accessory to be compared to.
    ///
    ///
    /// Returns: `true` if the accessories are equal, otherwise `false`.
    ///
    /// # Safety
    ///
    /// - `accessory` must implement OS_ar_accessory.
    /// - `other_accessory` must implement OS_ar_accessory.
    #[doc(alias = "ar_accessory_is_equal_to_accessory")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn is_equal_to_accessory(
        accessory: Option<&ar_accessory_t>,
        other_accessory: Option<&ar_accessory_t>,
    ) -> bool {
        extern "C-unwind" {
            fn ar_accessory_is_equal_to_accessory(
                accessory: Option<&ar_accessory_t>,
                other_accessory: Option<&ar_accessory_t>,
            ) -> bool;
        }
        unsafe { ar_accessory_is_equal_to_accessory(accessory, other_accessory) }
    }

    /// Get identifier for the accessory.
    ///
    /// Parameter `accessory`: The accessory.
    ///
    /// Parameter `out_identifier`: Object to fill with UUID.
    ///
    /// # Safety
    ///
    /// `accessory` must implement OS_ar_accessory.
    #[doc(alias = "ar_accessory_get_identifier")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn identifier(accessory: &ar_accessory_t, out_identifier: &mut uuid_t) {
        extern "C-unwind" {
            fn ar_accessory_get_identifier(accessory: &ar_accessory_t, out_identifier: &mut uuid_t);
        }
        unsafe { ar_accessory_get_identifier(accessory, out_identifier) }
    }

    /// Get inherent chirality for the accessory (what hand it is designed to be held in).
    ///
    /// Parameter `accessory`: The accessory.
    ///
    /// Returns: Chirality.
    ///
    /// # Safety
    ///
    /// `accessory` must implement OS_ar_accessory.
    #[doc(alias = "ar_accessory_get_inherent_chirality")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn inherent_chirality(accessory: &ar_accessory_t) -> ar_accessory_chirality_t {
        extern "C-unwind" {
            fn ar_accessory_get_inherent_chirality(
                accessory: &ar_accessory_t,
            ) -> ar_accessory_chirality_t;
        }
        unsafe { ar_accessory_get_inherent_chirality(accessory) }
    }

    /// Get an accessory's name.
    ///
    ///
    /// Parameter `accessory`: The accessory.
    ///
    ///
    /// Note: The returned value will have the same lifetime as the input `ar_accessory_t`.
    ///
    /// Returns: The name of the accessory, or NULL if no name is set.
    ///
    /// # Safety
    ///
    /// `accessory` must implement OS_ar_accessory.
    #[doc(alias = "ar_accessory_get_name")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn name(accessory: &ar_accessory_t) -> NonNull<c_char> {
        extern "C-unwind" {
            fn ar_accessory_get_name(accessory: &ar_accessory_t) -> Option<NonNull<c_char>>;
        }
        let ret = unsafe { ar_accessory_get_name(accessory) };
        ret.expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Gets the names of locations with pre-defined coordinate systems available for this accessory.
    ///
    ///
    /// Parameter `accessory`: Accessory.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An `ar_strings_t` with the location names.
    ///
    /// # Safety
    ///
    /// `accessory` must implement OS_ar_accessory.
    #[doc(alias = "ar_accessory_copy_location_names")]
    #[cfg(all(feature = "objc2", feature = "strings_collection"))]
    #[inline]
    pub unsafe fn location_names(accessory: &ar_accessory_t) -> Retained<ar_strings_t> {
        extern "C-unwind" {
            fn ar_accessory_copy_location_names(accessory: &ar_accessory_t) -> *mut ar_strings_t;
        }
        let ret = unsafe { ar_accessory_copy_location_names(accessory) };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Get path to a USDZ file for the accessory, if it has one.
    ///
    ///
    /// Parameter `accessory`: The accessory.
    ///
    /// Note: The returned value will have the same lifetime as the `ar_accessory_t`.
    ///
    /// Returns: The path to the USDZ file.
    ///
    /// # Safety
    ///
    /// `accessory` must implement OS_ar_accessory.
    #[doc(alias = "ar_accessory_get_usdz_file_path")]
    #[cfg(all(feature = "objc2", feature = "objc2-core-foundation"))]
    #[inline]
    pub unsafe fn usdz_file_path(accessory: &ar_accessory_t) -> Option<CFRetained<CFURL>> {
        extern "C-unwind" {
            fn ar_accessory_get_usdz_file_path(
                accessory: &ar_accessory_t,
            ) -> Option<NonNull<CFURL>>;
        }
        let ret = unsafe { ar_accessory_get_usdz_file_path(accessory) };
        ret.map(|ret| unsafe { CFRetained::retain(ret) })
    }
}

/// Handler triggered when a request to load an accessory from a `GCDevice` has completed.
///
///
/// Parameter `device`: `GCDevice` for the accessory that was being loaded.
///
/// Parameter `successful`: `true` if loading succeeded, `false` otherwise.
///
/// Parameter `error`: The error that occurred, if any. The error supports ARC. In non-ARC files, use `ar_release()` to release the error.
///
/// Parameter `accessory`: An instance of `ar_accessory_t` (NULL if loading failed). The accessory supports ARC. In non-ARC files, use
/// `ar_release()` to release it.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessory_device_load_completion_handler_t?language=objc)
#[cfg(all(feature = "block2", feature = "error", feature = "objc2"))]
pub type ar_accessory_device_load_completion_handler_t = block2::Block<
    'static,
    fn(NonNull<ProtocolObject<dyn GCDevice>>, bool, *mut ar_error_t, *mut ar_accessory_t),
>;

impl ar_accessory_t {
    /// Load an accessory from a `GCDevice`.
    ///
    ///
    /// Parameter `device`: The `GCDevice` for which to load the accessory.
    ///
    /// Parameter `completion_handler`: Handler triggered after the request to load an accessory completes.
    #[doc(alias = "ar_accessory_load_from_device")]
    #[cfg(all(feature = "block2", feature = "error", feature = "objc2"))]
    #[inline]
    pub unsafe fn load_from_device(
        device: &ProtocolObject<dyn GCDevice>,
        completion_handler: &ar_accessory_device_load_completion_handler_t,
    ) {
        extern "C-unwind" {
            fn ar_accessory_load_from_device(
                device: &ProtocolObject<dyn GCDevice>,
                completion_handler: &ar_accessory_device_load_completion_handler_t,
            );
        }
        unsafe { ar_accessory_load_from_device(device, completion_handler) }
    }
}

/// Function triggered when a request to load an accessory from a `GCDevice` has completed.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `device`: `GCDevice` for the accessory that was being loaded.
///
/// Parameter `successful`: `true` if loading succeeded, `false` otherwise.
///
/// Parameter `error`: The error that occurred, if any. The error supports ARC. In non-ARC files, use `ar_release()` to release the error.
///
/// Parameter `accessory`: An instance of `ar_accessory_t` (NULL if loading failed). The accessory supports ARC. In non-ARC files, use
/// `ar_release()` to release it.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessory_device_load_completion_handler_function_t?language=objc)
#[cfg(all(feature = "error", feature = "objc2"))]
pub type ar_accessory_device_load_completion_handler_function_t = unsafe extern "C-unwind" fn(
    *mut c_void,
    &ProtocolObject<dyn GCDevice>,
    bool,
    Option<&ar_error_t>,
    Option<&ar_accessory_t>,
);

impl ar_accessory_t {
    /// Load an accessory from a `GCDevice`.
    ///
    ///
    /// Parameter `device`: The `GCDevice` for which to load the accessory.
    ///
    /// Parameter `context`: The application-defined context.
    ///
    /// Parameter `completion_handler_function`: Function triggered after the request to load an accessory completes.
    ///
    /// # Safety
    ///
    /// - `context` must be a valid pointer or null.
    /// - `completion_handler_function` must be implemented correctly.
    #[doc(alias = "ar_accessory_load_from_device_f")]
    #[cfg(all(feature = "error", feature = "objc2"))]
    #[inline]
    pub unsafe fn load_from_device_f(
        device: &ProtocolObject<dyn GCDevice>,
        context: *mut c_void,
        completion_handler_function: ar_accessory_device_load_completion_handler_function_t,
    ) {
        extern "C-unwind" {
            fn ar_accessory_load_from_device_f(
                device: &ProtocolObject<dyn GCDevice>,
                context: *mut c_void,
                completion_handler_function: ar_accessory_device_load_completion_handler_function_t,
            );
        }
        unsafe { ar_accessory_load_from_device_f(device, context, completion_handler_function) }
    }

    /// Gets type of source that was used to load an accessory.
    ///
    ///
    /// Parameter `accessory`: The accessory.
    ///
    ///
    /// Returns: Source type.
    ///
    /// # Safety
    ///
    /// `accessory` must implement OS_ar_accessory.
    #[doc(alias = "ar_accessory_get_source_type")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn source_type(accessory: &ar_accessory_t) -> ar_accessory_source_type_t {
        extern "C-unwind" {
            fn ar_accessory_get_source_type(
                accessory: &ar_accessory_t,
            ) -> ar_accessory_source_type_t;
        }
        unsafe { ar_accessory_get_source_type(accessory) }
    }

    /// Gets the `GCDevice` that was used to initialize the accessory.
    ///
    ///
    /// Parameter `accessory`: The accessory.
    ///
    ///
    /// Returns: The `GCDevice`, or NULL if not used to initialize the accessory.
    ///
    /// # Safety
    ///
    /// `accessory` must implement OS_ar_accessory.
    #[doc(alias = "ar_accessory_get_source_device")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn source_device(
        accessory: &ar_accessory_t,
    ) -> Option<Retained<ProtocolObject<dyn GCDevice>>> {
        extern "C-unwind" {
            fn ar_accessory_get_source_device(
                accessory: &ar_accessory_t,
            ) -> *mut ProtocolObject<dyn GCDevice>;
        }
        let ret = unsafe { ar_accessory_get_source_device(accessory) };
        unsafe { Retained::retain_autoreleased(ret) }
    }
}

impl ar_accessories_t {
    /// Create an empty collection of accessories.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_accessories_t`.
    #[doc(alias = "ar_accessories_create")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn new() -> Retained<ar_accessories_t> {
        extern "C-unwind" {
            fn ar_accessories_create() -> *mut ar_accessories_t;
        }
        let ret = unsafe { ar_accessories_create() };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Add an accessory to a collection.
    ///
    ///
    /// The accessory must be unique. A duplicate of any existing object in the collection will not be added.
    ///
    ///
    /// Parameter `accessories`: The collection of accessories to alter.
    ///
    /// Parameter `accessory_to_add`: The accessory to add.
    ///
    /// # Safety
    ///
    /// - `accessories` must implement OS_ar_accessories.
    /// - `accessory_to_add` must implement OS_ar_accessory.
    #[doc(alias = "ar_accessories_add_accessory")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn add_accessory(accessories: &ar_accessories_t, accessory_to_add: &ar_accessory_t) {
        extern "C-unwind" {
            fn ar_accessories_add_accessory(
                accessories: &ar_accessories_t,
                accessory_to_add: &ar_accessory_t,
            );
        }
        unsafe { ar_accessories_add_accessory(accessories, accessory_to_add) }
    }

    /// Add accessories to a collection.
    ///
    ///
    /// The accessories must be unique. Duplicates of any existing object in the collection will not be added.
    ///
    ///
    /// Parameter `accessories`: The collection of accessories to alter.
    ///
    /// Parameter `accessories_to_add`: The accessories to add.
    ///
    /// # Safety
    ///
    /// - `accessories` must implement OS_ar_accessories.
    /// - `accessories_to_add` must implement OS_ar_accessories.
    #[doc(alias = "ar_accessories_add_accessories")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn add_accessories(
        accessories: &ar_accessories_t,
        accessories_to_add: &ar_accessories_t,
    ) {
        extern "C-unwind" {
            fn ar_accessories_add_accessories(
                accessories: &ar_accessories_t,
                accessories_to_add: &ar_accessories_t,
            );
        }
        unsafe { ar_accessories_add_accessories(accessories, accessories_to_add) }
    }

    /// Remove an accessory from a collection.
    ///
    ///
    /// No action is taken if the accessory is not found.
    ///
    ///
    /// Parameter `accessories`: The collection of accessories to alter.
    ///
    /// Parameter `accessory_to_remove`: The accessory to remove.
    ///
    /// # Safety
    ///
    /// - `accessories` must implement OS_ar_accessories.
    /// - `accessory_to_remove` must implement OS_ar_accessory.
    #[doc(alias = "ar_accessories_remove_accessory")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn remove_accessory(
        accessories: &ar_accessories_t,
        accessory_to_remove: &ar_accessory_t,
    ) {
        extern "C-unwind" {
            fn ar_accessories_remove_accessory(
                accessories: &ar_accessories_t,
                accessory_to_remove: &ar_accessory_t,
            );
        }
        unsafe { ar_accessories_remove_accessory(accessories, accessory_to_remove) }
    }

    /// Remove accessories from a collection.
    ///
    ///
    /// Parameter `accessories`: The collection of accessories to alter.
    ///
    /// Parameter `accessories_to_remove`: The accessories to remove.
    ///
    /// # Safety
    ///
    /// - `accessories` must implement OS_ar_accessories.
    /// - `accessories_to_remove` must implement OS_ar_accessories.
    #[doc(alias = "ar_accessories_remove_accessories")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn remove_accessories(
        accessories: &ar_accessories_t,
        accessories_to_remove: &ar_accessories_t,
    ) {
        extern "C-unwind" {
            fn ar_accessories_remove_accessories(
                accessories: &ar_accessories_t,
                accessories_to_remove: &ar_accessories_t,
            );
        }
        unsafe { ar_accessories_remove_accessories(accessories, accessories_to_remove) }
    }

    /// Get the count of accessories in the collection.
    ///
    ///
    /// Parameter `accessories`: The collection of accessories.
    ///
    /// Returns: The number of accessories in the collection.
    ///
    /// # Safety
    ///
    /// `accessories` must implement OS_ar_accessories.
    #[doc(alias = "ar_accessories_get_count")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn count(accessories: &ar_accessories_t) -> usize {
        extern "C-unwind" {
            fn ar_accessories_get_count(accessories: &ar_accessories_t) -> usize;
        }
        unsafe { ar_accessories_get_count(accessories) }
    }
}

/// Handler for enumerating a collection of accessories.
///
///
/// Parameter `accessory`: The accessory.
///
///
/// Returns: `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessories_enumerator_t?language=objc)
#[cfg(all(feature = "block2", feature = "objc2"))]
pub type ar_accessories_enumerator_t = block2::Block<'static, fn(NonNull<ar_accessory_t>) -> bool>;

impl ar_accessories_t {
    /// Enumerate a collection of accessories.
    ///
    ///
    /// Parameter `accessories`: The collection of accessories.
    ///
    /// Parameter `accessories_enumerator`: The enumerator handler.
    ///
    /// # Safety
    ///
    /// `accessories` must implement OS_ar_accessories.
    #[doc(alias = "ar_accessories_enumerate_accessories")]
    #[cfg(all(feature = "block2", feature = "objc2"))]
    #[inline]
    pub unsafe fn enumerate_accessories(
        accessories: &ar_accessories_t,
        accessories_enumerator: &ar_accessories_enumerator_t,
    ) {
        extern "C-unwind" {
            fn ar_accessories_enumerate_accessories(
                accessories: &ar_accessories_t,
                accessories_enumerator: &ar_accessories_enumerator_t,
            );
        }
        unsafe { ar_accessories_enumerate_accessories(accessories, accessories_enumerator) }
    }
}

/// Function for enumerating a collection of accessories.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `accessory`: The accessory.
///
///
/// Returns: `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessories_enumerator_function_t?language=objc)
#[cfg(feature = "objc2")]
pub type ar_accessories_enumerator_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &ar_accessory_t) -> bool;

impl ar_accessories_t {
    /// Enumerate a collection of reference objects.
    ///
    ///
    /// Parameter `accessories`: The collection of accessories.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `accessories_enumerator_function`: The enumerator function.
    ///
    /// # Safety
    ///
    /// - `accessories` must implement OS_ar_accessories.
    /// - `context` must be a valid pointer or null.
    /// - `accessories_enumerator_function` must be implemented correctly.
    #[doc(alias = "ar_accessories_enumerate_accessories_f")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn enumerate_accessories_f(
        accessories: &ar_accessories_t,
        context: *mut c_void,
        accessories_enumerator_function: ar_accessories_enumerator_function_t,
    ) {
        extern "C-unwind" {
            fn ar_accessories_enumerate_accessories_f(
                accessories: &ar_accessories_t,
                context: *mut c_void,
                accessories_enumerator_function: ar_accessories_enumerator_function_t,
            );
        }
        unsafe {
            ar_accessories_enumerate_accessories_f(
                accessories,
                context,
                accessories_enumerator_function,
            )
        }
    }
}

impl ar_accessory_anchor_t {
    /// Create an uninitialized accessory anchor.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_accessory_anchor_t`.
    #[doc(alias = "ar_accessory_anchor_create")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn new() -> Retained<ar_accessory_anchor_t> {
        extern "C-unwind" {
            fn ar_accessory_anchor_create() -> *mut ar_accessory_anchor_t;
        }
        let ret = unsafe { ar_accessory_anchor_create() };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Returns a Boolean value that indicates whether the two accessory anchors are equal.
    ///
    ///
    /// Parameter `anchor`: The accessory anchor to be compared.
    ///
    /// Parameter `other_anchor`: The other accessory anchor to be compared to.
    ///
    ///
    /// Returns: `true` if the accessory anchors are equal, otherwise `false`.
    ///
    /// # Safety
    ///
    /// - `anchor` must implement OS_ar_accessory_anchor.
    /// - `other_anchor` must implement OS_ar_accessory_anchor.
    #[doc(alias = "ar_accessory_anchor_is_equal_to_accessory_anchor")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn is_equal_to_accessory_anchor(
        anchor: Option<&ar_accessory_anchor_t>,
        other_anchor: Option<&ar_accessory_anchor_t>,
    ) -> bool {
        extern "C-unwind" {
            fn ar_accessory_anchor_is_equal_to_accessory_anchor(
                anchor: Option<&ar_accessory_anchor_t>,
                other_anchor: Option<&ar_accessory_anchor_t>,
            ) -> bool;
        }
        unsafe { ar_accessory_anchor_is_equal_to_accessory_anchor(anchor, other_anchor) }
    }

    /// Returns the accessory that is being tracked by the anchor.
    ///
    ///
    /// Parameter `accessory_anchor`: The accessory anchor.
    ///
    ///
    /// Returns: The accessory.
    ///
    /// # Safety
    ///
    /// `accessory_anchor` must implement OS_ar_accessory_anchor.
    #[doc(alias = "ar_accessory_anchor_get_accessory")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn accessory(accessory_anchor: &ar_accessory_anchor_t) -> Retained<ar_accessory_t> {
        extern "C-unwind" {
            fn ar_accessory_anchor_get_accessory(
                accessory_anchor: &ar_accessory_anchor_t,
            ) -> *mut ar_accessory_t;
        }
        let ret = unsafe { ar_accessory_anchor_get_accessory(accessory_anchor) };
        unsafe { Retained::retain_autoreleased(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Get the tracking state of the accessory anchor.
    ///
    ///
    /// Parameter `accessory_anchor`: The accessory anchor.
    ///
    ///
    /// Returns: Tracking state for this anchor.
    ///
    /// # Safety
    ///
    /// `accessory_anchor` must implement OS_ar_accessory_anchor.
    #[doc(alias = "ar_accessory_anchor_get_tracking_state")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn tracking_state(
        accessory_anchor: &ar_accessory_anchor_t,
    ) -> ar_accessory_anchor_tracking_state_t {
        extern "C-unwind" {
            fn ar_accessory_anchor_get_tracking_state(
                accessory_anchor: &ar_accessory_anchor_t,
            ) -> ar_accessory_anchor_tracking_state_t;
        }
        unsafe { ar_accessory_anchor_get_tracking_state(accessory_anchor) }
    }

    /// Returns a Boolean value that indicates whether the accessory is held.
    ///
    ///
    /// Parameter `accessory_anchor`: The accessory anchor.
    ///
    ///
    /// Returns: true if the accessory is currently held, otherwise false.
    ///
    /// # Safety
    ///
    /// `accessory_anchor` must implement OS_ar_accessory_anchor.
    #[doc(alias = "ar_accessory_anchor_is_held")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn is_held(accessory_anchor: &ar_accessory_anchor_t) -> bool {
        extern "C-unwind" {
            fn ar_accessory_anchor_is_held(accessory_anchor: &ar_accessory_anchor_t) -> bool;
        }
        unsafe { ar_accessory_anchor_is_held(accessory_anchor) }
    }

    /// Get the held state of this accessory anchor.
    ///
    ///
    /// Parameter `accessory_anchor`: The accessory anchor.
    ///
    ///
    /// Returns: Which hand the accessory is being held in, or unknown.
    ///
    /// # Safety
    ///
    /// `accessory_anchor` must implement OS_ar_accessory_anchor.
    #[doc(alias = "ar_accessory_anchor_get_held_chirality")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn held_chirality(
        accessory_anchor: &ar_accessory_anchor_t,
    ) -> ar_accessory_chirality_t {
        extern "C-unwind" {
            fn ar_accessory_anchor_get_held_chirality(
                accessory_anchor: &ar_accessory_anchor_t,
            ) -> ar_accessory_chirality_t;
        }
        unsafe { ar_accessory_anchor_get_held_chirality(accessory_anchor) }
    }

    /// Get the identifier of an anchor.
    ///
    ///
    /// Parameter `accessory_anchor`: The anchor.
    ///
    /// Parameter `out_identifier`: A pointer to a UUID to fill out with the anchor identifier. Must be non-null.
    ///
    /// # Safety
    ///
    /// `accessory_anchor` must implement OS_ar_accessory_anchor.
    #[doc(alias = "ar_accessory_anchor_get_identifier")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn identifier(
        accessory_anchor: &ar_accessory_anchor_t,
        out_identifier: &mut uuid_t,
    ) {
        extern "C-unwind" {
            fn ar_accessory_anchor_get_identifier(
                accessory_anchor: &ar_accessory_anchor_t,
                out_identifier: &mut uuid_t,
            );
        }
        unsafe { ar_accessory_anchor_get_identifier(accessory_anchor, out_identifier) }
    }

    /// Get the timestamp corresponding to the accessory anchor.
    ///
    ///
    /// Parameter `accessory_anchor`: The accessory anchor.
    ///
    ///
    /// Returns: The timestamp associated with the accessory anchor.
    ///
    /// # Safety
    ///
    /// `accessory_anchor` must implement OS_ar_accessory_anchor.
    #[doc(alias = "ar_accessory_anchor_get_timestamp")]
    #[cfg(all(
        feature = "anchor",
        feature = "objc2",
        feature = "objc2-core-foundation"
    ))]
    #[inline]
    pub unsafe fn timestamp(accessory_anchor: &ar_accessory_anchor_t) -> CFTimeInterval {
        extern "C-unwind" {
            fn ar_accessory_anchor_get_timestamp(
                accessory_anchor: &ar_accessory_anchor_t,
            ) -> CFTimeInterval;
        }
        unsafe { ar_accessory_anchor_get_timestamp(accessory_anchor) }
    }

    /// Determine whether an accessory anchor is tracked.
    ///
    ///
    /// Parameter `accessory_anchor`: The accessory anchor.
    ///
    ///
    /// Returns: `true` if the anchor is tracked, `false` otherwise.
    ///
    /// # Safety
    ///
    /// `accessory_anchor` must implement OS_ar_accessory_anchor.
    #[doc(alias = "ar_accessory_anchor_is_tracked")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn is_tracked(accessory_anchor: &ar_accessory_anchor_t) -> bool {
        extern "C-unwind" {
            fn ar_accessory_anchor_is_tracked(accessory_anchor: &ar_accessory_anchor_t) -> bool;
        }
        unsafe { ar_accessory_anchor_is_tracked(accessory_anchor) }
    }
}

impl ar_accessory_anchors_t {
    /// Get the count of accessory anchors in the collection.
    ///
    ///
    /// Parameter `accessory_anchors`: The collection of accessory anchors.
    ///
    ///
    /// Returns: The number of accessory anchors in the collection.
    ///
    /// # Safety
    ///
    /// `accessory_anchors` must implement OS_ar_accessory_anchors.
    #[doc(alias = "ar_accessory_anchors_get_count")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn count(accessory_anchors: &ar_accessory_anchors_t) -> usize {
        extern "C-unwind" {
            fn ar_accessory_anchors_get_count(accessory_anchors: &ar_accessory_anchors_t) -> usize;
        }
        unsafe { ar_accessory_anchors_get_count(accessory_anchors) }
    }
}

/// Handler for enumerating a collection of accessory anchors.
///
///
/// Parameter `accessory_anchor`: The accessory anchor.
///
///
/// Returns: `true` to continue enumerating to the next accessory anchor in the collection, `false` to stop enumerating.
///
///
/// Note: Enumeration is not thread-safe. The enumerator must not retain or release objects.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessory_anchors_enumerator_t?language=objc)
#[cfg(all(feature = "anchor", feature = "block2", feature = "objc2"))]
pub type ar_accessory_anchors_enumerator_t =
    block2::Block<'static, fn(NonNull<ar_accessory_anchor_t>) -> bool>;

impl ar_accessory_anchors_t {
    /// Enumerate a collection of accessory anchors.
    ///
    ///
    /// Parameter `accessory_anchors`: A collection of accessory anchors.
    ///
    /// Parameter `accessory_anchors_enumerator`: Enumeration handler.
    ///
    ///
    /// Note: Enumeration is not thread-safe. The enumerator must not retain or release objects.
    ///
    /// # Safety
    ///
    /// `accessory_anchors` must implement OS_ar_accessory_anchors.
    #[doc(alias = "ar_accessory_anchors_enumerate_anchors")]
    #[cfg(all(feature = "anchor", feature = "block2", feature = "objc2"))]
    #[inline]
    pub unsafe fn enumerate_anchors(
        accessory_anchors: &ar_accessory_anchors_t,
        accessory_anchors_enumerator: &ar_accessory_anchors_enumerator_t,
    ) {
        extern "C-unwind" {
            fn ar_accessory_anchors_enumerate_anchors(
                accessory_anchors: &ar_accessory_anchors_t,
                accessory_anchors_enumerator: &ar_accessory_anchors_enumerator_t,
            );
        }
        unsafe {
            ar_accessory_anchors_enumerate_anchors(accessory_anchors, accessory_anchors_enumerator)
        }
    }
}

/// Function for enumerating a collection of accessory anchors.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `accessory_anchor`: The accessory anchor.
///
///
/// Returns: `true` to continue enumerating to the next accessory anchor in the collection, `false` to stop enumerating.
///
///
/// Note: Enumeration is not thread-safe. The enumerator must not retain or release objects.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessory_anchors_enumerator_function_t?language=objc)
#[cfg(all(feature = "anchor", feature = "objc2"))]
pub type ar_accessory_anchors_enumerator_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &ar_accessory_anchor_t) -> bool;

impl ar_accessory_anchors_t {
    /// Enumerate a collection of acessory anchors.
    ///
    ///
    /// Parameter `accessory_anchors`: A collection of accessory anchors.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `accessory_anchors_enumerator_function`: Enumeration function.
    ///
    ///
    /// Note: Enumeration is not thread-safe. The enumerator must not retain or release objects.
    ///
    /// # Safety
    ///
    /// - `accessory_anchors` must implement OS_ar_accessory_anchors.
    /// - `context` must be a valid pointer or null.
    /// - `accessory_anchors_enumerator_function` must be implemented correctly.
    #[doc(alias = "ar_accessory_anchors_enumerate_anchors_f")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn enumerate_anchors_f(
        accessory_anchors: &ar_accessory_anchors_t,
        context: *mut c_void,
        accessory_anchors_enumerator_function: ar_accessory_anchors_enumerator_function_t,
    ) {
        extern "C-unwind" {
            fn ar_accessory_anchors_enumerate_anchors_f(
                accessory_anchors: &ar_accessory_anchors_t,
                context: *mut c_void,
                accessory_anchors_enumerator_function: ar_accessory_anchors_enumerator_function_t,
            );
        }
        unsafe {
            ar_accessory_anchors_enumerate_anchors_f(
                accessory_anchors,
                context,
                accessory_anchors_enumerator_function,
            )
        }
    }
}

impl ar_accessory_tracking_configuration_t {
    /// Create an accessory tracking configuration.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_accessory_tracking_configuration_t`.
    #[doc(alias = "ar_accessory_tracking_configuration_create")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn new() -> Retained<ar_accessory_tracking_configuration_t> {
        extern "C-unwind" {
            fn ar_accessory_tracking_configuration_create(
            ) -> *mut ar_accessory_tracking_configuration_t;
        }
        let ret = unsafe { ar_accessory_tracking_configuration_create() };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Set accessories to track for the configuration.
    ///
    ///
    /// Parameter `configuration`: Configuration to set accessories for.
    ///
    /// Parameter `accessories`: Accessories to add to the configuration.
    ///
    /// # Safety
    ///
    /// - `configuration` must implement OS_ar_accessory_tracking_configuration.
    /// - `accessories` must implement OS_ar_accessories.
    #[doc(alias = "ar_accessory_tracking_configuration_set_accessories")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn set_accessories(
        configuration: &ar_accessory_tracking_configuration_t,
        accessories: &ar_accessories_t,
    ) {
        extern "C-unwind" {
            fn ar_accessory_tracking_configuration_set_accessories(
                configuration: &ar_accessory_tracking_configuration_t,
                accessories: &ar_accessories_t,
            );
        }
        unsafe { ar_accessory_tracking_configuration_set_accessories(configuration, accessories) }
    }
}

impl ar_accessory_tracking_provider_t {
    /// Create an accessory tracking provider.
    ///
    ///
    /// Parameter `accessory_tracking_configuration`: accessory tracking configuration.
    ///
    ///
    /// See: `ar_session_t` to run this accessory tracking provider.
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_accessory_tracking_provider_t`.
    ///
    /// # Safety
    ///
    /// `accessory_tracking_configuration` must implement OS_ar_accessory_tracking_configuration.
    #[doc(alias = "ar_accessory_tracking_provider_create")]
    #[cfg(all(feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn new(
        accessory_tracking_configuration: &ar_accessory_tracking_configuration_t,
    ) -> Retained<ar_accessory_tracking_provider_t> {
        extern "C-unwind" {
            fn ar_accessory_tracking_provider_create(
                accessory_tracking_configuration: &ar_accessory_tracking_configuration_t,
            ) -> *mut ar_accessory_tracking_provider_t;
        }
        let ret =
            unsafe { ar_accessory_tracking_provider_create(accessory_tracking_configuration) };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }
}

/// Handler called when there are updates to accessory anchors.
///
///
/// Parameter `added_anchors`: The collection of anchors that were added.
///
/// Parameter `updated_anchors`: The collection of anchors that were updated.
///
/// Parameter `removed_anchors`: The collection of anchors that were removed.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessory_tracking_update_handler_t?language=objc)
#[cfg(all(feature = "block2", feature = "objc2"))]
pub type ar_accessory_tracking_update_handler_t = block2::Block<
    'static,
    fn(
        NonNull<ar_accessory_anchors_t>,
        NonNull<ar_accessory_anchors_t>,
        NonNull<ar_accessory_anchors_t>,
    ),
>;

impl ar_accessory_tracking_provider_t {
    /// Set the handler for receiving accessory anchor updates.
    ///
    /// Note: Routine anchor updates will be disabled unless a handler is provided to this method. This is done to save CPU time for applications which do
    /// not need an anchor stream.
    ///
    ///
    /// Parameter `accessory_tracking_provider`: The accessory tracking provider.
    ///
    /// Parameter `accessory_tracking_updates_queue`: The queue on which the handler will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `accessory_tracking_update_handler`: The handler to be called when new accessory tracking data arrives.
    ///
    ///
    /// Note: Setting this handler will override the function set using `ar_accessory_tracking_provider_set_update_handler_f`.
    ///
    /// # Safety
    ///
    /// - `accessory_tracking_provider` must implement OS_ar_accessory_tracking_provider.
    /// - `accessory_tracking_updates_queue` possibly has additional threading requirements.
    #[doc(alias = "ar_accessory_tracking_provider_set_update_handler")]
    #[cfg(all(
        feature = "block2",
        feature = "data_provider",
        feature = "dispatch2",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn set_update_handler(
        accessory_tracking_provider: &ar_accessory_tracking_provider_t,
        accessory_tracking_updates_queue: Option<&DispatchQueue>,
        accessory_tracking_update_handler: Option<&ar_accessory_tracking_update_handler_t>,
    ) {
        extern "C-unwind" {
            fn ar_accessory_tracking_provider_set_update_handler(
                accessory_tracking_provider: &ar_accessory_tracking_provider_t,
                accessory_tracking_updates_queue: Option<&DispatchQueue>,
                accessory_tracking_update_handler: Option<&ar_accessory_tracking_update_handler_t>,
            );
        }
        unsafe {
            ar_accessory_tracking_provider_set_update_handler(
                accessory_tracking_provider,
                accessory_tracking_updates_queue,
                accessory_tracking_update_handler,
            )
        }
    }
}

/// Function called when there are updates to accessory anchors.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `added_anchors`: The collection of anchors that were added.
///
/// Parameter `updated_anchors`: The collection of anchors that were updated.
///
/// Parameter `removed_anchors`: The collection of anchors that were removed.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_accessory_tracking_update_handler_function_t?language=objc)
#[cfg(feature = "objc2")]
pub type ar_accessory_tracking_update_handler_function_t = unsafe extern "C-unwind" fn(
    *mut c_void,
    &ar_accessory_anchors_t,
    &ar_accessory_anchors_t,
    &ar_accessory_anchors_t,
);

impl ar_accessory_tracking_provider_t {
    /// Set the function for receiving accessory tracking updates.
    ///
    ///
    /// Parameter `accessory_tracking_provider`: The accessory tracking provider.
    ///
    /// Parameter `accessory_tracking_updates_queue`: The queue on which the function will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `accessory_tracking_update_handler_function`: The function to be called when new accessory tracking data arrives.
    ///
    ///
    /// Note: Setting this function will override the handler set using `ar_accessory_tracking_provider_set_update_handler`.
    ///
    /// # Safety
    ///
    /// - `accessory_tracking_provider` must implement OS_ar_accessory_tracking_provider.
    /// - `accessory_tracking_updates_queue` possibly has additional threading requirements.
    /// - `context` must be a valid pointer or null.
    /// - `accessory_tracking_update_handler_function` must be implemented correctly.
    #[doc(alias = "ar_accessory_tracking_provider_set_update_handler_f")]
    #[cfg(all(feature = "data_provider", feature = "dispatch2", feature = "objc2"))]
    #[inline]
    pub unsafe fn set_update_handler_f(
        accessory_tracking_provider: &ar_accessory_tracking_provider_t,
        accessory_tracking_updates_queue: Option<&DispatchQueue>,
        context: *mut c_void,
        accessory_tracking_update_handler_function: Option<
            ar_accessory_tracking_update_handler_function_t,
        >,
    ) {
        extern "C-unwind" {
            fn ar_accessory_tracking_provider_set_update_handler_f(
                accessory_tracking_provider: &ar_accessory_tracking_provider_t,
                accessory_tracking_updates_queue: Option<&DispatchQueue>,
                context: *mut c_void,
                accessory_tracking_update_handler_function: Option<
                    ar_accessory_tracking_update_handler_function_t,
                >,
            );
        }
        unsafe {
            ar_accessory_tracking_provider_set_update_handler_f(
                accessory_tracking_provider,
                accessory_tracking_updates_queue,
                context,
                accessory_tracking_update_handler_function,
            )
        }
    }

    /// Determines whether this device supports the accessory tracking provider.
    ///
    ///
    /// Returns: Returns `true` if the accessory tracking provider is supported on this device, `false` otherwise.
    #[doc(alias = "ar_accessory_tracking_provider_is_supported")]
    #[inline]
    pub unsafe fn is_supported() -> bool {
        extern "C-unwind" {
            fn ar_accessory_tracking_provider_is_supported() -> bool;
        }
        unsafe { ar_accessory_tracking_provider_is_supported() }
    }

    /// Get the authorization type required by the accessory tracking provider.
    ///
    ///
    /// Returns: Authorization type.
    #[doc(alias = "ar_accessory_tracking_provider_get_required_authorization_type")]
    #[cfg(feature = "authorization")]
    #[inline]
    pub unsafe fn required_authorization_type() -> ar_authorization_type_t {
        extern "C-unwind" {
            fn ar_accessory_tracking_provider_get_required_authorization_type(
            ) -> ar_authorization_type_t;
        }
        unsafe { ar_accessory_tracking_provider_get_required_authorization_type() }
    }

    /// Retrieves the latest anchors updated with the most recent inertial data.
    ///
    /// These anchors provide higher frequency, lower latency and slightly lower accuracy than the anchors from the update handler.
    /// Use them directly or in combination with `ar_accessory_tracking_provider_predict_anchor_at_timestamp`.
    ///
    ///
    /// Parameter `accessory_tracking_provider`: An accessory tracking provider.
    ///
    ///
    /// Note: This collection is managed by the provider and is not safe for the caller to release. It has the same lifetime as this
    /// `accessory_tracking_provider`. This collection is not thread safe.
    ///
    /// Returns: An `ar_accessory_anchors_t` collection of latest anchors.
    ///
    /// # Safety
    ///
    /// `accessory_tracking_provider` must implement OS_ar_accessory_tracking_provider.
    #[doc(alias = "ar_accessory_tracking_provider_get_latest_anchors")]
    #[cfg(all(feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn latest_anchors(
        accessory_tracking_provider: &ar_accessory_tracking_provider_t,
    ) -> Retained<ar_accessory_anchors_t> {
        extern "C-unwind" {
            fn ar_accessory_tracking_provider_get_latest_anchors(
                accessory_tracking_provider: &ar_accessory_tracking_provider_t,
            ) -> *mut ar_accessory_anchors_t;
        }
        let ret = unsafe {
            ar_accessory_tracking_provider_get_latest_anchors(accessory_tracking_provider)
        };
        unsafe { Retained::retain_autoreleased(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Predict an accessory anchor to a target timestamp.
    ///
    /// Example usage:
    /// ```text
    /// auto timing_info = cp_drawable_get_frame_timing(drawable);
    /// auto time = cp_time_to_cf_time_interval(cp_frame_timing_get_trackable_anchor_time(timing_info));
    /// const BOOL success = ar_accessory_tracking_provider_predict_anchor_at_timestamp(_provider, anchor_id, timestamp, accessory_anchor);
    /// ```
    ///
    ///
    /// Parameter `accessory_tracking_provider`: An accessory tracking provider.
    ///
    /// Parameter `anchor`: Anchor to predict. Use `ar_accessory_tracking_provider_get_latest_anchors` to get latest anchors. Use tracked
    /// anchors to predict.
    ///
    /// Parameter `timestamp`: The timestamp to get the accessory anchor at. The timestamp should be provided as mach absolute time in seconds.
    ///
    /// Parameter `predicted_anchor`: The output predicted accessory anchor.
    ///
    ///
    /// Note: A large time offset from latest anchor timestamp could degrade accuracy. For accuracy sensitive use cases like drawing,
    /// use a small offset or the latest anchor. Use a prediction timestamp smaller than the latest anchor timestamp for interpolation.
    ///
    ///
    /// Returns: Whether accessory anchor prediction was successful.
    ///
    /// # Safety
    ///
    /// - `accessory_tracking_provider` must implement OS_ar_accessory_tracking_provider.
    /// - `anchor` must implement OS_ar_accessory_anchor.
    /// - `predicted_anchor` must implement OS_ar_accessory_anchor.
    #[doc(alias = "ar_accessory_tracking_provider_predict_anchor_at_timestamp")]
    #[cfg(all(
        feature = "anchor",
        feature = "data_provider",
        feature = "objc2",
        feature = "objc2-core-foundation"
    ))]
    #[inline]
    pub unsafe fn predict_anchor_at_timestamp(
        accessory_tracking_provider: &ar_accessory_tracking_provider_t,
        anchor: &ar_accessory_anchor_t,
        timestamp: CFTimeInterval,
        predicted_anchor: &ar_accessory_anchor_t,
    ) -> bool {
        extern "C-unwind" {
            fn ar_accessory_tracking_provider_predict_anchor_at_timestamp(
                accessory_tracking_provider: &ar_accessory_tracking_provider_t,
                anchor: &ar_accessory_anchor_t,
                timestamp: CFTimeInterval,
                predicted_anchor: &ar_accessory_anchor_t,
            ) -> bool;
        }
        unsafe {
            ar_accessory_tracking_provider_predict_anchor_at_timestamp(
                accessory_tracking_provider,
                anchor,
                timestamp,
                predicted_anchor,
            )
        }
    }
}
