//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::cell::UnsafeCell;
use core::ffi::*;
use core::marker::{PhantomData, PhantomPinned};
use core::ptr::NonNull;
#[cfg(feature = "dispatch2")]
use dispatch2::*;
#[cfg(feature = "objc2-core-foundation")]
use objc2_core_foundation::*;

use crate::*;

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_anchor_t?language=objc)
#[repr(C)]
pub struct ar_anchor_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_anchor_t {}
);

impl ar_anchor_t {
    /// Get the identifier of an anchor.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    /// Parameter `out_identifier`: A pointer to a UUID to fill out with the anchor identifier. Must be non-null.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_anchor.
    #[doc(alias = "ar_anchor_get_identifier")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn identifier(anchor: &ar_anchor_t, out_identifier: &mut uuid_t) {
        extern "C-unwind" {
            fn ar_anchor_get_identifier(anchor: &ar_anchor_t, out_identifier: &mut uuid_t);
        }
        unsafe { ar_anchor_get_identifier(anchor, out_identifier) }
    }

    /// Get the timestamp corresponding to an anchor.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    ///
    /// Returns: The timestamp associated with the anchor.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_anchor.
    #[doc(alias = "ar_anchor_get_timestamp")]
    #[cfg(all(feature = "objc2", feature = "objc2-core-foundation"))]
    #[inline]
    pub unsafe fn timestamp(anchor: &ar_anchor_t) -> CFTimeInterval {
        extern "C-unwind" {
            fn ar_anchor_get_timestamp(anchor: &ar_anchor_t) -> CFTimeInterval;
        }
        unsafe { ar_anchor_get_timestamp(anchor) }
    }
}

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_trackable_anchor_t?language=objc)
#[repr(C)]
pub struct ar_trackable_anchor_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_trackable_anchor_t {}
);

impl ar_trackable_anchor_t {
    /// Determine whether an anchor is tracked.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    ///
    /// Returns: `true` if the anchor is tracked, `false` otherwise.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_trackable_anchor.
    #[doc(alias = "ar_trackable_anchor_is_tracked")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn is_tracked(anchor: &ar_trackable_anchor_t) -> bool {
        extern "C-unwind" {
            fn ar_trackable_anchor_is_tracked(anchor: &ar_trackable_anchor_t) -> bool;
        }
        unsafe { ar_trackable_anchor_is_tracked(anchor) }
    }
}
