//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::cell::UnsafeCell;
use core::ffi::*;
use core::marker::{PhantomData, PhantomPinned};
use core::ptr::NonNull;
#[cfg(feature = "dispatch2")]
use dispatch2::*;
#[cfg(feature = "objc2")]
use objc2::__framework_prelude::*;

use crate::*;

/// Status of an authorization for ARKit data.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_authorization_status_t?language=objc)
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct ar_authorization_status_t(pub isize);
impl ar_authorization_status_t {
    /// Status of an authorization for ARKit data.
    #[doc(alias = "ar_authorization_status_not_determined")]
    pub const not_determined: Self = Self(0);
    /// Status of an authorization for ARKit data.
    #[doc(alias = "ar_authorization_status_allowed")]
    pub const allowed: Self = Self(1);
    /// Status of an authorization for ARKit data.
    #[doc(alias = "ar_authorization_status_denied")]
    pub const denied: Self = Self(2);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ar_authorization_status_t {
    const ENCODING: Encoding = isize::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ar_authorization_status_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// Types of authorization for ARKit data.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_authorization_type_t?language=objc)
// NS_OPTIONS
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct ar_authorization_type_t(pub usize);
bitflags::bitflags! {
    impl ar_authorization_type_t: usize {
/// Types of authorization for ARKit data.
        #[doc(alias = "ar_authorization_type_none")]
        const none = 0;
/// Authorization type used when requesting hand tracking.
///
/// See: `ar_hand_tracking_provider_t`
        #[doc(alias = "ar_authorization_type_hand_tracking")]
        const hand_tracking = 1<<0;
/// Authorization type used when requesting:
/// - Image tracking
///
/// See: `ar_image_tracking_provider_t`
/// - Plane detection
///
/// See: `ar_plane_detection_provider_t`
/// - Scene reconstruction
///
/// See: `ar_scene_reconstruction_provider_t`
        #[doc(alias = "ar_authorization_type_world_sensing")]
        const world_sensing = 1<<1;
/// Authorization type used when requesting:
/// - Camera access
///
/// See: `ar_camera_frame_provider_t`
        #[doc(alias = "ar_authorization_type_camera_access")]
        const camera_access = 1<<3;
/// Authorization type used when requesting:
/// - Accessory tracking
///
/// See: `ar_accessory_tracking_provider_t`
        #[doc(alias = "ar_authorization_type_accessory_tracking")]
        const accessory_tracking = 1<<5;
        const _ = !0;
    }
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ar_authorization_type_t {
    const ENCODING: Encoding = usize::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ar_authorization_type_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_authorization_result_t?language=objc)
#[repr(C)]
pub struct ar_authorization_result_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_authorization_result_t {}
);

impl ar_authorization_result_t {
    /// Get the authorization type associated with an authorization result.
    ///
    ///
    /// Parameter `authorization_result`: The authorization result.
    ///
    ///
    /// Returns: The authorization type.
    ///
    /// # Safety
    ///
    /// `authorization_result` must implement OS_ar_authorization_result.
    #[doc(alias = "ar_authorization_result_get_authorization_type")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn authorization_type(
        authorization_result: &ar_authorization_result_t,
    ) -> ar_authorization_type_t {
        extern "C-unwind" {
            fn ar_authorization_result_get_authorization_type(
                authorization_result: &ar_authorization_result_t,
            ) -> ar_authorization_type_t;
        }
        unsafe { ar_authorization_result_get_authorization_type(authorization_result) }
    }

    /// Get the authorization status associated with an authorization result.
    ///
    ///
    /// Parameter `authorization_result`: The authorization result.
    ///
    ///
    /// Returns: The authorization status.
    ///
    /// # Safety
    ///
    /// `authorization_result` must implement OS_ar_authorization_result.
    #[doc(alias = "ar_authorization_result_get_status")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn status(
        authorization_result: &ar_authorization_result_t,
    ) -> ar_authorization_status_t {
        extern "C-unwind" {
            fn ar_authorization_result_get_status(
                authorization_result: &ar_authorization_result_t,
            ) -> ar_authorization_status_t;
        }
        unsafe { ar_authorization_result_get_status(authorization_result) }
    }
}

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_authorization_results_t?language=objc)
#[repr(C)]
pub struct ar_authorization_results_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_authorization_results_t {}
);

impl ar_authorization_results_t {
    /// Get the count of authorization results in a collection.
    ///
    ///
    /// Parameter `authorization_results`: The collection of authorization results.
    ///
    ///
    /// Returns: The number of authorization results in the collection.
    ///
    /// # Safety
    ///
    /// `authorization_results` must implement OS_ar_authorization_results.
    #[doc(alias = "ar_authorization_results_get_count")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn count(authorization_results: &ar_authorization_results_t) -> usize {
        extern "C-unwind" {
            fn ar_authorization_results_get_count(
                authorization_results: &ar_authorization_results_t,
            ) -> usize;
        }
        unsafe { ar_authorization_results_get_count(authorization_results) }
    }
}

/// Handler for enumerating a collection of authorization results.
///
///
/// Parameter `authorization_result`: The authorization result.
///
///
/// Returns: `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_authorization_results_enumerator_t?language=objc)
#[cfg(all(feature = "block2", feature = "objc2"))]
pub type ar_authorization_results_enumerator_t =
    block2::Block<'static, fn(NonNull<ar_authorization_result_t>) -> bool>;

impl ar_authorization_results_t {
    /// Enumerate a collection of authorization results.
    ///
    ///
    /// Parameter `authorization_results`: The collection of authorization results.
    ///
    /// Parameter `authorization_results_enumerator`: The enumerator handler.
    ///
    /// # Safety
    ///
    /// `authorization_results` must implement OS_ar_authorization_results.
    #[doc(alias = "ar_authorization_results_enumerate_results")]
    #[cfg(all(feature = "block2", feature = "objc2"))]
    #[inline]
    pub unsafe fn enumerate_results(
        authorization_results: &ar_authorization_results_t,
        authorization_results_enumerator: &ar_authorization_results_enumerator_t,
    ) {
        extern "C-unwind" {
            fn ar_authorization_results_enumerate_results(
                authorization_results: &ar_authorization_results_t,
                authorization_results_enumerator: &ar_authorization_results_enumerator_t,
            );
        }
        unsafe {
            ar_authorization_results_enumerate_results(
                authorization_results,
                authorization_results_enumerator,
            )
        }
    }
}

/// Function for enumerating a collection of authorization results.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `authorization_result`: The authorization result.
///
///
/// Returns: `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_authorization_results_enumerator_function_t?language=objc)
#[cfg(feature = "objc2")]
pub type ar_authorization_results_enumerator_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &ar_authorization_result_t) -> bool;

impl ar_authorization_results_t {
    /// Enumerate a collection of authorization results using a function.
    ///
    ///
    /// Parameter `authorization_results`: The collection of authorization results.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `authorization_results_enumerator_function`: The enumerator function.
    ///
    /// # Safety
    ///
    /// - `authorization_results` must implement OS_ar_authorization_results.
    /// - `context` must be a valid pointer or null.
    /// - `authorization_results_enumerator_function` must be implemented correctly.
    #[doc(alias = "ar_authorization_results_enumerate_results_f")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn enumerate_results_f(
        authorization_results: &ar_authorization_results_t,
        context: *mut c_void,
        authorization_results_enumerator_function: ar_authorization_results_enumerator_function_t,
    ) {
        extern "C-unwind" {
            fn ar_authorization_results_enumerate_results_f(
                authorization_results: &ar_authorization_results_t,
                context: *mut c_void,
                authorization_results_enumerator_function: ar_authorization_results_enumerator_function_t,
            );
        }
        unsafe {
            ar_authorization_results_enumerate_results_f(
                authorization_results,
                context,
                authorization_results_enumerator_function,
            )
        }
    }
}
