//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::cell::UnsafeCell;
use core::ffi::*;
use core::marker::{PhantomData, PhantomPinned};
use core::ptr::NonNull;
#[cfg(feature = "dispatch2")]
use dispatch2::*;
#[cfg(feature = "objc2")]
use objc2::__framework_prelude::*;
#[cfg(feature = "objc2-core-foundation")]
use objc2_core_foundation::*;

use crate::*;

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_barcode_anchor_t?language=objc)
#[repr(C)]
pub struct ar_barcode_anchor_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_barcode_anchor_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_barcode_anchors_t?language=objc)
#[repr(C)]
pub struct ar_barcode_anchors_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_barcode_anchors_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_barcode_detection_configuration_t?language=objc)
#[repr(C)]
pub struct ar_barcode_detection_configuration_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_barcode_detection_configuration_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_barcode_detection_callbacks_t?language=objc)
#[repr(C)]
pub struct ar_barcode_detection_callbacks_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_barcode_detection_callbacks_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_barcode_detection_provider_t?language=objc)
#[repr(C)]
pub struct ar_barcode_detection_provider_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_barcode_detection_provider_t {}
);

/// Option set describing possible symbologies of a detected barcode.
///
///
/// Note: An `ar_barcode_anchor_t` has exactly one symbology. Multiple bits may be set to configure the `ar_barcode_detection_provider_t` to detect multiple symbologies.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_barcode_detection_symbology_t?language=objc)
// NS_OPTIONS
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct ar_barcode_detection_symbology_t(pub u64);
bitflags::bitflags! {
    impl ar_barcode_detection_symbology_t: u64 {
/// Option set describing possible symbologies of a detected barcode.
///
///
/// Note: An `ar_barcode_anchor_t` has exactly one symbology. Multiple bits may be set to configure the `ar_barcode_detection_provider_t` to detect multiple symbologies.
        #[doc(alias = "ar_barcode_detection_symbology_none")]
        const none = 0;
/// Aztec symbology. Decodable at 40 cm distance when greater than 2.0 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_aztec")]
        const aztec = 1<<0;
/// Codabar symbology. Decodable at 40 cm distance when greater than 5.5 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_codabar")]
        const codabar = 1<<1;
/// Code 39 symbology. Decodable at 40 cm distance when greater than 6.5 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_code_39")]
        const code_39 = 1<<2;
/// Code 39 Checksum symbology. Decodable at 40 cm distance when greater than 6.5 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_code_39_checksum")]
        const code_39_checksum = 1<<3;
/// Code 39 Full ASCII symbology. Decodable at 40 cm distance when greater than 3.0 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_code_39_full_ascii")]
        const code_39_full_ascii = 1<<4;
/// Code 39 Full ASCII Checksum symbology. Decodable at 40 cm distance when greater than 4.5 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_code_39_full_ascii_checksum")]
        const code_39_full_ascii_checksum = 1<<5;
/// Code 93 symbology. Decodable at 40 cm distance when greater than 5.0 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_code_93")]
        const code_93 = 1<<6;
/// Code 93i symbology. Decodable at 40 cm distance when greater than 5.0 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_code_93i")]
        const code_93i = 1<<7;
/// Code 128 symbology. Decodable at 40 cm distance when greater than 2.5 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_code_128")]
        const code_128 = 1<<8;
/// Data Matrix symbology. Decodable at 40 cm distance when greater than 1.0 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_data_matrix")]
        const data_matrix = 1<<9;
/// EAN-8 symbology. Decodable at 40 cm distance when greater than 3.0 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_ean_8")]
        const ean_8 = 1<<10;
/// EAN-13 symbology. Decodable at 40 cm distance when greater than 4.0 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_ean_13")]
        const ean_13 = 1<<11;
/// GS1 Databar symbology. Decodable at 40 cm distance when greater than 3.0 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_gs1_databar")]
        const gs1_databar = 1<<12;
/// GS1 Databar Expanded symbology. Decodable at 40 cm distance when greater than 6.5 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_gs1_databar_expanded")]
        const gs1_databar_expanded = 1<<13;
/// GS1 Databar Limited symbology. Decodable at 40 cm distance when greater than 3.0 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_gs1_databar_limited")]
        const gs1_databar_limited = 1<<14;
/// ITF symbology. Decodable at 40 cm distance when greater than 3.5 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_itf")]
        const itf = 1<<15;
/// ITF-14 symbology. Decodable at 40 cm distance when greater than 5.0 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_itf_14")]
        const itf_14 = 1<<16;
/// ITF Checksum symbology. Decodable at 40 cm distance when greater than 3.5 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_itf_checksum")]
        const itf_checksum = 1<<17;
/// MicroPDF417 symbology. Decodable at 40 cm distance when greater than 6.5 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_micropdf417")]
        const micropdf417 = 1<<18;
/// MicroQR symbology. Decodable at 40 cm distance when greater than 2.0 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_microqr")]
        const microqr = 1<<19;
/// MSIPlessey symbology. Decodable at 40 cm distance when greater than 4.5 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_msi_plessey")]
        const msi_plessey = 1<<20;
/// PDF417 symbology. Decodable at 40 cm distance when greater than 6.0 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_pdf417")]
        const pdf417 = 1<<21;
/// QR symbology. Decodable at 40 cm distance when greater than 1.5 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_qr")]
        const qr = 1<<22;
/// UPC-E symbology. Decodable at 40 cm distance when greater than 2.5 cm wide.
        #[doc(alias = "ar_barcode_detection_symbology_upce")]
        const upce = 1<<23;
        const _ = !0;
    }
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ar_barcode_detection_symbology_t {
    const ENCODING: Encoding = u64::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ar_barcode_detection_symbology_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

impl ar_barcode_anchor_t {
    /// Get the symbology of a barcode anchor.
    ///
    ///
    /// Parameter `barcode_anchor`: The barcode anchor.
    ///
    ///
    /// Returns: The barcode anchor's symbology.
    ///
    /// # Safety
    ///
    /// `barcode_anchor` must implement OS_ar_barcode_anchor.
    #[doc(alias = "ar_barcode_anchor_get_symbology")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn symbology(
        barcode_anchor: &ar_barcode_anchor_t,
    ) -> ar_barcode_detection_symbology_t {
        extern "C-unwind" {
            fn ar_barcode_anchor_get_symbology(
                barcode_anchor: &ar_barcode_anchor_t,
            ) -> ar_barcode_detection_symbology_t;
        }
        unsafe { ar_barcode_anchor_get_symbology(barcode_anchor) }
    }

    /// Get the payload string value of a barcode anchor.
    ///
    ///
    /// Parameter `barcode_anchor`: The barcode anchor.
    ///
    ///
    /// Note: The returned value will have the same lifetime as the input barcode anchor.
    ///
    /// Returns: The string representation of the barcode anchor's payload.
    ///
    /// # Safety
    ///
    /// `barcode_anchor` must implement OS_ar_barcode_anchor.
    #[doc(alias = "ar_barcode_anchor_get_payload_string_value")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn payload_string_value(barcode_anchor: &ar_barcode_anchor_t) -> *const c_char {
        extern "C-unwind" {
            fn ar_barcode_anchor_get_payload_string_value(
                barcode_anchor: &ar_barcode_anchor_t,
            ) -> *const c_char;
        }
        unsafe { ar_barcode_anchor_get_payload_string_value(barcode_anchor) }
    }

    /// Get a copy of a barcode anchor's payload data.
    ///
    ///
    /// Parameter `barcode_anchor`: The barcode anchor.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: A copy of the barcode anchor's payload data.
    ///
    /// # Safety
    ///
    /// `barcode_anchor` must implement OS_ar_barcode_anchor.
    #[doc(alias = "ar_barcode_anchor_copy_payload_data")]
    #[cfg(all(feature = "anchor", feature = "data", feature = "objc2"))]
    #[inline]
    pub unsafe fn payload_data(barcode_anchor: &ar_barcode_anchor_t) -> Retained<ar_data_t> {
        extern "C-unwind" {
            fn ar_barcode_anchor_copy_payload_data(
                barcode_anchor: &ar_barcode_anchor_t,
            ) -> *mut ar_data_t;
        }
        let ret = unsafe { ar_barcode_anchor_copy_payload_data(barcode_anchor) };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Get the identifier of an anchor.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    /// Parameter `out_identifier`: A pointer to a UUID to fill out with the anchor identifier. Must be non-null.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_barcode_anchor.
    #[doc(alias = "ar_barcode_anchor_get_identifier")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn identifier(anchor: &ar_barcode_anchor_t, out_identifier: &mut uuid_t) {
        extern "C-unwind" {
            fn ar_barcode_anchor_get_identifier(
                anchor: &ar_barcode_anchor_t,
                out_identifier: &mut uuid_t,
            );
        }
        unsafe { ar_barcode_anchor_get_identifier(anchor, out_identifier) }
    }

    /// Get the timestamp corresponding to an anchor.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    ///
    /// Returns: The timestamp associated with the anchor.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_barcode_anchor.
    #[doc(alias = "ar_barcode_anchor_get_timestamp")]
    #[cfg(all(
        feature = "anchor",
        feature = "objc2",
        feature = "objc2-core-foundation"
    ))]
    #[inline]
    pub unsafe fn timestamp(anchor: &ar_barcode_anchor_t) -> CFTimeInterval {
        extern "C-unwind" {
            fn ar_barcode_anchor_get_timestamp(anchor: &ar_barcode_anchor_t) -> CFTimeInterval;
        }
        unsafe { ar_barcode_anchor_get_timestamp(anchor) }
    }
}

impl ar_barcode_anchors_t {
    /// Get the count of barcode anchors in a collection.
    ///
    ///
    /// Parameter `barcode_anchors`: The collection of barcode anchors.
    ///
    ///
    /// Returns: The number of barcode anchors in the collection.
    ///
    /// # Safety
    ///
    /// `barcode_anchors` must implement OS_ar_barcode_anchors.
    #[doc(alias = "ar_barcode_anchors_get_count")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn count(barcode_anchors: &ar_barcode_anchors_t) -> usize {
        extern "C-unwind" {
            fn ar_barcode_anchors_get_count(barcode_anchors: &ar_barcode_anchors_t) -> usize;
        }
        unsafe { ar_barcode_anchors_get_count(barcode_anchors) }
    }
}

/// Handler for enumerating a collection of barcode anchors.
///
///
/// Parameter `barcode_anchor`: The barcode anchor.
///
///
/// Returns: `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_barcode_anchors_enumerator_t?language=objc)
#[cfg(all(feature = "anchor", feature = "block2", feature = "objc2"))]
pub type ar_barcode_anchors_enumerator_t =
    block2::Block<'static, fn(NonNull<ar_barcode_anchor_t>) -> bool>;

impl ar_barcode_anchors_t {
    /// Enumerate a collection of barcode anchors.
    ///
    ///
    /// Parameter `barcode_anchors`: The collection of barcode anchors.
    ///
    /// Parameter `barcode_anchors_enumerator`: The enumerator handler.
    ///
    /// # Safety
    ///
    /// `barcode_anchors` must implement OS_ar_barcode_anchors.
    #[doc(alias = "ar_barcode_anchors_enumerate_anchors")]
    #[cfg(all(feature = "anchor", feature = "block2", feature = "objc2"))]
    #[inline]
    pub unsafe fn enumerate_anchors(
        barcode_anchors: &ar_barcode_anchors_t,
        barcode_anchors_enumerator: &ar_barcode_anchors_enumerator_t,
    ) {
        extern "C-unwind" {
            fn ar_barcode_anchors_enumerate_anchors(
                barcode_anchors: &ar_barcode_anchors_t,
                barcode_anchors_enumerator: &ar_barcode_anchors_enumerator_t,
            );
        }
        unsafe { ar_barcode_anchors_enumerate_anchors(barcode_anchors, barcode_anchors_enumerator) }
    }
}

/// Function for enumerating a collection of barcode anchors.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `barcode_anchor`: The barcode anchor.
///
///
/// Returns: `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_barcode_anchors_enumerator_function_t?language=objc)
#[cfg(all(feature = "anchor", feature = "objc2"))]
pub type ar_barcode_anchors_enumerator_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &ar_barcode_anchor_t) -> bool;

impl ar_barcode_anchors_t {
    /// Enumerate a collection of barcode anchors using a function.
    ///
    ///
    /// Parameter `barcode_anchors`: The collection of barcode anchors.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `barcode_anchors_enumerator_function`: The enumerator function.
    ///
    /// # Safety
    ///
    /// - `barcode_anchors` must implement OS_ar_barcode_anchors.
    /// - `context` must be a valid pointer or null.
    /// - `barcode_anchors_enumerator_function` must be implemented correctly.
    #[doc(alias = "ar_barcode_anchors_enumerate_anchors_f")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn enumerate_anchors_f(
        barcode_anchors: &ar_barcode_anchors_t,
        context: *mut c_void,
        barcode_anchors_enumerator_function: ar_barcode_anchors_enumerator_function_t,
    ) {
        extern "C-unwind" {
            fn ar_barcode_anchors_enumerate_anchors_f(
                barcode_anchors: &ar_barcode_anchors_t,
                context: *mut c_void,
                barcode_anchors_enumerator_function: ar_barcode_anchors_enumerator_function_t,
            );
        }
        unsafe {
            ar_barcode_anchors_enumerate_anchors_f(
                barcode_anchors,
                context,
                barcode_anchors_enumerator_function,
            )
        }
    }
}

impl ar_barcode_detection_configuration_t {
    /// Create a barcode detection configuration.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_barcode_detection_configuration_t`.
    #[doc(alias = "ar_barcode_detection_configuration_create")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn new() -> Retained<ar_barcode_detection_configuration_t> {
        extern "C-unwind" {
            fn ar_barcode_detection_configuration_create(
            ) -> *mut ar_barcode_detection_configuration_t;
        }
        let ret = unsafe { ar_barcode_detection_configuration_create() };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Set the desired symbologies to detect.
    ///
    ///
    /// Parameter `barcode_detection_configuration`: The barcode detection configuration.
    ///
    /// Parameter `symbology`: The symbologies to detect.
    ///
    /// # Safety
    ///
    /// `barcode_detection_configuration` must implement OS_ar_barcode_detection_configuration.
    #[doc(alias = "ar_barcode_detection_configuration_set_detection_symbology")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn set_detection_symbology(
        barcode_detection_configuration: &ar_barcode_detection_configuration_t,
        symbology: ar_barcode_detection_symbology_t,
    ) {
        extern "C-unwind" {
            fn ar_barcode_detection_configuration_set_detection_symbology(
                barcode_detection_configuration: &ar_barcode_detection_configuration_t,
                symbology: ar_barcode_detection_symbology_t,
            );
        }
        unsafe {
            ar_barcode_detection_configuration_set_detection_symbology(
                barcode_detection_configuration,
                symbology,
            )
        }
    }
}

impl ar_barcode_detection_provider_t {
    /// Create a barcode detection provider.
    ///
    ///
    /// Parameter `barcode_detection_configuration`: An instance of `ar_barcode_detection_configuration_t`.
    ///
    ///
    /// See: `ar_session_t` to run this barcode detection provider.
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_barcode_detection_provider_t`.
    ///
    /// # Safety
    ///
    /// `barcode_detection_configuration` must implement OS_ar_barcode_detection_configuration.
    #[doc(alias = "ar_barcode_detection_provider_create")]
    #[cfg(all(feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn new(
        barcode_detection_configuration: &ar_barcode_detection_configuration_t,
    ) -> Retained<ar_barcode_detection_provider_t> {
        extern "C-unwind" {
            fn ar_barcode_detection_provider_create(
                barcode_detection_configuration: &ar_barcode_detection_configuration_t,
            ) -> *mut ar_barcode_detection_provider_t;
        }
        let ret = unsafe { ar_barcode_detection_provider_create(barcode_detection_configuration) };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Determines whether this device supports the barcode detection provider.
    ///
    ///
    /// Returns: Returns `true` if the barcode detection provider is supported on this device, `false` otherwise.
    #[doc(alias = "ar_barcode_detection_provider_is_supported")]
    #[inline]
    pub unsafe fn is_supported() -> bool {
        extern "C-unwind" {
            fn ar_barcode_detection_provider_is_supported() -> bool;
        }
        unsafe { ar_barcode_detection_provider_is_supported() }
    }
}

/// Handler called when there are updates to barcode anchors.
///
///
/// Parameter `added_anchors`: The collection of anchors that were added.
///
/// Parameter `updated_anchors`: The collection of anchors that were updated.
///
/// Parameter `removed_anchors`: The collection of anchors that were removed.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_barcode_detection_update_handler_t?language=objc)
#[cfg(all(feature = "block2", feature = "objc2"))]
pub type ar_barcode_detection_update_handler_t = block2::Block<
    'static,
    fn(NonNull<ar_barcode_anchors_t>, NonNull<ar_barcode_anchors_t>, NonNull<ar_barcode_anchors_t>),
>;

/// Function called when there are updates to barcode anchors.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `added_anchors`: The collection of anchors that were added.
///
/// Parameter `updated_anchors`: The collection of anchors that were updated.
///
/// Parameter `removed_anchors`: The collection of anchors that were removed.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_barcode_detection_update_handler_function_t?language=objc)
#[cfg(feature = "objc2")]
pub type ar_barcode_detection_update_handler_function_t = unsafe extern "C-unwind" fn(
    *mut c_void,
    &ar_barcode_anchors_t,
    &ar_barcode_anchors_t,
    &ar_barcode_anchors_t,
);

impl ar_barcode_detection_provider_t {
    /// Set the handler for receiving barcode detection updates.
    ///
    ///
    /// Parameter `barcode_detection_provider`: The barcode detection provider.
    ///
    /// Parameter `barcode_detection_updates_queue`: The queue on which the handler will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `barcode_detection_update_handler`: Handler to be called when new anchor data arrives. Refer to `ar_barcode_detection_update_handler_t` for
    /// handler signature.
    ///
    ///
    /// Note: Setting this handler will override the function set using `ar_barcode_detection_provider_set_update_handler_f`.
    ///
    /// # Safety
    ///
    /// - `barcode_detection_provider` must implement OS_ar_barcode_detection_provider.
    /// - `barcode_detection_updates_queue` possibly has additional threading requirements.
    #[doc(alias = "ar_barcode_detection_provider_set_update_handler")]
    #[cfg(all(
        feature = "block2",
        feature = "data_provider",
        feature = "dispatch2",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn set_update_handler(
        barcode_detection_provider: &ar_barcode_detection_provider_t,
        barcode_detection_updates_queue: Option<&DispatchQueue>,
        barcode_detection_update_handler: Option<&ar_barcode_detection_update_handler_t>,
    ) {
        extern "C-unwind" {
            fn ar_barcode_detection_provider_set_update_handler(
                barcode_detection_provider: &ar_barcode_detection_provider_t,
                barcode_detection_updates_queue: Option<&DispatchQueue>,
                barcode_detection_update_handler: Option<&ar_barcode_detection_update_handler_t>,
            );
        }
        unsafe {
            ar_barcode_detection_provider_set_update_handler(
                barcode_detection_provider,
                barcode_detection_updates_queue,
                barcode_detection_update_handler,
            )
        }
    }

    /// Set the function for receiving barcode detection updates.
    ///
    ///
    /// Parameter `barcode_detection_provider`: The barcode detection provider.
    ///
    /// Parameter `barcode_detection_updates_queue`: The queue on which the handler will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `barcode_detection_update_handler_function`: The function to be called when new barcode detection updates arrive.
    ///
    ///
    /// Note: Setting this function will override the handler set using `ar_barcode_detection_provider_set_update_handler`.
    ///
    /// # Safety
    ///
    /// - `barcode_detection_provider` must implement OS_ar_barcode_detection_provider.
    /// - `barcode_detection_updates_queue` possibly has additional threading requirements.
    /// - `context` must be a valid pointer or null.
    /// - `barcode_detection_update_handler_function` must be implemented correctly.
    #[doc(alias = "ar_barcode_detection_provider_set_update_handler_f")]
    #[cfg(all(feature = "data_provider", feature = "dispatch2", feature = "objc2"))]
    #[inline]
    pub unsafe fn set_update_handler_f(
        barcode_detection_provider: &ar_barcode_detection_provider_t,
        barcode_detection_updates_queue: Option<&DispatchQueue>,
        context: *mut c_void,
        barcode_detection_update_handler_function: Option<
            ar_barcode_detection_update_handler_function_t,
        >,
    ) {
        extern "C-unwind" {
            fn ar_barcode_detection_provider_set_update_handler_f(
                barcode_detection_provider: &ar_barcode_detection_provider_t,
                barcode_detection_updates_queue: Option<&DispatchQueue>,
                context: *mut c_void,
                barcode_detection_update_handler_function: Option<
                    ar_barcode_detection_update_handler_function_t,
                >,
            );
        }
        unsafe {
            ar_barcode_detection_provider_set_update_handler_f(
                barcode_detection_provider,
                barcode_detection_updates_queue,
                context,
                barcode_detection_update_handler_function,
            )
        }
    }

    /// Get the authorization type required by the barcode detection provider.
    ///
    ///
    /// Returns: The required authorization type.
    #[doc(alias = "ar_barcode_detection_provider_get_required_authorization_type")]
    #[cfg(feature = "authorization")]
    #[inline]
    pub unsafe fn required_authorization_type() -> ar_authorization_type_t {
        extern "C-unwind" {
            fn ar_barcode_detection_provider_get_required_authorization_type(
            ) -> ar_authorization_type_t;
        }
        unsafe { ar_barcode_detection_provider_get_required_authorization_type() }
    }
}
