//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::cell::UnsafeCell;
use core::ffi::*;
use core::marker::{PhantomData, PhantomPinned};
use core::ptr::NonNull;
#[cfg(feature = "dispatch2")]
use dispatch2::*;
#[cfg(feature = "objc2")]
use objc2::__framework_prelude::*;
#[cfg(feature = "objc2-core-foundation")]
use objc2_core_foundation::*;
#[cfg(feature = "objc2-core-video")]
use objc2_core_video::*;

use crate::*;

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_camera_region_anchor_t?language=objc)
#[repr(C)]
pub struct ar_camera_region_anchor_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_camera_region_anchor_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_camera_region_anchors_t?language=objc)
#[repr(C)]
pub struct ar_camera_region_anchors_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_camera_region_anchors_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_camera_region_configuration_t?language=objc)
#[repr(C)]
pub struct ar_camera_region_configuration_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_camera_region_configuration_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_camera_region_provider_t?language=objc)
#[repr(C)]
pub struct ar_camera_region_provider_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_camera_region_provider_t {}
);

/// Error codes specific to the camera region provider.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_camera_region_error_code_t?language=objc)
#[cfg(feature = "error")]
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ar_camera_region_error_code_t(pub ar_error_code_t);
#[cfg(feature = "error")]
impl ar_camera_region_error_code_t {
    /// Error code indicating that a camera region anchor failed to be added.
    #[doc(alias = "ar_camera_region_error_code_add_anchor_failed")]
    pub const add_anchor_failed: Self = Self(1300);
    /// Error code indicating that the maximum amount of camera region anchors for its respective camera enhancement have been added.
    #[doc(alias = "ar_camera_region_error_code_anchor_max_limit_reached")]
    pub const anchor_max_limit_reached: Self = Self(1301);
    /// Error code indicating that a camera region anchor failed to be removed.
    #[doc(alias = "ar_camera_region_error_code_remove_anchor_failed")]
    pub const remove_anchor_failed: Self = Self(1302);
}

#[cfg(all(feature = "error", feature = "objc2"))]
unsafe impl Encode for ar_camera_region_error_code_t {
    const ENCODING: Encoding = ar_error_code_t::ENCODING;
}

#[cfg(all(feature = "error", feature = "objc2"))]
unsafe impl RefEncode for ar_camera_region_error_code_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// Enum describing camera enhancement types.
///
/// Note: These will affect the frame rate of the output.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_camera_region_camera_enhancement_t?language=objc)
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct ar_camera_region_camera_enhancement_t(pub isize);
impl ar_camera_region_camera_enhancement_t {
    /// Solely camera stabilization. Implicitly included in other enhancements.
    #[doc(alias = "ar_camera_region_stabilization")]
    pub const stabilization: Self = Self(0);
    /// Contrast
    /// &
    /// Vibrancy enhancement.
    #[doc(alias = "ar_camera_region_contrast_and_vibrancy")]
    pub const contrast_and_vibrancy: Self = Self(1);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ar_camera_region_camera_enhancement_t {
    const ENCODING: Encoding = isize::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ar_camera_region_camera_enhancement_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

impl ar_camera_region_anchor_t {
    /// Returns a bool value that indicates whether the two camera region anchors are equal.
    ///
    ///
    /// Parameter `camera_region_anchor`: A camera region anchor to be compared.
    ///
    /// Parameter `other_camera_region_anchor`: The other camera region anchor to be compared to.
    ///
    ///
    /// Returns: `true` if the camera region anchors are equal, `false` otherwise.
    ///
    /// # Safety
    ///
    /// - `camera_region_anchor` must implement OS_ar_camera_region_anchor.
    /// - `other_camera_region_anchor` must implement OS_ar_camera_region_anchor.
    #[doc(alias = "ar_camera_region_anchor_is_equal_to_camera_region_anchor")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn is_equal_to_camera_region_anchor(
        camera_region_anchor: Option<&ar_camera_region_anchor_t>,
        other_camera_region_anchor: Option<&ar_camera_region_anchor_t>,
    ) -> bool {
        extern "C-unwind" {
            fn ar_camera_region_anchor_is_equal_to_camera_region_anchor(
                camera_region_anchor: Option<&ar_camera_region_anchor_t>,
                other_camera_region_anchor: Option<&ar_camera_region_anchor_t>,
            ) -> bool;
        }
        unsafe {
            ar_camera_region_anchor_is_equal_to_camera_region_anchor(
                camera_region_anchor,
                other_camera_region_anchor,
            )
        }
    }

    /// Get the width of a given anchor.
    ///
    ///
    /// Parameter `camera_region_anchor`: The anchor.
    ///
    ///
    /// Returns: The width of the anchor.
    ///
    ///
    /// Note: The width of the anchor is the length along the X-axis, in meters. This is [-width/2, width/2] from the center.
    ///
    /// # Safety
    ///
    /// `camera_region_anchor` must implement OS_ar_camera_region_anchor.
    #[doc(alias = "ar_camera_region_anchor_get_width")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn width(camera_region_anchor: &ar_camera_region_anchor_t) -> c_float {
        extern "C-unwind" {
            fn ar_camera_region_anchor_get_width(
                camera_region_anchor: &ar_camera_region_anchor_t,
            ) -> c_float;
        }
        unsafe { ar_camera_region_anchor_get_width(camera_region_anchor) }
    }

    /// Get the height of a given anchor.
    ///
    ///
    /// Parameter `camera_region_anchor`: The anchor.
    ///
    ///
    /// Returns: The height of the anchor.
    ///
    ///
    /// Note: The height of the anchor is the length along the Y-axis, in meters. This is [-height/2, height/2] from the center.
    ///
    /// # Safety
    ///
    /// `camera_region_anchor` must implement OS_ar_camera_region_anchor.
    #[doc(alias = "ar_camera_region_anchor_get_height")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn height(camera_region_anchor: &ar_camera_region_anchor_t) -> c_float {
        extern "C-unwind" {
            fn ar_camera_region_anchor_get_height(
                camera_region_anchor: &ar_camera_region_anchor_t,
            ) -> c_float;
        }
        unsafe { ar_camera_region_anchor_get_height(camera_region_anchor) }
    }

    /// Get the camera enhancement type for a given anchor.
    ///
    ///
    /// Parameter `camera_region_anchor`: The anchor.
    ///
    ///
    /// Returns: The anchor's camera enhancement.
    ///
    /// # Safety
    ///
    /// `camera_region_anchor` must implement OS_ar_camera_region_anchor.
    #[doc(alias = "ar_camera_region_anchor_get_camera_enhancement")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn camera_enhancement(
        camera_region_anchor: &ar_camera_region_anchor_t,
    ) -> ar_camera_region_camera_enhancement_t {
        extern "C-unwind" {
            fn ar_camera_region_anchor_get_camera_enhancement(
                camera_region_anchor: &ar_camera_region_anchor_t,
            ) -> ar_camera_region_camera_enhancement_t;
        }
        unsafe { ar_camera_region_anchor_get_camera_enhancement(camera_region_anchor) }
    }

    /// Get the `CVPixelBufferRef` for this anchor.
    ///
    ///
    /// Parameter `camera_region_anchor`: The anchor.
    ///
    ///
    /// Returns: The pixel buffer, or NULL if not set. Retain and release as necessary.
    ///
    ///
    /// Note: Retaining too many pixel buffers may lead to memory issues.
    ///
    /// # Safety
    ///
    /// `camera_region_anchor` must implement OS_ar_camera_region_anchor.
    #[doc(alias = "ar_camera_region_anchor_get_pixel_buffer")]
    #[cfg(all(
        feature = "anchor",
        feature = "objc2",
        feature = "objc2-core-foundation",
        feature = "objc2-core-video"
    ))]
    #[inline]
    pub unsafe fn pixel_buffer(
        camera_region_anchor: &ar_camera_region_anchor_t,
    ) -> Option<CFRetained<CVPixelBuffer>> {
        extern "C-unwind" {
            fn ar_camera_region_anchor_get_pixel_buffer(
                camera_region_anchor: &ar_camera_region_anchor_t,
            ) -> Option<NonNull<CVPixelBuffer>>;
        }
        let ret = unsafe { ar_camera_region_anchor_get_pixel_buffer(camera_region_anchor) };
        ret.map(|ret| unsafe { CFRetained::retain(ret) })
    }

    /// Get the identifier of an anchor.
    ///
    ///
    /// Parameter `camera_region_anchor`: The anchor.
    ///
    /// Parameter `out_identifier`: A pointer to a UUID to fill out with the anchor identifier. Must be non-null.
    ///
    /// # Safety
    ///
    /// `camera_region_anchor` must implement OS_ar_camera_region_anchor.
    #[doc(alias = "ar_camera_region_anchor_get_identifier")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn identifier(
        camera_region_anchor: &ar_camera_region_anchor_t,
        out_identifier: &mut uuid_t,
    ) {
        extern "C-unwind" {
            fn ar_camera_region_anchor_get_identifier(
                camera_region_anchor: &ar_camera_region_anchor_t,
                out_identifier: &mut uuid_t,
            );
        }
        unsafe { ar_camera_region_anchor_get_identifier(camera_region_anchor, out_identifier) }
    }

    /// Get the timestamp corresponding to an anchor.
    ///
    ///
    /// Parameter `camera_region_anchor`: The anchor.
    ///
    ///
    /// Returns: The timestamp associated with the anchor.
    ///
    /// # Safety
    ///
    /// `camera_region_anchor` must implement OS_ar_camera_region_anchor.
    #[doc(alias = "ar_camera_region_anchor_get_timestamp")]
    #[cfg(all(
        feature = "anchor",
        feature = "objc2",
        feature = "objc2-core-foundation"
    ))]
    #[inline]
    pub unsafe fn timestamp(camera_region_anchor: &ar_camera_region_anchor_t) -> CFTimeInterval {
        extern "C-unwind" {
            fn ar_camera_region_anchor_get_timestamp(
                camera_region_anchor: &ar_camera_region_anchor_t,
            ) -> CFTimeInterval;
        }
        unsafe { ar_camera_region_anchor_get_timestamp(camera_region_anchor) }
    }
}

impl ar_camera_region_anchors_t {
    /// Get the count of camera region anchors in a collection.
    ///
    ///
    /// Parameter `camera_region_anchors`: The collection of camera region anchors.
    ///
    ///
    /// Returns: The number of camera region anchors in the collection.
    ///
    /// # Safety
    ///
    /// `camera_region_anchors` must implement OS_ar_camera_region_anchors.
    #[doc(alias = "ar_camera_region_anchors_get_count")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn count(camera_region_anchors: &ar_camera_region_anchors_t) -> usize {
        extern "C-unwind" {
            fn ar_camera_region_anchors_get_count(
                camera_region_anchors: &ar_camera_region_anchors_t,
            ) -> usize;
        }
        unsafe { ar_camera_region_anchors_get_count(camera_region_anchors) }
    }
}

/// Handler for enumerating a collection of camera region anchors.
///
///
/// Parameter `camera_region_anchor`: The camera region anchor.
///
///
/// Returns: `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_camera_region_anchors_enumerator_t?language=objc)
#[cfg(all(feature = "anchor", feature = "block2", feature = "objc2"))]
pub type ar_camera_region_anchors_enumerator_t =
    block2::Block<'static, fn(NonNull<ar_camera_region_anchor_t>) -> bool>;

impl ar_camera_region_anchors_t {
    /// Enumerate a collection of camera region anchors.
    ///
    ///
    /// Parameter `camera_region_anchors`: The collection of camera region anchors.
    ///
    /// Parameter `camera_region_anchors_enumerator`: The enumerator handler.
    ///
    /// # Safety
    ///
    /// `camera_region_anchors` must implement OS_ar_camera_region_anchors.
    #[doc(alias = "ar_camera_region_anchors_enumerate_anchors")]
    #[cfg(all(feature = "anchor", feature = "block2", feature = "objc2"))]
    #[inline]
    pub unsafe fn enumerate_anchors(
        camera_region_anchors: &ar_camera_region_anchors_t,
        camera_region_anchors_enumerator: &ar_camera_region_anchors_enumerator_t,
    ) {
        extern "C-unwind" {
            fn ar_camera_region_anchors_enumerate_anchors(
                camera_region_anchors: &ar_camera_region_anchors_t,
                camera_region_anchors_enumerator: &ar_camera_region_anchors_enumerator_t,
            );
        }
        unsafe {
            ar_camera_region_anchors_enumerate_anchors(
                camera_region_anchors,
                camera_region_anchors_enumerator,
            )
        }
    }
}

/// Function for enumerating a collection of camera region anchors.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `camera_region_anchor`: The camera region anchor.
///
///
/// Returns: `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_camera_region_anchors_enumerator_function_t?language=objc)
#[cfg(all(feature = "anchor", feature = "objc2"))]
pub type ar_camera_region_anchors_enumerator_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &ar_camera_region_anchor_t) -> bool;

impl ar_camera_region_anchors_t {
    /// Enumerate a collection of camera region anchors using a function.
    ///
    ///
    /// Parameter `camera_region_anchors`: The collection of camera region anchors.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `camera_region_anchors_enumerator_function`: The enumerator function.
    ///
    /// # Safety
    ///
    /// - `camera_region_anchors` must implement OS_ar_camera_region_anchors.
    /// - `context` must be a valid pointer or null.
    /// - `camera_region_anchors_enumerator_function` must be implemented correctly.
    #[doc(alias = "ar_camera_region_anchors_enumerate_anchors_f")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn enumerate_anchors_f(
        camera_region_anchors: &ar_camera_region_anchors_t,
        context: *mut c_void,
        camera_region_anchors_enumerator_function: ar_camera_region_anchors_enumerator_function_t,
    ) {
        extern "C-unwind" {
            fn ar_camera_region_anchors_enumerate_anchors_f(
                camera_region_anchors: &ar_camera_region_anchors_t,
                context: *mut c_void,
                camera_region_anchors_enumerator_function: ar_camera_region_anchors_enumerator_function_t,
            );
        }
        unsafe {
            ar_camera_region_anchors_enumerate_anchors_f(
                camera_region_anchors,
                context,
                camera_region_anchors_enumerator_function,
            )
        }
    }
}

impl ar_camera_region_configuration_t {
    /// Create a camera region configuration.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_camera_region_configuration_t`.
    #[doc(alias = "ar_camera_region_configuration_create")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn new() -> Retained<ar_camera_region_configuration_t> {
        extern "C-unwind" {
            fn ar_camera_region_configuration_create() -> *mut ar_camera_region_configuration_t;
        }
        let ret = unsafe { ar_camera_region_configuration_create() };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }
}

impl ar_camera_region_provider_t {
    /// Create a camera region provider.
    ///
    ///
    /// Parameter `camera_region_configuration`: Camera Region configuration.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_camera_region_provider_t`.
    ///
    /// # Safety
    ///
    /// `camera_region_configuration` must implement OS_ar_camera_region_configuration.
    #[doc(alias = "ar_camera_region_provider_create")]
    #[cfg(all(feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn new(
        camera_region_configuration: &ar_camera_region_configuration_t,
    ) -> Retained<ar_camera_region_provider_t> {
        extern "C-unwind" {
            fn ar_camera_region_provider_create(
                camera_region_configuration: &ar_camera_region_configuration_t,
            ) -> *mut ar_camera_region_provider_t;
        }
        let ret = unsafe { ar_camera_region_provider_create(camera_region_configuration) };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Determine whether this device supports the camera region provider.
    ///
    ///
    /// Returns: `true` if the camera region provider is supported on this device, `false` otherwise.
    #[doc(alias = "ar_camera_region_provider_is_supported")]
    #[inline]
    pub unsafe fn is_supported() -> bool {
        extern "C-unwind" {
            fn ar_camera_region_provider_is_supported() -> bool;
        }
        unsafe { ar_camera_region_provider_is_supported() }
    }

    /// Get the authorization type required by the camera region provider.
    ///
    ///
    /// Returns: The required authorization type.
    #[doc(alias = "ar_camera_region_provider_get_required_authorization_type")]
    #[cfg(feature = "authorization")]
    #[inline]
    pub unsafe fn required_authorization_type() -> ar_authorization_type_t {
        extern "C-unwind" {
            fn ar_camera_region_provider_get_required_authorization_type() -> ar_authorization_type_t;
        }
        unsafe { ar_camera_region_provider_get_required_authorization_type() }
    }
}

/// Handler called when there are updates to a specific camera region anchor.
///
///
/// Parameter `added_anchor`: The anchor that was added.
///
/// Parameter `updated_anchor`: The anchor that was updated.
///
/// Parameter `removed_anchor`: The anchor that was removed.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_camera_region_anchor_update_handler_t?language=objc)
#[cfg(all(feature = "anchor", feature = "block2", feature = "objc2"))]
pub type ar_camera_region_anchor_update_handler_t = block2::Block<
    'static,
    fn(
        *mut ar_camera_region_anchor_t,
        *mut ar_camera_region_anchor_t,
        *mut ar_camera_region_anchor_t,
    ),
>;

impl ar_camera_region_provider_t {
    /// Set the handler for receiving camera region updates for a specific anchor identifier.
    ///
    ///
    /// Parameter `camera_region_provider`: The camera region provider.
    ///
    /// Parameter `camera_region_anchor_identifier`: The camera region anchor identifier to get updates for.
    ///
    /// Parameter `camera_region_anchor_updates_queue`: The queue on which the handler will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `camera_region_anchor_update_handler`: The handler to be called when new camera region anchor data arrives.
    ///
    /// # Safety
    ///
    /// - `camera_region_provider` must implement OS_ar_camera_region_provider.
    /// - `camera_region_anchor_updates_queue` possibly has additional threading requirements.
    #[doc(alias = "ar_camera_region_provider_set_update_handler_for_anchor_with_identifier")]
    #[cfg(all(
        feature = "anchor",
        feature = "block2",
        feature = "data_provider",
        feature = "dispatch2",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn set_update_handler_for_anchor_with_identifier(
        camera_region_provider: &ar_camera_region_provider_t,
        camera_region_anchor_identifier: &mut uuid_t,
        camera_region_anchor_updates_queue: Option<&DispatchQueue>,
        camera_region_anchor_update_handler: Option<&ar_camera_region_anchor_update_handler_t>,
    ) {
        extern "C-unwind" {
            fn ar_camera_region_provider_set_update_handler_for_anchor_with_identifier(
                camera_region_provider: &ar_camera_region_provider_t,
                camera_region_anchor_identifier: &mut uuid_t,
                camera_region_anchor_updates_queue: Option<&DispatchQueue>,
                camera_region_anchor_update_handler: Option<
                    &ar_camera_region_anchor_update_handler_t,
                >,
            );
        }
        unsafe {
            ar_camera_region_provider_set_update_handler_for_anchor_with_identifier(
                camera_region_provider,
                camera_region_anchor_identifier,
                camera_region_anchor_updates_queue,
                camera_region_anchor_update_handler,
            )
        }
    }
}

/// Function called when there are updates to a specific camera region anchor.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `added_anchor`: The anchor that was added.
///
/// Parameter `updated_anchor`: The anchor that was updated.
///
/// Parameter `removed_anchor`: The anchor that was removed.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_camera_region_anchor_update_handler_function_t?language=objc)
#[cfg(all(feature = "anchor", feature = "objc2"))]
pub type ar_camera_region_anchor_update_handler_function_t = unsafe extern "C-unwind" fn(
    *mut c_void,
    &ar_camera_region_anchor_t,
    &ar_camera_region_anchor_t,
    &ar_camera_region_anchor_t,
);

impl ar_camera_region_provider_t {
    /// Set the function for receiving camera region updates for a specific anchor identifier.
    ///
    ///
    /// Parameter `camera_region_provider`: The camera region provider.
    ///
    /// Parameter `camera_region_anchor_identifier`: The camera region anchor identifier to get updates for.
    ///
    /// Parameter `camera_region_anchor_updates_queue`: The queue on which the function will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `camera_region_anchor_update_handler_function`: The function to be called when new camera region anchor data arrives.
    ///
    ///
    /// Note: Setting this function will override the handler set using `ar_camera_region_provider_set_update_handler_for_anchor_with_identifier`.
    ///
    /// # Safety
    ///
    /// - `camera_region_provider` must implement OS_ar_camera_region_provider.
    /// - `camera_region_anchor_updates_queue` possibly has additional threading requirements.
    /// - `context` must be a valid pointer or null.
    /// - `camera_region_anchor_update_handler_function` must be implemented correctly.
    #[doc(alias = "ar_camera_region_provider_set_update_handler_for_anchor_with_identifier_f")]
    #[cfg(all(
        feature = "anchor",
        feature = "data_provider",
        feature = "dispatch2",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn set_update_handler_for_anchor_with_identifier_f(
        camera_region_provider: &ar_camera_region_provider_t,
        camera_region_anchor_identifier: &mut uuid_t,
        camera_region_anchor_updates_queue: Option<&DispatchQueue>,
        context: *mut c_void,
        camera_region_anchor_update_handler_function: Option<
            ar_camera_region_anchor_update_handler_function_t,
        >,
    ) {
        extern "C-unwind" {
            fn ar_camera_region_provider_set_update_handler_for_anchor_with_identifier_f(
                camera_region_provider: &ar_camera_region_provider_t,
                camera_region_anchor_identifier: &mut uuid_t,
                camera_region_anchor_updates_queue: Option<&DispatchQueue>,
                context: *mut c_void,
                camera_region_anchor_update_handler_function: Option<
                    ar_camera_region_anchor_update_handler_function_t,
                >,
            );
        }
        unsafe {
            ar_camera_region_provider_set_update_handler_for_anchor_with_identifier_f(
                camera_region_provider,
                camera_region_anchor_identifier,
                camera_region_anchor_updates_queue,
                context,
                camera_region_anchor_update_handler_function,
            )
        }
    }
}

/// Handler called when a request to add a camera region anchor has completed (successfully or not).
///
///
/// Parameter `camera_region_anchor`: The camera region anchor to be added.
///
/// Parameter `successful`: `true` if the camera region anchor was successfully added, `false` otherwise.
///
/// Parameter `error`: The error that occurred, if any. The returned error supports ARC. In non-ARC files, use `ar_release()` to release the error.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_camera_region_add_anchor_completion_handler_t?language=objc)
#[cfg(all(
    feature = "anchor",
    feature = "block2",
    feature = "error",
    feature = "objc2"
))]
pub type ar_camera_region_add_anchor_completion_handler_t =
    block2::Block<'static, fn(NonNull<ar_camera_region_anchor_t>, bool, *mut ar_error_t)>;

impl ar_camera_region_provider_t {
    /// Add a camera region anchor to a camera region provider.
    ///
    ///
    /// Parameter `camera_region_provider`: The camera region provider.
    ///
    /// Parameter `camera_region_anchor`: The camera region anchor to add.
    ///
    /// Parameter `add_anchor_completion_handler`: The handler to be called after the request to add the camera region anchor completes.
    ///
    /// # Safety
    ///
    /// - `camera_region_provider` must implement OS_ar_camera_region_provider.
    /// - `camera_region_anchor` must implement OS_ar_camera_region_anchor.
    #[doc(alias = "ar_camera_region_provider_add_camera_region_anchor")]
    #[cfg(all(
        feature = "anchor",
        feature = "block2",
        feature = "data_provider",
        feature = "error",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn add_camera_region_anchor(
        camera_region_provider: &ar_camera_region_provider_t,
        camera_region_anchor: &ar_camera_region_anchor_t,
        add_anchor_completion_handler: &ar_camera_region_add_anchor_completion_handler_t,
    ) {
        extern "C-unwind" {
            fn ar_camera_region_provider_add_camera_region_anchor(
                camera_region_provider: &ar_camera_region_provider_t,
                camera_region_anchor: &ar_camera_region_anchor_t,
                add_anchor_completion_handler: &ar_camera_region_add_anchor_completion_handler_t,
            );
        }
        unsafe {
            ar_camera_region_provider_add_camera_region_anchor(
                camera_region_provider,
                camera_region_anchor,
                add_anchor_completion_handler,
            )
        }
    }
}

/// Function called when a request to add a camera region anchor has completed (successfully or not).
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `camera_region_anchor`: The camera region anchor to be added.
///
/// Parameter `successful`: `true` if the camera region anchor was successfully added, `false` otherwise.
///
/// Parameter `error`: The error that occurred, if any. The returned error supports ARC. In non-ARC files, use `ar_release()` to release the error.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_camera_region_add_anchor_completion_handler_function_t?language=objc)
#[cfg(all(feature = "anchor", feature = "error", feature = "objc2"))]
pub type ar_camera_region_add_anchor_completion_handler_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &ar_camera_region_anchor_t, bool, Option<&ar_error_t>);

impl ar_camera_region_provider_t {
    /// Add a camera region anchor to an camera region provider using a function.
    ///
    ///
    /// Parameter `camera_region_provider`: The camera region provider.
    ///
    /// Parameter `camera_region_anchor`: The camera region anchor to add.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `add_anchor_completion_handler_function`: The function to be called after the request to add the camera region anchor completes.
    ///
    /// # Safety
    ///
    /// - `camera_region_provider` must implement OS_ar_camera_region_provider.
    /// - `camera_region_anchor` must implement OS_ar_camera_region_anchor.
    /// - `context` must be a valid pointer or null.
    /// - `add_anchor_completion_handler_function` must be implemented correctly.
    #[doc(alias = "ar_camera_region_provider_add_camera_region_anchor_f")]
    #[cfg(all(
        feature = "anchor",
        feature = "data_provider",
        feature = "error",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn add_camera_region_anchor_f(
        camera_region_provider: &ar_camera_region_provider_t,
        camera_region_anchor: &ar_camera_region_anchor_t,
        context: *mut c_void,
        add_anchor_completion_handler_function: ar_camera_region_add_anchor_completion_handler_function_t,
    ) {
        extern "C-unwind" {
            fn ar_camera_region_provider_add_camera_region_anchor_f(
                camera_region_provider: &ar_camera_region_provider_t,
                camera_region_anchor: &ar_camera_region_anchor_t,
                context: *mut c_void,
                add_anchor_completion_handler_function: ar_camera_region_add_anchor_completion_handler_function_t,
            );
        }
        unsafe {
            ar_camera_region_provider_add_camera_region_anchor_f(
                camera_region_provider,
                camera_region_anchor,
                context,
                add_anchor_completion_handler_function,
            )
        }
    }
}

/// Handler called when a request to remove a camera region anchor has completed (successfully or not).
///
///
/// Parameter `camera_region_anchor`: The camera region anchor to be removed.
///
/// Parameter `successful`: `true` if the camera region anchor was successfully removed, `false` otherwise.
///
/// Parameter `error`: The error that occurred, if any. The returned error supports ARC. In non-ARC files, use `ar_release()` to release the error.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_camera_region_remove_anchor_completion_handler_t?language=objc)
#[cfg(all(
    feature = "anchor",
    feature = "block2",
    feature = "error",
    feature = "objc2"
))]
pub type ar_camera_region_remove_anchor_completion_handler_t =
    block2::Block<'static, fn(NonNull<ar_camera_region_anchor_t>, bool, *mut ar_error_t)>;

impl ar_camera_region_provider_t {
    /// Remove a camera region anchor from a camera region provider.
    ///
    ///
    /// Parameter `camera_region_provider`: The camera region provider.
    ///
    /// Parameter `camera_region_anchor`: The camera region anchor.
    ///
    /// Parameter `remove_anchor_completion_handler`: The handler to be called after the request to remove the camera region anchor completes.
    ///
    /// # Safety
    ///
    /// - `camera_region_provider` must implement OS_ar_camera_region_provider.
    /// - `camera_region_anchor` must implement OS_ar_camera_region_anchor.
    #[doc(alias = "ar_camera_region_provider_remove_camera_region_anchor")]
    #[cfg(all(
        feature = "anchor",
        feature = "block2",
        feature = "data_provider",
        feature = "error",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn remove_camera_region_anchor(
        camera_region_provider: &ar_camera_region_provider_t,
        camera_region_anchor: &ar_camera_region_anchor_t,
        remove_anchor_completion_handler: &ar_camera_region_remove_anchor_completion_handler_t,
    ) {
        extern "C-unwind" {
            fn ar_camera_region_provider_remove_camera_region_anchor(
                camera_region_provider: &ar_camera_region_provider_t,
                camera_region_anchor: &ar_camera_region_anchor_t,
                remove_anchor_completion_handler: &ar_camera_region_remove_anchor_completion_handler_t,
            );
        }
        unsafe {
            ar_camera_region_provider_remove_camera_region_anchor(
                camera_region_provider,
                camera_region_anchor,
                remove_anchor_completion_handler,
            )
        }
    }
}

/// Handler called when a request to remove a camera region anchor by its identifier has completed (successfully or not).
///
///
/// Parameter `camera_region_anchor_identifier`: The identifier of the camera region anchor requested to be removed.
///
/// Parameter `successful`: `true` if the camera region anchor was successfully removed, `false` otherwise.
///
/// Parameter `error`: The error that occurred, if any. The returned error supports ARC. In non-ARC files, use `ar_release()` to release the error.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_camera_region_remove_anchor_with_identifier_completion_handler_t?language=objc)
#[cfg(all(feature = "block2", feature = "error", feature = "objc2"))]
pub type ar_camera_region_remove_anchor_with_identifier_completion_handler_t =
    block2::Block<'static, fn(NonNull<uuid_t>, bool, *mut ar_error_t)>;

impl ar_camera_region_provider_t {
    /// Remove a camera region anchor from a camera region provider by its identifier.
    ///
    ///
    /// Parameter `camera_region_provider`: The camera region provider.
    ///
    /// Parameter `camera_region_anchor_identifier`: The identifier of the camera region anchor to remove.
    ///
    /// Parameter `remove_anchor_with_identifier_completion_handler`: The handler to be called after the request to remove the camera region anchor by its
    /// identifier completes.
    ///
    /// # Safety
    ///
    /// `camera_region_provider` must implement OS_ar_camera_region_provider.
    #[doc(alias = "ar_camera_region_provider_remove_camera_region_anchor_with_identifier")]
    #[cfg(all(
        feature = "block2",
        feature = "data_provider",
        feature = "error",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn remove_camera_region_anchor_with_identifier(
        camera_region_provider: &ar_camera_region_provider_t,
        camera_region_anchor_identifier: &mut uuid_t,
        remove_anchor_with_identifier_completion_handler: &ar_camera_region_remove_anchor_with_identifier_completion_handler_t,
    ) {
        extern "C-unwind" {
            fn ar_camera_region_provider_remove_camera_region_anchor_with_identifier(
                camera_region_provider: &ar_camera_region_provider_t,
                camera_region_anchor_identifier: &mut uuid_t,
                remove_anchor_with_identifier_completion_handler: &ar_camera_region_remove_anchor_with_identifier_completion_handler_t,
            );
        }
        unsafe {
            ar_camera_region_provider_remove_camera_region_anchor_with_identifier(
                camera_region_provider,
                camera_region_anchor_identifier,
                remove_anchor_with_identifier_completion_handler,
            )
        }
    }
}

/// Function called when a request to remove a camera region anchor has completed (successfully or not).
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `camera_region_anchor`: The camera region anchor to be removed.
///
/// Parameter `successful`: `true` if the camera region anchor was successfully removed, `false` otherwise.
///
/// Parameter `error`: The error that occurred, if any. The returned error supports ARC. In non-ARC files, use `ar_release()` to release the error.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_camera_region_remove_anchor_completion_handler_function_t?language=objc)
#[cfg(all(feature = "anchor", feature = "error", feature = "objc2"))]
pub type ar_camera_region_remove_anchor_completion_handler_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &ar_camera_region_anchor_t, bool, Option<&ar_error_t>);

impl ar_camera_region_provider_t {
    /// Remove a camera region anchor from a camera region provider using a function.
    ///
    ///
    /// Parameter `camera_region_provider`: The camera region provider.
    ///
    /// Parameter `camera_region_anchor`: The camera region anchor to remove.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `remove_anchor_completion_handler_function`: The function to be called after the request to remove the camera region anchor completes.
    ///
    /// # Safety
    ///
    /// - `camera_region_provider` must implement OS_ar_camera_region_provider.
    /// - `camera_region_anchor` must implement OS_ar_camera_region_anchor.
    /// - `context` must be a valid pointer or null.
    /// - `remove_anchor_completion_handler_function` must be implemented correctly.
    #[doc(alias = "ar_camera_region_provider_remove_camera_region_anchor_f")]
    #[cfg(all(
        feature = "anchor",
        feature = "data_provider",
        feature = "error",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn remove_camera_region_anchor_f(
        camera_region_provider: &ar_camera_region_provider_t,
        camera_region_anchor: &ar_camera_region_anchor_t,
        context: *mut c_void,
        remove_anchor_completion_handler_function: ar_camera_region_remove_anchor_completion_handler_function_t,
    ) {
        extern "C-unwind" {
            fn ar_camera_region_provider_remove_camera_region_anchor_f(
                camera_region_provider: &ar_camera_region_provider_t,
                camera_region_anchor: &ar_camera_region_anchor_t,
                context: *mut c_void,
                remove_anchor_completion_handler_function: ar_camera_region_remove_anchor_completion_handler_function_t,
            );
        }
        unsafe {
            ar_camera_region_provider_remove_camera_region_anchor_f(
                camera_region_provider,
                camera_region_anchor,
                context,
                remove_anchor_completion_handler_function,
            )
        }
    }
}

/// Function called when a request to remove a camera region anchor by its identifier has completed (successfully or not).
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `camera_region_anchor_identifier`: The identifier of the camera region anchor requested to be removed.
///
/// Parameter `successful`: `true` if the camera region anchor was successfully removed, `false` otherwise.
///
/// Parameter `error`: The error that occurred, if any. The returned error supports ARC. In non-ARC files, use `ar_release()` to release the error.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_camera_region_remove_anchor_with_identifier_completion_handler_function_t?language=objc)
#[cfg(all(feature = "error", feature = "objc2"))]
pub type ar_camera_region_remove_anchor_with_identifier_completion_handler_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &mut uuid_t, bool, Option<&ar_error_t>);

impl ar_camera_region_provider_t {
    /// Remove a camera region anchor from a camera region provider by its identifier using a function.
    ///
    ///
    /// Parameter `camera_region_provider`: The camera region provider.
    ///
    /// Parameter `camera_region_anchor_identifier`: The identifier of the camera region anchor to remove.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `remove_anchor_with_identifier_completion_handler_function`: The function to be called after the request to remove the camera region anchor by
    /// its identifier completes.
    ///
    /// # Safety
    ///
    /// - `camera_region_provider` must implement OS_ar_camera_region_provider.
    /// - `context` must be a valid pointer or null.
    /// - `remove_anchor_with_identifier_completion_handler_function` must be implemented correctly.
    #[doc(alias = "ar_camera_region_provider_remove_camera_region_anchor_with_identifier_f")]
    #[cfg(all(feature = "data_provider", feature = "error", feature = "objc2"))]
    #[inline]
    pub unsafe fn remove_camera_region_anchor_with_identifier_f(
        camera_region_provider: &ar_camera_region_provider_t,
        camera_region_anchor_identifier: &mut uuid_t,
        context: *mut c_void,
        remove_anchor_with_identifier_completion_handler_function: ar_camera_region_remove_anchor_with_identifier_completion_handler_function_t,
    ) {
        extern "C-unwind" {
            fn ar_camera_region_provider_remove_camera_region_anchor_with_identifier_f(
                camera_region_provider: &ar_camera_region_provider_t,
                camera_region_anchor_identifier: &mut uuid_t,
                context: *mut c_void,
                remove_anchor_with_identifier_completion_handler_function: ar_camera_region_remove_anchor_with_identifier_completion_handler_function_t,
            );
        }
        unsafe {
            ar_camera_region_provider_remove_camera_region_anchor_with_identifier_f(
                camera_region_provider,
                camera_region_anchor_identifier,
                context,
                remove_anchor_with_identifier_completion_handler_function,
            )
        }
    }
}
