//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::cell::UnsafeCell;
use core::ffi::*;
use core::marker::{PhantomData, PhantomPinned};
use core::ptr::NonNull;
#[cfg(feature = "dispatch2")]
use dispatch2::*;
#[cfg(feature = "objc2")]
use objc2::__framework_prelude::*;

use crate::*;

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_data_provider_t?language=objc)
#[repr(C)]
pub struct ar_data_provider_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_data_provider_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_data_providers_t?language=objc)
#[repr(C)]
pub struct ar_data_providers_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_data_providers_t {}
);

/// State of a data provider.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_data_provider_state_t?language=objc)
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct ar_data_provider_state_t(pub isize);
impl ar_data_provider_state_t {
    /// State of a data provider.
    #[doc(alias = "ar_data_provider_state_initialized")]
    pub const initialized: Self = Self(0);
    /// State of a data provider.
    #[doc(alias = "ar_data_provider_state_running")]
    pub const running: Self = Self(1);
    /// State of a data provider.
    #[doc(alias = "ar_data_provider_state_paused")]
    pub const paused: Self = Self(2);
    /// State of a data provider.
    #[doc(alias = "ar_data_provider_state_stopped")]
    pub const stopped: Self = Self(3);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ar_data_provider_state_t {
    const ENCODING: Encoding = isize::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ar_data_provider_state_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

impl ar_data_provider_t {
    /// Get the state of a data provider.
    ///
    ///
    /// Parameter `data_provider`: The data provider.
    ///
    ///
    /// Returns: The state of the data provider.
    ///
    /// # Safety
    ///
    /// `data_provider` must implement OS_ar_data_provider.
    #[doc(alias = "ar_data_provider_get_state")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn state(data_provider: &ar_data_provider_t) -> ar_data_provider_state_t {
        extern "C-unwind" {
            fn ar_data_provider_get_state(
                data_provider: &ar_data_provider_t,
            ) -> ar_data_provider_state_t;
        }
        unsafe { ar_data_provider_get_state(data_provider) }
    }

    /// Get the authorization type required by a data provider.
    ///
    ///
    /// Parameter `data_provider`: The data provider.
    ///
    ///
    /// Returns: The authorization type required by the data provider.
    ///
    /// # Safety
    ///
    /// `data_provider` must implement OS_ar_data_provider.
    #[doc(alias = "ar_data_provider_get_required_authorization_type")]
    #[cfg(all(feature = "authorization", feature = "objc2"))]
    #[inline]
    pub unsafe fn required_authorization_type(
        data_provider: &ar_data_provider_t,
    ) -> ar_authorization_type_t {
        extern "C-unwind" {
            fn ar_data_provider_get_required_authorization_type(
                data_provider: &ar_data_provider_t,
            ) -> ar_authorization_type_t;
        }
        unsafe { ar_data_provider_get_required_authorization_type(data_provider) }
    }
}

impl ar_data_providers_t {
    /// Create an empty collection of data providers.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_data_providers_t`.
    #[doc(alias = "ar_data_providers_create")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn new() -> Retained<ar_data_providers_t> {
        extern "C-unwind" {
            fn ar_data_providers_create() -> *mut ar_data_providers_t;
        }
        let ret = unsafe { ar_data_providers_create() };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Add a data provider to a collection.
    ///
    ///
    /// Parameter `data_providers`: The collection to expand.
    ///
    /// Parameter `data_provider_to_add`: The data provider to add.
    ///
    /// # Safety
    ///
    /// - `data_providers` must implement OS_ar_data_providers.
    /// - `data_provider_to_add` must implement OS_ar_data_provider.
    #[doc(alias = "ar_data_providers_add_data_provider")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn add_data_provider(
        data_providers: &ar_data_providers_t,
        data_provider_to_add: &ar_data_provider_t,
    ) {
        extern "C-unwind" {
            fn ar_data_providers_add_data_provider(
                data_providers: &ar_data_providers_t,
                data_provider_to_add: &ar_data_provider_t,
            );
        }
        unsafe { ar_data_providers_add_data_provider(data_providers, data_provider_to_add) }
    }

    /// Add data providers to a collection.
    ///
    ///
    /// Parameter `data_providers`: The collection to expand.
    ///
    /// Parameter `data_providers_to_add`: The collection of data providers to add.
    ///
    /// # Safety
    ///
    /// - `data_providers` must implement OS_ar_data_providers.
    /// - `data_providers_to_add` must implement OS_ar_data_providers.
    #[doc(alias = "ar_data_providers_add_data_providers")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn add_data_providers(
        data_providers: &ar_data_providers_t,
        data_providers_to_add: &ar_data_providers_t,
    ) {
        extern "C-unwind" {
            fn ar_data_providers_add_data_providers(
                data_providers: &ar_data_providers_t,
                data_providers_to_add: &ar_data_providers_t,
            );
        }
        unsafe { ar_data_providers_add_data_providers(data_providers, data_providers_to_add) }
    }

    /// Remove a data provider from a collection.
    ///
    ///
    /// Parameter `data_providers`: The collection from which to remove.
    ///
    /// Parameter `data_provider_to_remove`: The data provider to remove.
    ///
    /// # Safety
    ///
    /// - `data_providers` must implement OS_ar_data_providers.
    /// - `data_provider_to_remove` must implement OS_ar_data_provider.
    #[doc(alias = "ar_data_providers_remove_data_provider")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn remove_data_provider(
        data_providers: &ar_data_providers_t,
        data_provider_to_remove: &ar_data_provider_t,
    ) {
        extern "C-unwind" {
            fn ar_data_providers_remove_data_provider(
                data_providers: &ar_data_providers_t,
                data_provider_to_remove: &ar_data_provider_t,
            );
        }
        unsafe { ar_data_providers_remove_data_provider(data_providers, data_provider_to_remove) }
    }

    /// Remove data providers from a collection.
    ///
    ///
    /// Parameter `data_providers`: The collection from which to remove.
    ///
    /// Parameter `data_providers_to_remove`: The collection of data providers to remove.
    ///
    /// # Safety
    ///
    /// - `data_providers` must implement OS_ar_data_providers.
    /// - `data_providers_to_remove` must implement OS_ar_data_providers.
    #[doc(alias = "ar_data_providers_remove_data_providers")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn remove_data_providers(
        data_providers: &ar_data_providers_t,
        data_providers_to_remove: &ar_data_providers_t,
    ) {
        extern "C-unwind" {
            fn ar_data_providers_remove_data_providers(
                data_providers: &ar_data_providers_t,
                data_providers_to_remove: &ar_data_providers_t,
            );
        }
        unsafe { ar_data_providers_remove_data_providers(data_providers, data_providers_to_remove) }
    }

    /// Get the count of data providers in a collection.
    ///
    ///
    /// Parameter `data_providers`: The collection of data providers.
    ///
    ///
    /// Returns: The number of data providers in the collection.
    ///
    /// # Safety
    ///
    /// `data_providers` must implement OS_ar_data_providers.
    #[doc(alias = "ar_data_providers_get_count")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn count(data_providers: &ar_data_providers_t) -> usize {
        extern "C-unwind" {
            fn ar_data_providers_get_count(data_providers: &ar_data_providers_t) -> usize;
        }
        unsafe { ar_data_providers_get_count(data_providers) }
    }
}

/// Handler for enumerating a collection of data providers.
///
///
/// Parameter `data_provider`: The data provider.
///
///
/// Returns: `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_data_providers_enumerator_t?language=objc)
#[cfg(all(feature = "block2", feature = "objc2"))]
pub type ar_data_providers_enumerator_t =
    block2::Block<'static, fn(NonNull<ar_data_provider_t>) -> bool>;

impl ar_data_providers_t {
    /// Enumerate a collection of data providers.
    ///
    ///
    /// Parameter `data_providers`: The collection of data providers.
    ///
    /// Parameter `data_providers_enumerator`: The enumerator handler.
    ///
    /// # Safety
    ///
    /// `data_providers` must implement OS_ar_data_providers.
    #[doc(alias = "ar_data_providers_enumerate_data_providers")]
    #[cfg(all(feature = "block2", feature = "objc2"))]
    #[inline]
    pub unsafe fn enumerate_data_providers(
        data_providers: &ar_data_providers_t,
        data_providers_enumerator: &ar_data_providers_enumerator_t,
    ) {
        extern "C-unwind" {
            fn ar_data_providers_enumerate_data_providers(
                data_providers: &ar_data_providers_t,
                data_providers_enumerator: &ar_data_providers_enumerator_t,
            );
        }
        unsafe {
            ar_data_providers_enumerate_data_providers(data_providers, data_providers_enumerator)
        }
    }
}

/// Function for enumerating a collection of data providers.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `data_provider`: The data provider.
///
///
/// Returns: `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_data_providers_enumerator_function_t?language=objc)
#[cfg(feature = "objc2")]
pub type ar_data_providers_enumerator_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &ar_data_provider_t) -> bool;

impl ar_data_providers_t {
    /// Enumerate a collection of data providers using a function.
    ///
    ///
    /// Parameter `data_providers`: The collection of data providers.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `data_providers_enumerator_function`: The enumerator function.
    ///
    /// # Safety
    ///
    /// - `data_providers` must implement OS_ar_data_providers.
    /// - `context` must be a valid pointer or null.
    /// - `data_providers_enumerator_function` must be implemented correctly.
    #[doc(alias = "ar_data_providers_enumerate_data_providers_f")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn enumerate_data_providers_f(
        data_providers: &ar_data_providers_t,
        context: *mut c_void,
        data_providers_enumerator_function: ar_data_providers_enumerator_function_t,
    ) {
        extern "C-unwind" {
            fn ar_data_providers_enumerate_data_providers_f(
                data_providers: &ar_data_providers_t,
                context: *mut c_void,
                data_providers_enumerator_function: ar_data_providers_enumerator_function_t,
            );
        }
        unsafe {
            ar_data_providers_enumerate_data_providers_f(
                data_providers,
                context,
                data_providers_enumerator_function,
            )
        }
    }
}
