//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::cell::UnsafeCell;
use core::ffi::*;
use core::marker::{PhantomData, PhantomPinned};
use core::ptr::NonNull;
#[cfg(feature = "dispatch2")]
use dispatch2::*;

use crate::*;

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_data_t?language=objc)
#[repr(C)]
pub struct ar_data_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_data_t {}
);

impl ar_data_t {
    /// Get a pointer to the data's bytes.
    ///
    ///
    /// Returns: A pointer to the data's bytes.
    ///
    /// # Safety
    ///
    /// `data` must implement OS_ar_data.
    #[doc(alias = "ar_data_get_bytes")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn bytes(data: &ar_data_t) -> NonNull<c_void> {
        extern "C-unwind" {
            fn ar_data_get_bytes(data: &ar_data_t) -> Option<NonNull<c_void>>;
        }
        let ret = unsafe { ar_data_get_bytes(data) };
        ret.expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Get the length of the data, in bytes.
    ///
    ///
    /// Returns: The length of the data, in bytes.
    ///
    /// # Safety
    ///
    /// `data` must implement OS_ar_data.
    #[doc(alias = "ar_data_get_length")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn length(data: &ar_data_t) -> usize {
        extern "C-unwind" {
            fn ar_data_get_length(data: &ar_data_t) -> usize;
        }
        unsafe { ar_data_get_length(data) }
    }
}
