//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::cell::UnsafeCell;
use core::ffi::*;
use core::marker::{PhantomData, PhantomPinned};
use core::ptr::NonNull;
#[cfg(feature = "dispatch2")]
use dispatch2::*;
#[cfg(feature = "objc2")]
use objc2::__framework_prelude::*;
#[cfg(feature = "objc2-core-foundation")]
use objc2_core_foundation::*;
#[cfg(feature = "objc2-metal")]
use objc2_metal::*;

use crate::*;

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_environment_probe_anchor_t?language=objc)
#[repr(C)]
pub struct ar_environment_probe_anchor_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_environment_probe_anchor_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_environment_probe_anchors_t?language=objc)
#[repr(C)]
pub struct ar_environment_probe_anchors_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_environment_probe_anchors_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_environment_light_estimation_configuration_t?language=objc)
#[repr(C)]
pub struct ar_environment_light_estimation_configuration_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_environment_light_estimation_configuration_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_environment_light_estimation_provider_t?language=objc)
#[repr(C)]
pub struct ar_environment_light_estimation_provider_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_environment_light_estimation_provider_t {}
);

impl ar_environment_probe_anchor_t {
    /// Returns a bool value that indicates whether the two environment probe anchors are equal.
    ///
    ///
    /// Parameter `environment_probe_anchor`: A environment probe anchor to be compared.
    ///
    /// Parameter `other_environment_probe_anchor`: The other environment probe anchor to be compared to.
    ///
    ///
    /// Returns: YES if the environment probe anchors are equal, otherwise NO.
    ///
    /// # Safety
    ///
    /// - `environment_probe_anchor` must implement OS_ar_environment_probe_anchor.
    /// - `other_environment_probe_anchor` must implement OS_ar_environment_probe_anchor.
    #[doc(alias = "ar_environment_probe_anchor_is_equal_to_environment_probe_anchor")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn is_equal_to_environment_probe_anchor(
        environment_probe_anchor: Option<&ar_environment_probe_anchor_t>,
        other_environment_probe_anchor: Option<&ar_environment_probe_anchor_t>,
    ) -> bool {
        extern "C-unwind" {
            fn ar_environment_probe_anchor_is_equal_to_environment_probe_anchor(
                environment_probe_anchor: Option<&ar_environment_probe_anchor_t>,
                other_environment_probe_anchor: Option<&ar_environment_probe_anchor_t>,
            ) -> bool;
        }
        unsafe {
            ar_environment_probe_anchor_is_equal_to_environment_probe_anchor(
                environment_probe_anchor,
                other_environment_probe_anchor,
            )
        }
    }

    /// Get the environment texture of an environment probe anchor.
    ///
    ///
    /// Parameter `environment_probe`: An environment probe anchor.
    ///
    ///
    /// The texture is provided as a cube using MTLTextureTypeCube,
    /// containing rgb floating point linear high-dynamic range values in P3 color space.
    ///
    /// Note: Textures could be nil if the person is not in a well-lit environment. The lifetime of this texture is tied to the lifetime of the
    /// `ar_environment_probe_anchor_t`.
    ///
    /// Returns: Returns a MTLTextureTypeCube.
    ///
    /// # Safety
    ///
    /// `environment_probe` must implement OS_ar_environment_probe_anchor.
    #[doc(alias = "ar_environment_probe_anchor_get_environment_texture")]
    #[cfg(all(feature = "anchor", feature = "objc2", feature = "objc2-metal"))]
    #[inline]
    pub unsafe fn environment_texture(
        environment_probe: &ar_environment_probe_anchor_t,
    ) -> Option<Retained<ProtocolObject<dyn MTLTexture>>> {
        extern "C-unwind" {
            fn ar_environment_probe_anchor_get_environment_texture(
                environment_probe: &ar_environment_probe_anchor_t,
            ) -> *mut ProtocolObject<dyn MTLTexture>;
        }
        let ret = unsafe { ar_environment_probe_anchor_get_environment_texture(environment_probe) };
        unsafe { Retained::retain_autoreleased(ret) }
    }

    /// Get the camera scale reference of an environment probe anchor.
    ///
    ///
    /// Parameter `environment_probe`: An environment probe anchor.
    ///
    ///
    /// Returns: Returns the camera scale reference of a pixel with rgb value [1,1,1] in the environment texture.
    ///
    ///
    /// The environment texture stores floating point linear high-dynamic range rgb values in P3 color space.
    /// In order to have a consistent brightness between texture updates, the cameraScaleReference allows you to translate the local brightness from the
    /// current environment texture to the absolute brightness range from the camera.
    ///
    /// # Safety
    ///
    /// `environment_probe` must implement OS_ar_environment_probe_anchor.
    #[doc(alias = "ar_environment_probe_anchor_get_camera_scale_reference")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn camera_scale_reference(
        environment_probe: &ar_environment_probe_anchor_t,
    ) -> c_float {
        extern "C-unwind" {
            fn ar_environment_probe_anchor_get_camera_scale_reference(
                environment_probe: &ar_environment_probe_anchor_t,
            ) -> c_float;
        }
        unsafe { ar_environment_probe_anchor_get_camera_scale_reference(environment_probe) }
    }

    /// Get the identifier of an anchor.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    /// Parameter `out_identifier`: A pointer to a UUID to fill out with the anchor identifier. Must be non-null.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_environment_probe_anchor.
    #[doc(alias = "ar_environment_probe_anchor_get_identifier")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn identifier(anchor: &ar_environment_probe_anchor_t, out_identifier: &mut uuid_t) {
        extern "C-unwind" {
            fn ar_environment_probe_anchor_get_identifier(
                anchor: &ar_environment_probe_anchor_t,
                out_identifier: &mut uuid_t,
            );
        }
        unsafe { ar_environment_probe_anchor_get_identifier(anchor, out_identifier) }
    }

    /// Get the timestamp corresponding to an anchor.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    ///
    /// Returns: The timestamp associated with the anchor.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_environment_probe_anchor.
    #[doc(alias = "ar_environment_probe_anchor_get_timestamp")]
    #[cfg(all(
        feature = "anchor",
        feature = "objc2",
        feature = "objc2-core-foundation"
    ))]
    #[inline]
    pub unsafe fn timestamp(anchor: &ar_environment_probe_anchor_t) -> CFTimeInterval {
        extern "C-unwind" {
            fn ar_environment_probe_anchor_get_timestamp(
                anchor: &ar_environment_probe_anchor_t,
            ) -> CFTimeInterval;
        }
        unsafe { ar_environment_probe_anchor_get_timestamp(anchor) }
    }
}

impl ar_environment_probe_anchors_t {
    /// Get the count of environment probe anchors in the collection.
    ///
    ///
    /// Parameter `environment_probe_anchors`: The collection of environment probe anchors.
    ///
    ///
    /// Returns: The number of environment probe anchors in the collection.
    ///
    /// # Safety
    ///
    /// `environment_probe_anchors` must implement OS_ar_environment_probe_anchors.
    #[doc(alias = "ar_environment_probe_anchors_get_count")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn count(environment_probe_anchors: &ar_environment_probe_anchors_t) -> usize {
        extern "C-unwind" {
            fn ar_environment_probe_anchors_get_count(
                environment_probe_anchors: &ar_environment_probe_anchors_t,
            ) -> usize;
        }
        unsafe { ar_environment_probe_anchors_get_count(environment_probe_anchors) }
    }
}

/// Handler for enumerating a collection of environment probe anchors.
///
///
/// Parameter `environment_probe_anchor`: The environment probe anchor.
///
///
/// Returns: Return `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_environment_probe_anchors_enumerator_t?language=objc)
#[cfg(all(feature = "anchor", feature = "block2", feature = "objc2"))]
pub type ar_environment_probe_anchors_enumerator_t =
    block2::Block<'static, fn(NonNull<ar_environment_probe_anchor_t>) -> bool>;

impl ar_environment_probe_anchors_t {
    /// Enumerate a collection of environment probe anchors.
    ///
    ///
    /// Parameter `environment_probe_anchors`: The collection of environment probe anchors.
    ///
    /// Parameter `environment_probe_anchors_enumerator`: The enumerator handler.
    ///
    /// # Safety
    ///
    /// `environment_probe_anchors` must implement OS_ar_environment_probe_anchors.
    #[doc(alias = "ar_environment_probe_anchors_enumerate_anchors")]
    #[cfg(all(feature = "anchor", feature = "block2", feature = "objc2"))]
    #[inline]
    pub unsafe fn enumerate_anchors(
        environment_probe_anchors: &ar_environment_probe_anchors_t,
        environment_probe_anchors_enumerator: &ar_environment_probe_anchors_enumerator_t,
    ) {
        extern "C-unwind" {
            fn ar_environment_probe_anchors_enumerate_anchors(
                environment_probe_anchors: &ar_environment_probe_anchors_t,
                environment_probe_anchors_enumerator: &ar_environment_probe_anchors_enumerator_t,
            );
        }
        unsafe {
            ar_environment_probe_anchors_enumerate_anchors(
                environment_probe_anchors,
                environment_probe_anchors_enumerator,
            )
        }
    }
}

/// Function for enumerating a collection of environment probe anchors.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `environment_probe_anchor`: The environment probe anchor.
///
///
/// Returns: Return `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_environment_probe_anchors_enumerator_function_t?language=objc)
#[cfg(all(feature = "anchor", feature = "objc2"))]
pub type ar_environment_probe_anchors_enumerator_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &ar_environment_probe_anchor_t) -> bool;

impl ar_environment_probe_anchors_t {
    /// Enumerate a collection of environment probe anchors.
    ///
    ///
    /// Parameter `environment_probe_anchors`: The collection of environment probe anchors.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `environment_probe_anchors_enumerator_function`: The enumerator function.
    ///
    /// # Safety
    ///
    /// - `environment_probe_anchors` must implement OS_ar_environment_probe_anchors.
    /// - `context` must be a valid pointer or null.
    /// - `environment_probe_anchors_enumerator_function` must be implemented correctly.
    #[doc(alias = "ar_environment_probe_anchors_enumerate_anchors_f")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn enumerate_anchors_f(
        environment_probe_anchors: &ar_environment_probe_anchors_t,
        context: *mut c_void,
        environment_probe_anchors_enumerator_function: ar_environment_probe_anchors_enumerator_function_t,
    ) {
        extern "C-unwind" {
            fn ar_environment_probe_anchors_enumerate_anchors_f(
                environment_probe_anchors: &ar_environment_probe_anchors_t,
                context: *mut c_void,
                environment_probe_anchors_enumerator_function: ar_environment_probe_anchors_enumerator_function_t,
            );
        }
        unsafe {
            ar_environment_probe_anchors_enumerate_anchors_f(
                environment_probe_anchors,
                context,
                environment_probe_anchors_enumerator_function,
            )
        }
    }
}

impl ar_environment_light_estimation_configuration_t {
    /// Create an environment light estimation configuration.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_environment_light_estimation_configuration_t`.
    #[doc(alias = "ar_environment_light_estimation_configuration_create")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn new() -> Retained<ar_environment_light_estimation_configuration_t> {
        extern "C-unwind" {
            fn ar_environment_light_estimation_configuration_create(
            ) -> *mut ar_environment_light_estimation_configuration_t;
        }
        let ret = unsafe { ar_environment_light_estimation_configuration_create() };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }
}

/// Handler triggered when there are updates to environment probe anchors.
///
///
/// Parameter `added_anchors`: Collection of anchors that are added.
///
/// Parameter `updated_anchors`: Collection of anchors that are updated.
///
/// Parameter `removed_anchors`: Collection of anchors that are removed.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_environment_light_estimation_update_handler_t?language=objc)
#[cfg(all(feature = "block2", feature = "objc2"))]
pub type ar_environment_light_estimation_update_handler_t = block2::Block<
    'static,
    fn(
        NonNull<ar_environment_probe_anchors_t>,
        NonNull<ar_environment_probe_anchors_t>,
        NonNull<ar_environment_probe_anchors_t>,
    ),
>;

/// Function to be called when there are updates to environment probe anchors.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `added_anchors`: Collection of anchors that are added.
///
/// Parameter `updated_anchors`: Collection of anchors that are updated.
///
/// Parameter `removed_anchors`: Collection of anchors that are removed.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_environment_light_estimation_update_handler_function_t?language=objc)
#[cfg(feature = "objc2")]
pub type ar_environment_light_estimation_update_handler_function_t =
    unsafe extern "C-unwind" fn(
        *mut c_void,
        &ar_environment_probe_anchors_t,
        &ar_environment_probe_anchors_t,
        &ar_environment_probe_anchors_t,
    );

impl ar_environment_light_estimation_provider_t {
    /// Create an environment light estimation provider.
    ///
    ///
    /// Parameter `environment_light_estimation_configuration`: Environment light estimation configuration.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_environment_light_estimation_provider_t`.
    ///
    /// # Safety
    ///
    /// `environment_light_estimation_configuration` must implement OS_ar_environment_light_estimation_configuration.
    #[doc(alias = "ar_environment_light_estimation_provider_create")]
    #[cfg(all(feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn new(
        environment_light_estimation_configuration: &ar_environment_light_estimation_configuration_t,
    ) -> Retained<ar_environment_light_estimation_provider_t> {
        extern "C-unwind" {
            fn ar_environment_light_estimation_provider_create(
                environment_light_estimation_configuration: &ar_environment_light_estimation_configuration_t,
            ) -> *mut ar_environment_light_estimation_provider_t;
        }
        let ret = unsafe {
            ar_environment_light_estimation_provider_create(
                environment_light_estimation_configuration,
            )
        };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Determines whether this device supports the environment light estimation provider.
    ///
    ///
    /// Returns: Returns `true` if the environment light estimation provider is supported on this device, `false` otherwise.
    #[doc(alias = "ar_environment_light_estimation_provider_is_supported")]
    #[inline]
    pub unsafe fn is_supported() -> bool {
        extern "C-unwind" {
            fn ar_environment_light_estimation_provider_is_supported() -> bool;
        }
        unsafe { ar_environment_light_estimation_provider_is_supported() }
    }

    /// Set the handler for receiving environment light estimation updates.
    ///
    ///
    /// Parameter `environment_light_estimation_provider`: Environment light estimation provider.
    ///
    /// Parameter `environment_light_estimation_anchor_updates_queue`: Queue on which the handler will be executed,
    /// sending NULL will default to the main queue.
    ///
    /// Parameter `environment_light_estimation_update_handler`: Handler to be triggered when new data
    /// arrives.
    ///
    ///
    /// Note: Setting this function will override the handler set using `ar_environment_light_estimation_provider_set_probe_update_handler_f`.
    ///
    /// # Safety
    ///
    /// - `environment_light_estimation_provider` must implement OS_ar_environment_light_estimation_provider.
    /// - `environment_light_estimation_anchor_updates_queue` possibly has additional threading requirements.
    #[doc(alias = "ar_environment_light_estimation_provider_set_update_handler")]
    #[cfg(all(
        feature = "block2",
        feature = "data_provider",
        feature = "dispatch2",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn set_update_handler(
        environment_light_estimation_provider: &ar_environment_light_estimation_provider_t,
        environment_light_estimation_anchor_updates_queue: Option<&DispatchQueue>,
        environment_light_estimation_update_handler: Option<
            &ar_environment_light_estimation_update_handler_t,
        >,
    ) {
        extern "C-unwind" {
            fn ar_environment_light_estimation_provider_set_update_handler(
                environment_light_estimation_provider: &ar_environment_light_estimation_provider_t,
                environment_light_estimation_anchor_updates_queue: Option<&DispatchQueue>,
                environment_light_estimation_update_handler: Option<
                    &ar_environment_light_estimation_update_handler_t,
                >,
            );
        }
        unsafe {
            ar_environment_light_estimation_provider_set_update_handler(
                environment_light_estimation_provider,
                environment_light_estimation_anchor_updates_queue,
                environment_light_estimation_update_handler,
            )
        }
    }

    /// Set the function for receiving environment light estimation updates.
    ///
    ///
    /// Parameter `environment_light_estimation_provider`: Environment light estimation provider.
    ///
    /// Parameter `environment_light_estimation_anchor_updates_queue`: Queue on which the function will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `environment_light_estimation_update_handler_function`: The function to be called when new data arrives.
    ///
    ///
    /// Note: Setting this function will override the handler set using `ar_environment_light_estimation_provider_set_probe_update_handler`.
    ///
    /// # Safety
    ///
    /// - `environment_light_estimation_provider` must implement OS_ar_environment_light_estimation_provider.
    /// - `environment_light_estimation_anchor_updates_queue` possibly has additional threading requirements.
    /// - `context` must be a valid pointer or null.
    /// - `environment_light_estimation_update_handler_function` must be implemented correctly.
    #[doc(alias = "ar_environment_light_estimation_provider_set_update_handler_f")]
    #[cfg(all(feature = "data_provider", feature = "dispatch2", feature = "objc2"))]
    #[inline]
    pub unsafe fn set_update_handler_f(
        environment_light_estimation_provider: &ar_environment_light_estimation_provider_t,
        environment_light_estimation_anchor_updates_queue: Option<&DispatchQueue>,
        context: *mut c_void,
        environment_light_estimation_update_handler_function: Option<
            ar_environment_light_estimation_update_handler_function_t,
        >,
    ) {
        extern "C-unwind" {
            fn ar_environment_light_estimation_provider_set_update_handler_f(
                environment_light_estimation_provider: &ar_environment_light_estimation_provider_t,
                environment_light_estimation_anchor_updates_queue: Option<&DispatchQueue>,
                context: *mut c_void,
                environment_light_estimation_update_handler_function: Option<
                    ar_environment_light_estimation_update_handler_function_t,
                >,
            );
        }
        unsafe {
            ar_environment_light_estimation_provider_set_update_handler_f(
                environment_light_estimation_provider,
                environment_light_estimation_anchor_updates_queue,
                context,
                environment_light_estimation_update_handler_function,
            )
        }
    }

    /// Get the authorization type required by the environment light estimation provider.
    ///
    ///
    /// Returns: Authorization type.
    #[doc(alias = "ar_environment_light_estimation_provider_get_required_authorization_type")]
    #[cfg(feature = "authorization")]
    #[inline]
    pub unsafe fn required_authorization_type() -> ar_authorization_type_t {
        extern "C-unwind" {
            fn ar_environment_light_estimation_provider_get_required_authorization_type(
            ) -> ar_authorization_type_t;
        }
        unsafe { ar_environment_light_estimation_provider_get_required_authorization_type() }
    }
}
