//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::cell::UnsafeCell;
use core::marker::{PhantomData, PhantomPinned};
use core::ptr::NonNull;
#[cfg(feature = "dispatch2")]
use dispatch2::*;
#[cfg(feature = "objc2-core-foundation")]
use objc2_core_foundation::*;

use crate::*;

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_error_t?language=objc)
#[repr(C)]
pub struct ar_error_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_error_t {}
);

extern "C" {
    /// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_error_domain?language=objc)
    #[cfg(feature = "objc2-core-foundation")]
    pub static ar_error_domain: &'static CFString;
}

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_error_code_t?language=objc)
pub type ar_error_code_t = isize;

impl ar_error_t {
    /// Get the error code associated with an error.
    ///
    ///
    /// Parameter `error`: The `ar_error_t` instance.
    ///
    ///
    /// Returns: The error code.
    ///
    /// # Safety
    ///
    /// `error` must implement OS_ar_error.
    #[doc(alias = "ar_error_get_error_code")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn error_code(error: &ar_error_t) -> ar_error_code_t {
        extern "C-unwind" {
            fn ar_error_get_error_code(error: &ar_error_t) -> ar_error_code_t;
        }
        unsafe { ar_error_get_error_code(error) }
    }

    /// Copy out a `CFErrorRef` that represents an `ar_error_t`.
    ///
    ///
    /// Parameter `error`: The `ar_error_t` instance.
    ///
    ///
    /// Returns: The `CFErrorRef`. The caller is responsible for calling `CFRelease` on the returned pointer.
    ///
    /// # Safety
    ///
    /// `error` must implement OS_ar_error.
    #[doc(alias = "ar_error_copy_cf_error")]
    #[cfg(all(feature = "objc2", feature = "objc2-core-foundation"))]
    #[inline]
    pub unsafe fn cf_error(error: &ar_error_t) -> CFRetained<CFError> {
        extern "C-unwind" {
            fn ar_error_copy_cf_error(error: &ar_error_t) -> Option<NonNull<CFError>>;
        }
        let ret = unsafe { ar_error_copy_cf_error(error) };
        let ret =
            ret.expect("function was marked as returning non-null, but actually returned NULL");
        unsafe { CFRetained::from_raw(ret) }
    }
}
