//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::cell::UnsafeCell;
use core::ffi::*;
use core::marker::{PhantomData, PhantomPinned};
use core::ptr::NonNull;
#[cfg(feature = "dispatch2")]
use dispatch2::*;
#[cfg(feature = "objc2")]
use objc2::__framework_prelude::*;

use crate::*;

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_hand_skeleton_t?language=objc)
#[repr(C)]
pub struct ar_hand_skeleton_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_hand_skeleton_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_hand_skeleton_joint_name_t?language=objc)
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct ar_hand_skeleton_joint_name_t(pub u64);
impl ar_hand_skeleton_joint_name_t {
    #[doc(alias = "ar_hand_skeleton_joint_name_wrist")]
    pub const wrist: Self = Self(0);
    #[doc(alias = "ar_hand_skeleton_joint_name_thumb_knuckle")]
    pub const thumb_knuckle: Self = Self(1);
    #[doc(alias = "ar_hand_skeleton_joint_name_thumb_intermediate_base")]
    pub const thumb_intermediate_base: Self = Self(2);
    #[doc(alias = "ar_hand_skeleton_joint_name_thumb_intermediate_tip")]
    pub const thumb_intermediate_tip: Self = Self(3);
    #[doc(alias = "ar_hand_skeleton_joint_name_thumb_tip")]
    pub const thumb_tip: Self = Self(4);
    #[doc(alias = "ar_hand_skeleton_joint_name_index_finger_metacarpal")]
    pub const index_finger_metacarpal: Self = Self(5);
    #[doc(alias = "ar_hand_skeleton_joint_name_index_finger_knuckle")]
    pub const index_finger_knuckle: Self = Self(6);
    #[doc(alias = "ar_hand_skeleton_joint_name_index_finger_intermediate_base")]
    pub const index_finger_intermediate_base: Self = Self(7);
    #[doc(alias = "ar_hand_skeleton_joint_name_index_finger_intermediate_tip")]
    pub const index_finger_intermediate_tip: Self = Self(8);
    #[doc(alias = "ar_hand_skeleton_joint_name_index_finger_tip")]
    pub const index_finger_tip: Self = Self(9);
    #[doc(alias = "ar_hand_skeleton_joint_name_middle_finger_metacarpal")]
    pub const middle_finger_metacarpal: Self = Self(10);
    #[doc(alias = "ar_hand_skeleton_joint_name_middle_finger_knuckle")]
    pub const middle_finger_knuckle: Self = Self(11);
    #[doc(alias = "ar_hand_skeleton_joint_name_middle_finger_intermediate_base")]
    pub const middle_finger_intermediate_base: Self = Self(12);
    #[doc(alias = "ar_hand_skeleton_joint_name_middle_finger_intermediate_tip")]
    pub const middle_finger_intermediate_tip: Self = Self(13);
    #[doc(alias = "ar_hand_skeleton_joint_name_middle_finger_tip")]
    pub const middle_finger_tip: Self = Self(14);
    #[doc(alias = "ar_hand_skeleton_joint_name_ring_finger_metacarpal")]
    pub const ring_finger_metacarpal: Self = Self(15);
    #[doc(alias = "ar_hand_skeleton_joint_name_ring_finger_knuckle")]
    pub const ring_finger_knuckle: Self = Self(16);
    #[doc(alias = "ar_hand_skeleton_joint_name_ring_finger_intermediate_base")]
    pub const ring_finger_intermediate_base: Self = Self(17);
    #[doc(alias = "ar_hand_skeleton_joint_name_ring_finger_intermediate_tip")]
    pub const ring_finger_intermediate_tip: Self = Self(18);
    #[doc(alias = "ar_hand_skeleton_joint_name_ring_finger_tip")]
    pub const ring_finger_tip: Self = Self(19);
    #[doc(alias = "ar_hand_skeleton_joint_name_little_finger_metacarpal")]
    pub const little_finger_metacarpal: Self = Self(20);
    #[doc(alias = "ar_hand_skeleton_joint_name_little_finger_knuckle")]
    pub const little_finger_knuckle: Self = Self(21);
    #[doc(alias = "ar_hand_skeleton_joint_name_little_finger_intermediate_base")]
    pub const little_finger_intermediate_base: Self = Self(22);
    #[doc(alias = "ar_hand_skeleton_joint_name_little_finger_intermediate_tip")]
    pub const little_finger_intermediate_tip: Self = Self(23);
    #[doc(alias = "ar_hand_skeleton_joint_name_little_finger_tip")]
    pub const little_finger_tip: Self = Self(24);
    #[doc(alias = "ar_hand_skeleton_joint_name_forearm_wrist")]
    pub const forearm_wrist: Self = Self(25);
    #[doc(alias = "ar_hand_skeleton_joint_name_forearm_arm")]
    pub const forearm_arm: Self = Self(26);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ar_hand_skeleton_joint_name_t {
    const ENCODING: Encoding = u64::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ar_hand_skeleton_joint_name_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

impl ar_hand_skeleton_t {
    /// Create a hand skeleton in a neutral pose that allows access to constants like joint indices, names, counts, etc.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_hand_skeleton_t`.
    #[doc(alias = "ar_hand_skeleton_create")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn new() -> Retained<ar_hand_skeleton_t> {
        extern "C-unwind" {
            fn ar_hand_skeleton_create() -> *mut ar_hand_skeleton_t;
        }
        let ret = unsafe { ar_hand_skeleton_create() };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Returns a bool value that indicates whether the two hand skeletons are equal.
    ///
    ///
    /// Parameter `hand_skeleton`: A hand skeleton to be compared.
    ///
    /// Parameter `other_hand_skeleton`: The other hand skeleton to be compared to.
    ///
    ///
    /// Returns: YES if the hand skeletons are equal, otherwise NO.
    ///
    /// # Safety
    ///
    /// - `hand_skeleton` must implement OS_ar_hand_skeleton.
    /// - `other_hand_skeleton` must implement OS_ar_hand_skeleton.
    #[doc(alias = "ar_hand_skeleton_is_equal_to_hand_skeleton")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn is_equal_to_hand_skeleton(
        hand_skeleton: Option<&ar_hand_skeleton_t>,
        other_hand_skeleton: Option<&ar_hand_skeleton_t>,
    ) -> bool {
        extern "C-unwind" {
            fn ar_hand_skeleton_is_equal_to_hand_skeleton(
                hand_skeleton: Option<&ar_hand_skeleton_t>,
                other_hand_skeleton: Option<&ar_hand_skeleton_t>,
            ) -> bool;
        }
        unsafe { ar_hand_skeleton_is_equal_to_hand_skeleton(hand_skeleton, other_hand_skeleton) }
    }

    /// Get a joint by it's name from the hand skeleton.
    ///
    ///
    /// Parameter `hand_skeleton`: The hand skeleton.
    ///
    /// Parameter `joint_name`: The joint index.
    ///
    ///
    /// Returns: An instance of `ar_skeleton_joint_t`.
    ///
    /// # Safety
    ///
    /// `hand_skeleton` must implement OS_ar_hand_skeleton.
    #[doc(alias = "ar_hand_skeleton_get_joint_named")]
    #[cfg(all(feature = "objc2", feature = "skeleton_joint"))]
    #[inline]
    pub unsafe fn joint_named(
        hand_skeleton: &ar_hand_skeleton_t,
        joint_name: ar_hand_skeleton_joint_name_t,
    ) -> Retained<ar_skeleton_joint_t> {
        extern "C-unwind" {
            fn ar_hand_skeleton_get_joint_named(
                hand_skeleton: &ar_hand_skeleton_t,
                joint_name: ar_hand_skeleton_joint_name_t,
            ) -> *mut ar_skeleton_joint_t;
        }
        let ret = unsafe { ar_hand_skeleton_get_joint_named(hand_skeleton, joint_name) };
        unsafe { Retained::retain_autoreleased(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Get the total number of joints in the hand skeleton.
    ///
    ///
    /// Parameter `hand_skeleton`: The hand skeleton.
    ///
    ///
    /// Returns: The number of joints.
    ///
    /// # Safety
    ///
    /// `hand_skeleton` must implement OS_ar_hand_skeleton.
    #[doc(alias = "ar_hand_skeleton_get_joint_count")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn joint_count(hand_skeleton: &ar_hand_skeleton_t) -> u64 {
        extern "C-unwind" {
            fn ar_hand_skeleton_get_joint_count(hand_skeleton: &ar_hand_skeleton_t) -> u64;
        }
        unsafe { ar_hand_skeleton_get_joint_count(hand_skeleton) }
    }

    /// Enumerate the names of joints in an `ar_hand_skeleton_t` using an enumeration block.
    ///
    ///
    /// Parameter `hand_skeleton`: The hand skeleton.
    ///
    /// Parameter `joint_enumerator`: The enumerator block.
    ///
    /// # Safety
    ///
    /// `hand_skeleton` must implement OS_ar_hand_skeleton.
    #[doc(alias = "ar_hand_skeleton_enumerate_joints")]
    #[cfg(all(feature = "block2", feature = "objc2", feature = "skeleton_joint"))]
    #[inline]
    pub unsafe fn enumerate_joints(
        hand_skeleton: &ar_hand_skeleton_t,
        joint_enumerator: &ar_skeleton_joint_enumerator_t,
    ) {
        extern "C-unwind" {
            fn ar_hand_skeleton_enumerate_joints(
                hand_skeleton: &ar_hand_skeleton_t,
                joint_enumerator: &ar_skeleton_joint_enumerator_t,
            );
        }
        unsafe { ar_hand_skeleton_enumerate_joints(hand_skeleton, joint_enumerator) }
    }

    /// Enumerate the joints in an `ar_hand_skeleton_t` using a function.
    ///
    ///
    /// Parameter `hand_skeleton`: The hand skeleton.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `joint_enumerator_function`: The enumerator function.
    ///
    /// # Safety
    ///
    /// - `hand_skeleton` must implement OS_ar_hand_skeleton.
    /// - `context` must be a valid pointer or null.
    /// - `joint_enumerator_function` must be implemented correctly.
    #[doc(alias = "ar_hand_skeleton_enumerate_joints_f")]
    #[cfg(all(feature = "objc2", feature = "skeleton_joint"))]
    #[inline]
    pub unsafe fn enumerate_joints_f(
        hand_skeleton: &ar_hand_skeleton_t,
        context: *mut c_void,
        joint_enumerator_function: ar_skeleton_joint_enumerator_function_t,
    ) {
        extern "C-unwind" {
            fn ar_hand_skeleton_enumerate_joints_f(
                hand_skeleton: &ar_hand_skeleton_t,
                context: *mut c_void,
                joint_enumerator_function: ar_skeleton_joint_enumerator_function_t,
            );
        }
        unsafe {
            ar_hand_skeleton_enumerate_joints_f(hand_skeleton, context, joint_enumerator_function)
        }
    }
}
