//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::cell::UnsafeCell;
use core::ffi::*;
use core::marker::{PhantomData, PhantomPinned};
use core::ptr::NonNull;
#[cfg(feature = "dispatch2")]
use dispatch2::*;
#[cfg(feature = "objc2")]
use objc2::__framework_prelude::*;
#[cfg(feature = "objc2-core-foundation")]
use objc2_core_foundation::*;

use crate::*;

/// Status enum values for the hand anchor at a specified timestamp from the provider.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_hand_anchor_query_status_t?language=objc)
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct ar_hand_anchor_query_status_t(pub isize);
impl ar_hand_anchor_query_status_t {
    /// Status enum values for the hand anchor at a specified timestamp from the provider.
    #[doc(alias = "ar_hand_anchor_query_status_success")]
    pub const success: Self = Self(0);
    /// Status enum values for the hand anchor at a specified timestamp from the provider.
    #[doc(alias = "ar_hand_anchor_query_status_failure")]
    pub const failure: Self = Self(1);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ar_hand_anchor_query_status_t {
    const ENCODING: Encoding = isize::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ar_hand_anchor_query_status_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_hand_anchor_t?language=objc)
#[repr(C)]
pub struct ar_hand_anchor_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_hand_anchor_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_hand_tracking_configuration_t?language=objc)
#[repr(C)]
pub struct ar_hand_tracking_configuration_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_hand_tracking_configuration_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_hand_tracking_provider_t?language=objc)
#[repr(C)]
pub struct ar_hand_tracking_provider_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_hand_tracking_provider_t {}
);

/// Enum for the chirality of a hand.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_hand_chirality_t?language=objc)
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct ar_hand_chirality_t(pub isize);
impl ar_hand_chirality_t {
    /// Enum for the chirality of a hand.
    #[doc(alias = "ar_hand_chirality_right")]
    pub const right: Self = Self(0);
    /// Enum for the chirality of a hand.
    #[doc(alias = "ar_hand_chirality_left")]
    pub const left: Self = Self(1);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ar_hand_chirality_t {
    const ENCODING: Encoding = isize::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ar_hand_chirality_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// Enum for hand fidelity.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_hand_fidelity_t?language=objc)
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct ar_hand_fidelity_t(pub isize);
impl ar_hand_fidelity_t {
    /// Enum for hand fidelity.
    #[doc(alias = "ar_hand_fidelity_nominal")]
    pub const nominal: Self = Self(0);
    /// Enum for hand fidelity.
    #[doc(alias = "ar_hand_fidelity_high")]
    pub const high: Self = Self(1);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ar_hand_fidelity_t {
    const ENCODING: Encoding = isize::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ar_hand_fidelity_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

impl ar_hand_anchor_t {
    /// Create a hand anchor.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_hand_anchor_t`.
    #[doc(alias = "ar_hand_anchor_create")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn new() -> Retained<ar_hand_anchor_t> {
        extern "C-unwind" {
            fn ar_hand_anchor_create() -> *mut ar_hand_anchor_t;
        }
        let ret = unsafe { ar_hand_anchor_create() };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Returns a bool value that indicates whether the two hand anchors are equal.
    ///
    ///
    /// Parameter `anchor`: A hand anchor to be compared.
    ///
    /// Parameter `other_anchor`: The other hand anchor to be compared to.
    ///
    ///
    /// Returns: YES if the hand anchors are equal, otherwise NO.
    ///
    /// # Safety
    ///
    /// - `anchor` must implement OS_ar_hand_anchor.
    /// - `other_anchor` must implement OS_ar_hand_anchor.
    #[doc(alias = "ar_hand_anchor_is_equal_to_hand_anchor")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn is_equal_to_hand_anchor(
        anchor: Option<&ar_hand_anchor_t>,
        other_anchor: Option<&ar_hand_anchor_t>,
    ) -> bool {
        extern "C-unwind" {
            fn ar_hand_anchor_is_equal_to_hand_anchor(
                anchor: Option<&ar_hand_anchor_t>,
                other_anchor: Option<&ar_hand_anchor_t>,
            ) -> bool;
        }
        unsafe { ar_hand_anchor_is_equal_to_hand_anchor(anchor, other_anchor) }
    }

    /// Get the hand skeleton of a hand anchor.
    ///
    ///
    /// Parameter `hand_anchor`: The hand anchor.
    ///
    ///
    /// Returns: The skeleton.
    ///
    /// # Safety
    ///
    /// `hand_anchor` must implement OS_ar_hand_anchor.
    #[doc(alias = "ar_hand_anchor_get_hand_skeleton")]
    #[cfg(all(feature = "anchor", feature = "hand_skeleton", feature = "objc2"))]
    #[inline]
    pub unsafe fn hand_skeleton(
        hand_anchor: &ar_hand_anchor_t,
    ) -> Option<Retained<ar_hand_skeleton_t>> {
        extern "C-unwind" {
            fn ar_hand_anchor_get_hand_skeleton(
                hand_anchor: &ar_hand_anchor_t,
            ) -> *mut ar_hand_skeleton_t;
        }
        let ret = unsafe { ar_hand_anchor_get_hand_skeleton(hand_anchor) };
        unsafe { Retained::retain_autoreleased(ret) }
    }

    /// Get the chirality of the hand tracked by a hand anchor.
    ///
    ///
    /// Parameter `hand_anchor`: The hand anchor.
    ///
    ///
    /// Returns: The chirality of the hand.
    ///
    /// # Safety
    ///
    /// `hand_anchor` must implement OS_ar_hand_anchor.
    #[doc(alias = "ar_hand_anchor_get_chirality")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn chirality(hand_anchor: &ar_hand_anchor_t) -> ar_hand_chirality_t {
        extern "C-unwind" {
            fn ar_hand_anchor_get_chirality(hand_anchor: &ar_hand_anchor_t) -> ar_hand_chirality_t;
        }
        unsafe { ar_hand_anchor_get_chirality(hand_anchor) }
    }

    /// Get the fidelity of the hand anchor.
    ///
    ///
    /// Parameter `hand_anchor`: The hand anchor.
    ///
    ///
    /// Returns: The fidelity of the anchor.
    ///
    /// # Safety
    ///
    /// `hand_anchor` must implement OS_ar_hand_anchor.
    #[doc(alias = "ar_hand_anchor_get_fidelity")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn fidelity(hand_anchor: &ar_hand_anchor_t) -> ar_hand_fidelity_t {
        extern "C-unwind" {
            fn ar_hand_anchor_get_fidelity(hand_anchor: &ar_hand_anchor_t) -> ar_hand_fidelity_t;
        }
        unsafe { ar_hand_anchor_get_fidelity(hand_anchor) }
    }

    /// Get the identifier of an anchor.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    /// Parameter `out_identifier`: A pointer to a UUID to fill out with the anchor identifier. Must be non-null.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_hand_anchor.
    #[doc(alias = "ar_hand_anchor_get_identifier")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn identifier(anchor: &ar_hand_anchor_t, out_identifier: &mut uuid_t) {
        extern "C-unwind" {
            fn ar_hand_anchor_get_identifier(
                anchor: &ar_hand_anchor_t,
                out_identifier: &mut uuid_t,
            );
        }
        unsafe { ar_hand_anchor_get_identifier(anchor, out_identifier) }
    }

    /// Get the timestamp corresponding to an anchor.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    ///
    /// Returns: The timestamp associated with the anchor.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_hand_anchor.
    #[doc(alias = "ar_hand_anchor_get_timestamp")]
    #[cfg(all(
        feature = "anchor",
        feature = "objc2",
        feature = "objc2-core-foundation"
    ))]
    #[inline]
    pub unsafe fn timestamp(anchor: &ar_hand_anchor_t) -> CFTimeInterval {
        extern "C-unwind" {
            fn ar_hand_anchor_get_timestamp(anchor: &ar_hand_anchor_t) -> CFTimeInterval;
        }
        unsafe { ar_hand_anchor_get_timestamp(anchor) }
    }

    /// Determine whether an anchor is tracked.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    ///
    /// Returns: `true` if the anchor is tracked, `false` otherwise.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_hand_anchor.
    #[doc(alias = "ar_hand_anchor_is_tracked")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn is_tracked(anchor: &ar_hand_anchor_t) -> bool {
        extern "C-unwind" {
            fn ar_hand_anchor_is_tracked(anchor: &ar_hand_anchor_t) -> bool;
        }
        unsafe { ar_hand_anchor_is_tracked(anchor) }
    }
}

/// Handler called when there are updates to hand tracking.
///
///
/// Parameter `hand_anchor_left`: The latest left hand anchor.
///
/// Parameter `hand_anchor_right`: The latest right hand anchor.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_hand_tracking_update_handler_t?language=objc)
#[cfg(all(feature = "anchor", feature = "block2", feature = "objc2"))]
pub type ar_hand_tracking_update_handler_t =
    block2::Block<'static, fn(NonNull<ar_hand_anchor_t>, NonNull<ar_hand_anchor_t>)>;

/// Function to be called when there are updates to hand tracking.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `hand_anchor_left`: The latest left hand anchor.
///
/// Parameter `hand_anchor_right`: The latest right hand anchor.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_hand_tracking_update_handler_function_t?language=objc)
#[cfg(all(feature = "anchor", feature = "objc2"))]
pub type ar_hand_tracking_update_handler_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &ar_hand_anchor_t, &ar_hand_anchor_t);

impl ar_hand_tracking_configuration_t {
    /// Create a hand tracking configuration.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_hand_tracking_configuration_t`.
    #[doc(alias = "ar_hand_tracking_configuration_create")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn new() -> Retained<ar_hand_tracking_configuration_t> {
        extern "C-unwind" {
            fn ar_hand_tracking_configuration_create() -> *mut ar_hand_tracking_configuration_t;
        }
        let ret = unsafe { ar_hand_tracking_configuration_create() };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }
}

impl ar_hand_tracking_provider_t {
    /// Create a hand tracking provider.
    ///
    ///
    /// Parameter `hand_tracking_configuration`: The configuration for hand tracking.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_hand_tracking_provider_t`.
    ///
    /// # Safety
    ///
    /// `hand_tracking_configuration` must implement OS_ar_hand_tracking_configuration.
    #[doc(alias = "ar_hand_tracking_provider_create")]
    #[cfg(all(feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn new(
        hand_tracking_configuration: &ar_hand_tracking_configuration_t,
    ) -> Retained<ar_hand_tracking_provider_t> {
        extern "C-unwind" {
            fn ar_hand_tracking_provider_create(
                hand_tracking_configuration: &ar_hand_tracking_configuration_t,
            ) -> *mut ar_hand_tracking_provider_t;
        }
        let ret = unsafe { ar_hand_tracking_provider_create(hand_tracking_configuration) };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Set the handler for receiving hand tracking updates.
    ///
    ///
    /// Parameter `hand_tracking_provider`: The hand tracking provider.
    ///
    /// Parameter `hand_anchor_updates_queue`: The queue on which the handler will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `hand_tracking_update_handler`: The handler to be called when new data arrives.
    ///
    ///
    /// Note: Setting this handler will override the function set using `ar_hand_tracking_provider_set_update_handler_f`.
    ///
    /// # Safety
    ///
    /// - `hand_tracking_provider` must implement OS_ar_hand_tracking_provider.
    /// - `hand_anchor_updates_queue` possibly has additional threading requirements.
    #[doc(alias = "ar_hand_tracking_provider_set_update_handler")]
    #[cfg(all(
        feature = "anchor",
        feature = "block2",
        feature = "data_provider",
        feature = "dispatch2",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn set_update_handler(
        hand_tracking_provider: &ar_hand_tracking_provider_t,
        hand_anchor_updates_queue: Option<&DispatchQueue>,
        hand_tracking_update_handler: Option<&ar_hand_tracking_update_handler_t>,
    ) {
        extern "C-unwind" {
            fn ar_hand_tracking_provider_set_update_handler(
                hand_tracking_provider: &ar_hand_tracking_provider_t,
                hand_anchor_updates_queue: Option<&DispatchQueue>,
                hand_tracking_update_handler: Option<&ar_hand_tracking_update_handler_t>,
            );
        }
        unsafe {
            ar_hand_tracking_provider_set_update_handler(
                hand_tracking_provider,
                hand_anchor_updates_queue,
                hand_tracking_update_handler,
            )
        }
    }

    /// Set the function for receiving hand tracking updates.
    ///
    ///
    /// Parameter `hand_tracking_provider`: The hand tracking provider.
    ///
    /// Parameter `hand_anchor_updates_queue`: The queue on which the function will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `hand_tracking_update_handler_function`: The function to be called when new data arrives.
    ///
    ///
    /// Note: Setting this function will override the handler set using `ar_hand_tracking_provider_set_update_handler`.
    ///
    /// # Safety
    ///
    /// - `hand_tracking_provider` must implement OS_ar_hand_tracking_provider.
    /// - `hand_anchor_updates_queue` possibly has additional threading requirements.
    /// - `context` must be a valid pointer or null.
    /// - `hand_tracking_update_handler_function` must be implemented correctly.
    #[doc(alias = "ar_hand_tracking_provider_set_update_handler_f")]
    #[cfg(all(
        feature = "anchor",
        feature = "data_provider",
        feature = "dispatch2",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn set_update_handler_f(
        hand_tracking_provider: &ar_hand_tracking_provider_t,
        hand_anchor_updates_queue: Option<&DispatchQueue>,
        context: *mut c_void,
        hand_tracking_update_handler_function: Option<ar_hand_tracking_update_handler_function_t>,
    ) {
        extern "C-unwind" {
            fn ar_hand_tracking_provider_set_update_handler_f(
                hand_tracking_provider: &ar_hand_tracking_provider_t,
                hand_anchor_updates_queue: Option<&DispatchQueue>,
                context: *mut c_void,
                hand_tracking_update_handler_function: Option<
                    ar_hand_tracking_update_handler_function_t,
                >,
            );
        }
        unsafe {
            ar_hand_tracking_provider_set_update_handler_f(
                hand_tracking_provider,
                hand_anchor_updates_queue,
                context,
                hand_tracking_update_handler_function,
            )
        }
    }

    /// Determine whether this device supports the hand tracking provider.
    ///
    ///
    /// Returns: `true` if the hand tracking provider is supported on this device, `false` otherwise.
    #[doc(alias = "ar_hand_tracking_provider_is_supported")]
    #[inline]
    pub unsafe fn is_supported() -> bool {
        extern "C-unwind" {
            fn ar_hand_tracking_provider_is_supported() -> bool;
        }
        unsafe { ar_hand_tracking_provider_is_supported() }
    }

    /// Fill the given `ar_hand_anchor_t` instances with the latest hand tracking data. Subsequent calls will continue returning the latest hand tracking
    /// data. New anchor data will be returned when the hand tracking data is updated.
    ///
    /// Note: For apps compiled with a visionOS 1.0 SDK, subsequent calls to this function will not update the given `ar_hand_anchor_t` instances, and will
    /// return `false` until the latest hand tracking data has arrived.
    ///
    ///
    /// Parameter `hand_tracking_provider`: The hand tracking provider.
    ///
    /// Parameter `hand_anchor_left`: The `ar_hand_anchor_t` instance for the left hand to be updated.
    ///
    /// Parameter `hand_anchor_right`: The `ar_hand_anchor_t` instance for the right hand to be updated.
    ///
    ///
    /// Returns: `true` on success while the `hand_tracking_provider` is running, `false` otherwise.
    ///
    /// # Safety
    ///
    /// - `hand_tracking_provider` must implement OS_ar_hand_tracking_provider.
    /// - `hand_anchor_left` must implement OS_ar_hand_anchor.
    /// - `hand_anchor_right` must implement OS_ar_hand_anchor.
    #[doc(alias = "ar_hand_tracking_provider_get_latest_anchors")]
    #[cfg(all(feature = "anchor", feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn latest_anchors(
        hand_tracking_provider: &ar_hand_tracking_provider_t,
        hand_anchor_left: &ar_hand_anchor_t,
        hand_anchor_right: &ar_hand_anchor_t,
    ) -> bool {
        extern "C-unwind" {
            fn ar_hand_tracking_provider_get_latest_anchors(
                hand_tracking_provider: &ar_hand_tracking_provider_t,
                hand_anchor_left: &ar_hand_anchor_t,
                hand_anchor_right: &ar_hand_anchor_t,
            ) -> bool;
        }
        unsafe {
            ar_hand_tracking_provider_get_latest_anchors(
                hand_tracking_provider,
                hand_anchor_left,
                hand_anchor_right,
            )
        }
    }

    /// Fill the given `ar_hand_anchor_t` instances with the best estimated tracking data given the provided `timestamp`.
    ///
    /// The provided `timestamp`when rendering should be obtained from `cp_frame_timing_get_trackable_anchor_time`.
    ///
    ///
    /// ```text
    ///  cp_time_t anchor_prediction_time = cp_frame_timing_get_trackable_anchor_time(timing);
    ///  CFTimeInterval anchor_prediction_time_seconds = cp_time_to_cf_time_interval(anchor_prediction_time);
    ///
    ///  ar_hand_tracking_provider_query_anchors_at_timestamp(provider, hand_anchor_left, hand_anchor_right);
    ///
    ///  if (ar_trackable_anchor_is_tracked(hand_anchor_left)) {
    ///     ...
    ///  }
    ///
    ///  if (ar_trackable_anchor_is_tracked(hand_anchor_right)) {
    ///     ...
    ///  }
    /// ```
    ///
    ///
    /// Parameter `hand_tracking_provider`: The hand tracking provider.
    ///
    /// Parameter `timestamp`: Target timestamp, mach absolute time in seconds.
    ///
    /// Parameter `hand_anchor_left`: The anchor instance for the left hand to be updated.
    ///
    /// Parameter `hand_anchor_right`: The anchor instance for the right hand to be updated.
    ///
    /// # Safety
    ///
    /// - `hand_tracking_provider` must implement OS_ar_hand_tracking_provider.
    /// - `hand_anchor_left` must implement OS_ar_hand_anchor.
    /// - `hand_anchor_right` must implement OS_ar_hand_anchor.
    #[doc(alias = "ar_hand_tracking_provider_query_anchors_at_timestamp")]
    #[cfg(all(
        feature = "anchor",
        feature = "data_provider",
        feature = "objc2",
        feature = "objc2-core-foundation"
    ))]
    #[inline]
    pub unsafe fn query_anchors_at_timestamp(
        hand_tracking_provider: &ar_hand_tracking_provider_t,
        timestamp: CFTimeInterval,
        hand_anchor_left: &ar_hand_anchor_t,
        hand_anchor_right: &ar_hand_anchor_t,
    ) -> ar_hand_anchor_query_status_t {
        extern "C-unwind" {
            fn ar_hand_tracking_provider_query_anchors_at_timestamp(
                hand_tracking_provider: &ar_hand_tracking_provider_t,
                timestamp: CFTimeInterval,
                hand_anchor_left: &ar_hand_anchor_t,
                hand_anchor_right: &ar_hand_anchor_t,
            ) -> ar_hand_anchor_query_status_t;
        }
        unsafe {
            ar_hand_tracking_provider_query_anchors_at_timestamp(
                hand_tracking_provider,
                timestamp,
                hand_anchor_left,
                hand_anchor_right,
            )
        }
    }

    /// Get the authorization type required by the hand tracking provider.
    ///
    ///
    /// Returns: The required authorization type.
    #[doc(alias = "ar_hand_tracking_provider_get_required_authorization_type")]
    #[cfg(feature = "authorization")]
    #[inline]
    pub unsafe fn required_authorization_type() -> ar_authorization_type_t {
        extern "C-unwind" {
            fn ar_hand_tracking_provider_get_required_authorization_type() -> ar_authorization_type_t;
        }
        unsafe { ar_hand_tracking_provider_get_required_authorization_type() }
    }
}
