//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::cell::UnsafeCell;
use core::ffi::*;
use core::marker::{PhantomData, PhantomPinned};
use core::ptr::NonNull;
#[cfg(feature = "dispatch2")]
use dispatch2::*;

use crate::*;

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_identifiers_t?language=objc)
#[repr(C)]
pub struct ar_identifiers_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_identifiers_t {}
);

impl ar_identifiers_t {
    /// Returns a bool value that indicates whether the two collections of identifiers are equal.
    ///
    ///
    /// Parameter `identifiers`: A collection of identifiers to be compared.
    ///
    /// Parameter `other_identifiers`: The other collection of identifiers to be compared to.
    ///
    ///
    /// Returns: YES if the collections of identifiers are equal, otherwise NO.
    ///
    /// # Safety
    ///
    /// - `identifiers` must implement OS_ar_identifiers.
    /// - `other_identifiers` must implement OS_ar_identifiers.
    #[doc(alias = "ar_identifiers_is_equal_to_identifiers")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn is_equal_to_identifiers(
        identifiers: Option<&ar_identifiers_t>,
        other_identifiers: Option<&ar_identifiers_t>,
    ) -> bool {
        extern "C-unwind" {
            fn ar_identifiers_is_equal_to_identifiers(
                identifiers: Option<&ar_identifiers_t>,
                other_identifiers: Option<&ar_identifiers_t>,
            ) -> bool;
        }
        unsafe { ar_identifiers_is_equal_to_identifiers(identifiers, other_identifiers) }
    }

    /// Get the count of identifiers in a collection.
    ///
    ///
    /// Parameter `identifiers`: The collection of identifiers.
    ///
    ///
    /// Returns: The number of identifiers in the collection.
    ///
    /// # Safety
    ///
    /// `identifiers` must implement OS_ar_identifiers.
    #[doc(alias = "ar_identifiers_get_count")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn count(identifiers: &ar_identifiers_t) -> usize {
        extern "C-unwind" {
            fn ar_identifiers_get_count(identifiers: &ar_identifiers_t) -> usize;
        }
        unsafe { ar_identifiers_get_count(identifiers) }
    }
}

/// Handler for enumerating a collection of identifiers.
///
///
/// Parameter `identifier`: The identifier.
///
///
/// Note: The `identifier` will have the same lifetime as the scope of the enumerator.
///
///
/// Returns: `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_identifiers_enumerator_t?language=objc)
#[cfg(feature = "block2")]
pub type ar_identifiers_enumerator_t = block2::Block<'static, fn(NonNull<uuid_t>) -> bool>;

impl ar_identifiers_t {
    /// Enumerate a collection of identifiers.
    ///
    ///
    /// Parameter `identifiers`: The collection of identifiers.
    ///
    /// Parameter `identifiers_enumerator`: The enumerator handler.
    ///
    /// # Safety
    ///
    /// `identifiers` must implement OS_ar_identifiers.
    #[doc(alias = "ar_identifiers_enumerate_identifiers")]
    #[cfg(all(feature = "block2", feature = "objc2"))]
    #[inline]
    pub unsafe fn enumerate_identifiers(
        identifiers: &ar_identifiers_t,
        identifiers_enumerator: &ar_identifiers_enumerator_t,
    ) {
        extern "C-unwind" {
            fn ar_identifiers_enumerate_identifiers(
                identifiers: &ar_identifiers_t,
                identifiers_enumerator: &ar_identifiers_enumerator_t,
            );
        }
        unsafe { ar_identifiers_enumerate_identifiers(identifiers, identifiers_enumerator) }
    }
}

/// Function for enumerating a collection of identifiers.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `identifier`: The identifier.
///
///
/// Returns: `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_identifiers_enumerator_function_t?language=objc)
pub type ar_identifiers_enumerator_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &mut uuid_t) -> bool;

impl ar_identifiers_t {
    /// Enumerate a collection of identifiers using a function.
    ///
    ///
    /// Parameter `identifiers`: The collection of identifiers.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `identifiers_enumerator_function`: The enumerator function.
    ///
    /// # Safety
    ///
    /// - `identifiers` must implement OS_ar_identifiers.
    /// - `context` must be a valid pointer or null.
    /// - `identifiers_enumerator_function` must be implemented correctly.
    #[doc(alias = "ar_identifiers_enumerate_identifiers_f")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn enumerate_identifiers_f(
        identifiers: &ar_identifiers_t,
        context: *mut c_void,
        identifiers_enumerator_function: ar_identifiers_enumerator_function_t,
    ) {
        extern "C-unwind" {
            fn ar_identifiers_enumerate_identifiers_f(
                identifiers: &ar_identifiers_t,
                context: *mut c_void,
                identifiers_enumerator_function: ar_identifiers_enumerator_function_t,
            );
        }
        unsafe {
            ar_identifiers_enumerate_identifiers_f(
                identifiers,
                context,
                identifiers_enumerator_function,
            )
        }
    }
}
