// This file has been automatically generated by `objc2`'s `header-translator`.
// DO NOT EDIT

#![allow(unused_imports)]
#![allow(deprecated)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(missing_docs)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::type_complexity)]
#![allow(clippy::new_ret_no_self)]
#![allow(clippy::upper_case_acronyms)]
#![allow(clippy::identity_op)]
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::doc_lazy_continuation)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(rustdoc::bare_urls)]
#![allow(rustdoc::invalid_html_tags)]

#[link(name = "ARKit", kind = "framework")]
extern "C" {}

#[cfg(feature = "accessory_tracking")]
#[path = "accessory_tracking.rs"]
mod __accessory_tracking;
#[cfg(feature = "anchor")]
#[path = "anchor.rs"]
mod __anchor;
#[cfg(feature = "authorization")]
#[path = "authorization.rs"]
mod __authorization;
#[cfg(feature = "barcode_detection")]
#[path = "barcode_detection.rs"]
mod __barcode_detection;
#[cfg(feature = "camera_frame_provider")]
#[path = "camera_frame_provider.rs"]
mod __camera_frame_provider;
#[cfg(feature = "camera_region")]
#[path = "camera_region.rs"]
mod __camera_region;
#[cfg(feature = "data")]
#[path = "data.rs"]
mod __data;
#[cfg(feature = "data_provider")]
#[path = "data_provider.rs"]
mod __data_provider;
#[cfg(feature = "environment_light_estimation")]
#[path = "environment_light_estimation.rs"]
mod __environment_light_estimation;
#[cfg(feature = "error")]
#[path = "error.rs"]
mod __error;
#[cfg(feature = "hand_skeleton")]
#[path = "hand_skeleton.rs"]
mod __hand_skeleton;
#[cfg(feature = "hand_tracking")]
#[path = "hand_tracking.rs"]
mod __hand_tracking;
#[cfg(feature = "identifiers")]
#[path = "identifiers.rs"]
mod __identifiers;
#[cfg(feature = "image_tracking")]
#[path = "image_tracking.rs"]
mod __image_tracking;
#[cfg(feature = "object")]
#[path = "object.rs"]
mod __object;
#[cfg(feature = "object_tracking")]
#[path = "object_tracking.rs"]
mod __object_tracking;
#[cfg(feature = "plane_detection")]
#[path = "plane_detection.rs"]
mod __plane_detection;
#[cfg(feature = "room_tracking")]
#[path = "room_tracking.rs"]
mod __room_tracking;
#[cfg(feature = "scene_reconstruction")]
#[path = "scene_reconstruction.rs"]
mod __scene_reconstruction;
#[cfg(feature = "session")]
#[path = "session.rs"]
mod __session;
#[cfg(feature = "shared_coordinate_space")]
#[path = "shared_coordinate_space.rs"]
mod __shared_coordinate_space;
#[cfg(feature = "skeleton_joint")]
#[path = "skeleton_joint.rs"]
mod __skeleton_joint;
#[cfg(feature = "stereo_properties")]
#[path = "stereo_properties.rs"]
mod __stereo_properties;
#[cfg(feature = "strings_collection")]
#[path = "strings_collection.rs"]
mod __strings_collection;
#[cfg(feature = "transform_correction")]
#[path = "transform_correction.rs"]
mod __transform_correction;
#[cfg(feature = "world_tracking")]
#[path = "world_tracking.rs"]
mod __world_tracking;

#[cfg(all(feature = "accessory_tracking", feature = "objc2"))]
pub use self::__accessory_tracking::ar_accessories_enumerator_function_t;
#[cfg(all(feature = "accessory_tracking", feature = "block2", feature = "objc2"))]
pub use self::__accessory_tracking::ar_accessories_enumerator_t;
#[cfg(feature = "accessory_tracking")]
pub use self::__accessory_tracking::ar_accessories_t;
#[cfg(feature = "accessory_tracking")]
pub use self::__accessory_tracking::ar_accessory_anchor_t;
#[cfg(feature = "accessory_tracking")]
pub use self::__accessory_tracking::ar_accessory_anchor_tracking_state_t;
#[cfg(all(feature = "accessory_tracking", feature = "anchor", feature = "objc2"))]
pub use self::__accessory_tracking::ar_accessory_anchors_enumerator_function_t;
#[cfg(all(
    feature = "accessory_tracking",
    feature = "anchor",
    feature = "block2",
    feature = "objc2"
))]
pub use self::__accessory_tracking::ar_accessory_anchors_enumerator_t;
#[cfg(feature = "accessory_tracking")]
pub use self::__accessory_tracking::ar_accessory_anchors_t;
#[cfg(feature = "accessory_tracking")]
pub use self::__accessory_tracking::ar_accessory_chirality_t;
#[cfg(all(feature = "accessory_tracking", feature = "error", feature = "objc2"))]
pub use self::__accessory_tracking::ar_accessory_device_load_completion_handler_function_t;
#[cfg(all(
    feature = "accessory_tracking",
    feature = "block2",
    feature = "error",
    feature = "objc2"
))]
pub use self::__accessory_tracking::ar_accessory_device_load_completion_handler_t;
#[cfg(feature = "accessory_tracking")]
pub use self::__accessory_tracking::ar_accessory_location_name_aim;
#[cfg(feature = "accessory_tracking")]
pub use self::__accessory_tracking::ar_accessory_location_name_grip;
#[cfg(feature = "accessory_tracking")]
pub use self::__accessory_tracking::ar_accessory_location_name_grip_surface;
#[cfg(feature = "accessory_tracking")]
pub use self::__accessory_tracking::ar_accessory_source_type_t;
#[cfg(feature = "accessory_tracking")]
pub use self::__accessory_tracking::ar_accessory_t;
#[cfg(feature = "accessory_tracking")]
pub use self::__accessory_tracking::ar_accessory_tracking_configuration_t;
#[cfg(all(feature = "accessory_tracking", feature = "error"))]
pub use self::__accessory_tracking::ar_accessory_tracking_error_code_t;
#[cfg(feature = "accessory_tracking")]
pub use self::__accessory_tracking::ar_accessory_tracking_provider_t;
#[cfg(all(feature = "accessory_tracking", feature = "objc2"))]
pub use self::__accessory_tracking::ar_accessory_tracking_update_handler_function_t;
#[cfg(all(feature = "accessory_tracking", feature = "block2", feature = "objc2"))]
pub use self::__accessory_tracking::ar_accessory_tracking_update_handler_t;
#[cfg(feature = "anchor")]
pub use self::__anchor::ar_anchor_t;
#[cfg(feature = "anchor")]
pub use self::__anchor::ar_trackable_anchor_t;
#[cfg(feature = "authorization")]
pub use self::__authorization::ar_authorization_result_t;
#[cfg(all(feature = "authorization", feature = "objc2"))]
pub use self::__authorization::ar_authorization_results_enumerator_function_t;
#[cfg(all(feature = "authorization", feature = "block2", feature = "objc2"))]
pub use self::__authorization::ar_authorization_results_enumerator_t;
#[cfg(feature = "authorization")]
pub use self::__authorization::ar_authorization_results_t;
#[cfg(feature = "authorization")]
pub use self::__authorization::ar_authorization_status_t;
#[cfg(feature = "authorization")]
pub use self::__authorization::ar_authorization_type_t;
#[cfg(feature = "barcode_detection")]
pub use self::__barcode_detection::ar_barcode_anchor_t;
#[cfg(all(feature = "anchor", feature = "barcode_detection", feature = "objc2"))]
pub use self::__barcode_detection::ar_barcode_anchors_enumerator_function_t;
#[cfg(all(
    feature = "anchor",
    feature = "barcode_detection",
    feature = "block2",
    feature = "objc2"
))]
pub use self::__barcode_detection::ar_barcode_anchors_enumerator_t;
#[cfg(feature = "barcode_detection")]
pub use self::__barcode_detection::ar_barcode_anchors_t;
#[cfg(feature = "barcode_detection")]
pub use self::__barcode_detection::ar_barcode_detection_callbacks_t;
#[cfg(feature = "barcode_detection")]
pub use self::__barcode_detection::ar_barcode_detection_configuration_t;
#[cfg(feature = "barcode_detection")]
pub use self::__barcode_detection::ar_barcode_detection_provider_t;
#[cfg(feature = "barcode_detection")]
pub use self::__barcode_detection::ar_barcode_detection_symbology_t;
#[cfg(all(feature = "barcode_detection", feature = "objc2"))]
pub use self::__barcode_detection::ar_barcode_detection_update_handler_function_t;
#[cfg(all(feature = "barcode_detection", feature = "block2", feature = "objc2"))]
pub use self::__barcode_detection::ar_barcode_detection_update_handler_t;
#[cfg(feature = "camera_frame_provider")]
pub use self::__camera_frame_provider::ar_camera_frame_parameters_t;
#[cfg(feature = "camera_frame_provider")]
pub use self::__camera_frame_provider::ar_camera_frame_provider_t;
#[cfg(all(feature = "camera_frame_provider", feature = "objc2"))]
pub use self::__camera_frame_provider::ar_camera_frame_sample_enumerator_function_t;
#[cfg(all(
    feature = "block2",
    feature = "camera_frame_provider",
    feature = "objc2"
))]
pub use self::__camera_frame_provider::ar_camera_frame_sample_enumerator_t;
#[cfg(feature = "camera_frame_provider")]
pub use self::__camera_frame_provider::ar_camera_frame_sample_t;
#[cfg(feature = "camera_frame_provider")]
pub use self::__camera_frame_provider::ar_camera_frame_samples_t;
#[cfg(feature = "camera_frame_provider")]
pub use self::__camera_frame_provider::ar_camera_frame_t;
#[cfg(all(feature = "camera_frame_provider", feature = "objc2"))]
pub use self::__camera_frame_provider::ar_camera_frame_update_handler_function_t;
#[cfg(all(
    feature = "block2",
    feature = "camera_frame_provider",
    feature = "objc2"
))]
pub use self::__camera_frame_provider::ar_camera_frame_update_handler_t;
#[cfg(feature = "camera_frame_provider")]
pub use self::__camera_frame_provider::ar_camera_position_t;
#[cfg(feature = "camera_frame_provider")]
pub use self::__camera_frame_provider::ar_camera_rectification_type_t;
#[cfg(feature = "camera_frame_provider")]
pub use self::__camera_frame_provider::ar_camera_type_t;
#[cfg(all(feature = "camera_frame_provider", feature = "objc2"))]
pub use self::__camera_frame_provider::ar_camera_video_format_enumerator_function_t;
#[cfg(all(
    feature = "block2",
    feature = "camera_frame_provider",
    feature = "objc2"
))]
pub use self::__camera_frame_provider::ar_camera_video_format_enumerator_t;
#[cfg(feature = "camera_frame_provider")]
pub use self::__camera_frame_provider::ar_camera_video_format_t;
#[cfg(feature = "camera_frame_provider")]
pub use self::__camera_frame_provider::ar_camera_video_formats_t;
#[cfg(all(
    feature = "anchor",
    feature = "camera_region",
    feature = "error",
    feature = "objc2"
))]
pub use self::__camera_region::ar_camera_region_add_anchor_completion_handler_function_t;
#[cfg(all(
    feature = "anchor",
    feature = "block2",
    feature = "camera_region",
    feature = "error",
    feature = "objc2"
))]
pub use self::__camera_region::ar_camera_region_add_anchor_completion_handler_t;
#[cfg(feature = "camera_region")]
pub use self::__camera_region::ar_camera_region_anchor_t;
#[cfg(all(feature = "anchor", feature = "camera_region", feature = "objc2"))]
pub use self::__camera_region::ar_camera_region_anchor_update_handler_function_t;
#[cfg(all(
    feature = "anchor",
    feature = "block2",
    feature = "camera_region",
    feature = "objc2"
))]
pub use self::__camera_region::ar_camera_region_anchor_update_handler_t;
#[cfg(all(feature = "anchor", feature = "camera_region", feature = "objc2"))]
pub use self::__camera_region::ar_camera_region_anchors_enumerator_function_t;
#[cfg(all(
    feature = "anchor",
    feature = "block2",
    feature = "camera_region",
    feature = "objc2"
))]
pub use self::__camera_region::ar_camera_region_anchors_enumerator_t;
#[cfg(feature = "camera_region")]
pub use self::__camera_region::ar_camera_region_anchors_t;
#[cfg(feature = "camera_region")]
pub use self::__camera_region::ar_camera_region_camera_enhancement_t;
#[cfg(feature = "camera_region")]
pub use self::__camera_region::ar_camera_region_configuration_t;
#[cfg(all(feature = "camera_region", feature = "error"))]
pub use self::__camera_region::ar_camera_region_error_code_t;
#[cfg(feature = "camera_region")]
pub use self::__camera_region::ar_camera_region_provider_t;
#[cfg(all(
    feature = "anchor",
    feature = "camera_region",
    feature = "error",
    feature = "objc2"
))]
pub use self::__camera_region::ar_camera_region_remove_anchor_completion_handler_function_t;
#[cfg(all(
    feature = "anchor",
    feature = "block2",
    feature = "camera_region",
    feature = "error",
    feature = "objc2"
))]
pub use self::__camera_region::ar_camera_region_remove_anchor_completion_handler_t;
#[cfg(all(feature = "camera_region", feature = "error", feature = "objc2"))]
pub use self::__camera_region::ar_camera_region_remove_anchor_with_identifier_completion_handler_function_t;
#[cfg(all(
    feature = "block2",
    feature = "camera_region",
    feature = "error",
    feature = "objc2"
))]
pub use self::__camera_region::ar_camera_region_remove_anchor_with_identifier_completion_handler_t;
#[cfg(feature = "data")]
pub use self::__data::ar_data_t;
#[cfg(feature = "data_provider")]
pub use self::__data_provider::ar_data_provider_state_t;
#[cfg(feature = "data_provider")]
pub use self::__data_provider::ar_data_provider_t;
#[cfg(all(feature = "data_provider", feature = "objc2"))]
pub use self::__data_provider::ar_data_providers_enumerator_function_t;
#[cfg(all(feature = "block2", feature = "data_provider", feature = "objc2"))]
pub use self::__data_provider::ar_data_providers_enumerator_t;
#[cfg(feature = "data_provider")]
pub use self::__data_provider::ar_data_providers_t;
#[cfg(feature = "environment_light_estimation")]
pub use self::__environment_light_estimation::ar_environment_light_estimation_configuration_t;
#[cfg(feature = "environment_light_estimation")]
pub use self::__environment_light_estimation::ar_environment_light_estimation_provider_t;
#[cfg(all(feature = "environment_light_estimation", feature = "objc2"))]
pub use self::__environment_light_estimation::ar_environment_light_estimation_update_handler_function_t;
#[cfg(all(
    feature = "block2",
    feature = "environment_light_estimation",
    feature = "objc2"
))]
pub use self::__environment_light_estimation::ar_environment_light_estimation_update_handler_t;
#[cfg(feature = "environment_light_estimation")]
pub use self::__environment_light_estimation::ar_environment_probe_anchor_t;
#[cfg(all(
    feature = "anchor",
    feature = "environment_light_estimation",
    feature = "objc2"
))]
pub use self::__environment_light_estimation::ar_environment_probe_anchors_enumerator_function_t;
#[cfg(all(
    feature = "anchor",
    feature = "block2",
    feature = "environment_light_estimation",
    feature = "objc2"
))]
pub use self::__environment_light_estimation::ar_environment_probe_anchors_enumerator_t;
#[cfg(feature = "environment_light_estimation")]
pub use self::__environment_light_estimation::ar_environment_probe_anchors_t;
#[cfg(feature = "error")]
pub use self::__error::ar_error_code_t;
#[cfg(all(feature = "error", feature = "objc2-core-foundation"))]
pub use self::__error::ar_error_domain;
#[cfg(feature = "error")]
pub use self::__error::ar_error_t;
#[cfg(feature = "hand_skeleton")]
pub use self::__hand_skeleton::ar_hand_skeleton_joint_name_t;
#[cfg(feature = "hand_skeleton")]
pub use self::__hand_skeleton::ar_hand_skeleton_t;
#[cfg(feature = "hand_tracking")]
pub use self::__hand_tracking::ar_hand_anchor_query_status_t;
#[cfg(feature = "hand_tracking")]
pub use self::__hand_tracking::ar_hand_anchor_t;
#[cfg(feature = "hand_tracking")]
pub use self::__hand_tracking::ar_hand_chirality_t;
#[cfg(feature = "hand_tracking")]
pub use self::__hand_tracking::ar_hand_fidelity_t;
#[cfg(feature = "hand_tracking")]
pub use self::__hand_tracking::ar_hand_tracking_configuration_t;
#[cfg(feature = "hand_tracking")]
pub use self::__hand_tracking::ar_hand_tracking_provider_t;
#[cfg(all(feature = "anchor", feature = "hand_tracking", feature = "objc2"))]
pub use self::__hand_tracking::ar_hand_tracking_update_handler_function_t;
#[cfg(all(
    feature = "anchor",
    feature = "block2",
    feature = "hand_tracking",
    feature = "objc2"
))]
pub use self::__hand_tracking::ar_hand_tracking_update_handler_t;
#[cfg(feature = "identifiers")]
pub use self::__identifiers::ar_identifiers_enumerator_function_t;
#[cfg(all(feature = "block2", feature = "identifiers"))]
pub use self::__identifiers::ar_identifiers_enumerator_t;
#[cfg(feature = "identifiers")]
pub use self::__identifiers::ar_identifiers_t;
#[cfg(feature = "image_tracking")]
pub use self::__image_tracking::ar_image_anchor_t;
#[cfg(all(feature = "anchor", feature = "image_tracking", feature = "objc2"))]
pub use self::__image_tracking::ar_image_anchors_enumerator_function_t;
#[cfg(all(
    feature = "anchor",
    feature = "block2",
    feature = "image_tracking",
    feature = "objc2"
))]
pub use self::__image_tracking::ar_image_anchors_enumerator_t;
#[cfg(feature = "image_tracking")]
pub use self::__image_tracking::ar_image_anchors_t;
#[cfg(feature = "image_tracking")]
pub use self::__image_tracking::ar_image_tracking_configuration_t;
#[cfg(feature = "image_tracking")]
pub use self::__image_tracking::ar_image_tracking_provider_t;
#[cfg(all(feature = "image_tracking", feature = "objc2"))]
pub use self::__image_tracking::ar_image_tracking_update_handler_function_t;
#[cfg(all(feature = "block2", feature = "image_tracking", feature = "objc2"))]
pub use self::__image_tracking::ar_image_tracking_update_handler_t;
#[cfg(feature = "image_tracking")]
pub use self::__image_tracking::ar_reference_image_t;
#[cfg(all(feature = "image_tracking", feature = "objc2"))]
pub use self::__image_tracking::ar_reference_images_enumerator_function_t;
#[cfg(all(feature = "block2", feature = "image_tracking", feature = "objc2"))]
pub use self::__image_tracking::ar_reference_images_enumerator_t;
#[cfg(feature = "image_tracking")]
pub use self::__image_tracking::ar_reference_images_t;
#[cfg(feature = "object")]
pub use self::__object::ar_release;
#[cfg(feature = "object")]
pub use self::__object::ar_retain;
#[cfg(feature = "object_tracking")]
pub use self::__object_tracking::ar_object_anchor_t;
#[cfg(all(feature = "anchor", feature = "objc2", feature = "object_tracking"))]
pub use self::__object_tracking::ar_object_anchors_enumerator_function_t;
#[cfg(all(
    feature = "anchor",
    feature = "block2",
    feature = "objc2",
    feature = "object_tracking"
))]
pub use self::__object_tracking::ar_object_anchors_enumerator_t;
#[cfg(feature = "object_tracking")]
pub use self::__object_tracking::ar_object_anchors_t;
#[cfg(feature = "object_tracking")]
pub use self::__object_tracking::ar_object_axis_aligned_bounding_box_t;
#[cfg(feature = "object_tracking")]
pub use self::__object_tracking::ar_object_tracking_configuration_t;
#[cfg(all(feature = "error", feature = "object_tracking"))]
pub use self::__object_tracking::ar_object_tracking_error_code_t;
#[cfg(feature = "object_tracking")]
pub use self::__object_tracking::ar_object_tracking_provider_t;
#[cfg(all(feature = "objc2", feature = "object_tracking"))]
pub use self::__object_tracking::ar_object_tracking_update_handler_function_t;
#[cfg(all(feature = "block2", feature = "objc2", feature = "object_tracking"))]
pub use self::__object_tracking::ar_object_tracking_update_handler_t;
#[cfg(all(
    feature = "error",
    feature = "objc2",
    feature = "objc2-core-foundation",
    feature = "object_tracking"
))]
pub use self::__object_tracking::ar_reference_object_bundle_load_completion_handler_function_t;
#[cfg(all(
    feature = "block2",
    feature = "error",
    feature = "objc2",
    feature = "objc2-core-foundation",
    feature = "object_tracking"
))]
pub use self::__object_tracking::ar_reference_object_bundle_load_completion_handler_t;
#[cfg(feature = "object_tracking")]
pub use self::__object_tracking::ar_reference_object_t;
#[cfg(all(
    feature = "error",
    feature = "objc2",
    feature = "objc2-core-foundation",
    feature = "object_tracking"
))]
pub use self::__object_tracking::ar_reference_object_url_load_completion_handler_function_t;
#[cfg(all(
    feature = "block2",
    feature = "error",
    feature = "objc2",
    feature = "objc2-core-foundation",
    feature = "object_tracking"
))]
pub use self::__object_tracking::ar_reference_object_url_load_completion_handler_t;
#[cfg(all(feature = "objc2", feature = "object_tracking"))]
pub use self::__object_tracking::ar_reference_objects_enumerator_function_t;
#[cfg(all(feature = "block2", feature = "objc2", feature = "object_tracking"))]
pub use self::__object_tracking::ar_reference_objects_enumerator_t;
#[cfg(feature = "object_tracking")]
pub use self::__object_tracking::ar_reference_objects_t;
#[cfg(feature = "plane_detection")]
pub use self::__plane_detection::ar_plane_alignment_t;
#[cfg(feature = "plane_detection")]
pub use self::__plane_detection::ar_plane_anchor_t;
#[cfg(all(feature = "anchor", feature = "objc2", feature = "plane_detection"))]
pub use self::__plane_detection::ar_plane_anchors_enumerator_function_t;
#[cfg(all(
    feature = "anchor",
    feature = "block2",
    feature = "objc2",
    feature = "plane_detection"
))]
pub use self::__plane_detection::ar_plane_anchors_enumerator_t;
#[cfg(feature = "plane_detection")]
pub use self::__plane_detection::ar_plane_anchors_t;
#[cfg(feature = "plane_detection")]
pub use self::__plane_detection::ar_plane_classification_t;
#[cfg(feature = "plane_detection")]
pub use self::__plane_detection::ar_plane_detection_configuration_t;
#[cfg(feature = "plane_detection")]
pub use self::__plane_detection::ar_plane_detection_provider_t;
#[cfg(all(feature = "objc2", feature = "plane_detection"))]
pub use self::__plane_detection::ar_plane_detection_update_handler_function_t;
#[cfg(all(feature = "block2", feature = "objc2", feature = "plane_detection"))]
pub use self::__plane_detection::ar_plane_detection_update_handler_t;
#[cfg(feature = "plane_detection")]
pub use self::__plane_detection::ar_plane_extent_t;
#[cfg(feature = "plane_detection")]
pub use self::__plane_detection::ar_plane_geometry_t;
#[cfg(feature = "room_tracking")]
pub use self::__room_tracking::ar_room_anchor_t;
#[cfg(all(feature = "anchor", feature = "objc2", feature = "room_tracking"))]
pub use self::__room_tracking::ar_room_anchors_enumerator_function_t;
#[cfg(all(
    feature = "anchor",
    feature = "block2",
    feature = "objc2",
    feature = "room_tracking"
))]
pub use self::__room_tracking::ar_room_anchors_enumerator_t;
#[cfg(feature = "room_tracking")]
pub use self::__room_tracking::ar_room_anchors_t;
#[cfg(feature = "room_tracking")]
pub use self::__room_tracking::ar_room_tracking_configuration_t;
#[cfg(feature = "room_tracking")]
pub use self::__room_tracking::ar_room_tracking_provider_t;
#[cfg(all(feature = "objc2", feature = "room_tracking"))]
pub use self::__room_tracking::ar_room_tracking_update_handler_function_t;
#[cfg(all(feature = "block2", feature = "objc2", feature = "room_tracking"))]
pub use self::__room_tracking::ar_room_tracking_update_handler_t;
#[cfg(feature = "scene_reconstruction")]
pub use self::__scene_reconstruction::ar_geometry_element_t;
#[cfg(feature = "scene_reconstruction")]
pub use self::__scene_reconstruction::ar_geometry_primitive_type_t;
#[cfg(feature = "scene_reconstruction")]
pub use self::__scene_reconstruction::ar_geometry_source_t;
#[cfg(feature = "scene_reconstruction")]
pub use self::__scene_reconstruction::ar_mesh_anchor_t;
#[cfg(all(
    feature = "anchor",
    feature = "objc2",
    feature = "scene_reconstruction"
))]
pub use self::__scene_reconstruction::ar_mesh_anchors_enumerator_function_t;
#[cfg(all(
    feature = "anchor",
    feature = "block2",
    feature = "objc2",
    feature = "scene_reconstruction"
))]
pub use self::__scene_reconstruction::ar_mesh_anchors_enumerator_t;
#[cfg(feature = "scene_reconstruction")]
pub use self::__scene_reconstruction::ar_mesh_anchors_t;
#[cfg(feature = "scene_reconstruction")]
pub use self::__scene_reconstruction::ar_mesh_classification_t;
#[cfg(all(feature = "objc2", feature = "scene_reconstruction"))]
pub use self::__scene_reconstruction::ar_mesh_geometries_enumerator_function_t;
#[cfg(all(
    feature = "block2",
    feature = "objc2",
    feature = "scene_reconstruction"
))]
pub use self::__scene_reconstruction::ar_mesh_geometries_enumerator_t;
#[cfg(feature = "scene_reconstruction")]
pub use self::__scene_reconstruction::ar_mesh_geometries_t;
#[cfg(feature = "scene_reconstruction")]
pub use self::__scene_reconstruction::ar_mesh_geometry_t;
#[cfg(feature = "scene_reconstruction")]
pub use self::__scene_reconstruction::ar_scene_reconstruction_configuration_t;
#[cfg(feature = "scene_reconstruction")]
pub use self::__scene_reconstruction::ar_scene_reconstruction_mode_t;
#[cfg(feature = "scene_reconstruction")]
pub use self::__scene_reconstruction::ar_scene_reconstruction_provider_t;
#[cfg(all(feature = "objc2", feature = "scene_reconstruction"))]
pub use self::__scene_reconstruction::ar_scene_reconstruction_update_handler_function_t;
#[cfg(all(
    feature = "block2",
    feature = "objc2",
    feature = "scene_reconstruction"
))]
pub use self::__scene_reconstruction::ar_scene_reconstruction_update_handler_t;
#[cfg(feature = "scene_reconstruction")]
pub use self::__scene_reconstruction::ar_surface_classification_t;
#[cfg(all(
    feature = "authorization",
    feature = "error",
    feature = "objc2",
    feature = "session"
))]
pub use self::__session::ar_authorization_results_handler_function_t;
#[cfg(all(
    feature = "authorization",
    feature = "block2",
    feature = "error",
    feature = "objc2",
    feature = "session"
))]
pub use self::__session::ar_authorization_results_handler_t;
#[cfg(all(feature = "authorization", feature = "objc2", feature = "session"))]
pub use self::__session::ar_authorization_update_handler_function_t;
#[cfg(all(
    feature = "authorization",
    feature = "block2",
    feature = "objc2",
    feature = "session"
))]
pub use self::__session::ar_authorization_update_handler_t;
#[cfg(feature = "session")]
pub use self::__session::ar_device_t;
#[cfg(all(
    feature = "data_provider",
    feature = "error",
    feature = "objc2",
    feature = "session"
))]
pub use self::__session::ar_session_data_provider_state_change_handler_function_t;
#[cfg(all(
    feature = "block2",
    feature = "data_provider",
    feature = "error",
    feature = "objc2",
    feature = "session"
))]
pub use self::__session::ar_session_data_provider_state_change_handler_t;
#[cfg(all(feature = "error", feature = "session"))]
pub use self::__session::ar_session_error_code_t;
#[cfg(feature = "session")]
pub use self::__session::ar_session_t;
#[cfg(feature = "shared_coordinate_space")]
pub use self::__shared_coordinate_space::ar_coordinate_space_data_t;
#[cfg(all(
    feature = "data_provider",
    feature = "dispatch2",
    feature = "identifiers",
    feature = "objc2",
    feature = "shared_coordinate_space"
))]
pub use self::__shared_coordinate_space::ar_shared_coordinate_provider_set_connected_participants_update_handler_f;
#[cfg(feature = "shared_coordinate_space")]
pub use self::__shared_coordinate_space::ar_shared_coordinate_space_configuration_t;
#[cfg(all(
    feature = "identifiers",
    feature = "objc2",
    feature = "shared_coordinate_space"
))]
pub use self::__shared_coordinate_space::ar_shared_coordinate_space_connected_participants_update_handler_function_t;
#[cfg(all(
    feature = "block2",
    feature = "identifiers",
    feature = "objc2",
    feature = "shared_coordinate_space"
))]
pub use self::__shared_coordinate_space::ar_shared_coordinate_space_connected_participants_update_handler_t;
#[cfg(feature = "shared_coordinate_space")]
pub use self::__shared_coordinate_space::ar_shared_coordinate_space_provider_t;
#[cfg(all(feature = "block2", feature = "shared_coordinate_space"))]
pub use self::__shared_coordinate_space::ar_shared_coordinate_space_sharing_status_update_handler_function_t;
#[cfg(all(feature = "block2", feature = "shared_coordinate_space"))]
pub use self::__shared_coordinate_space::ar_shared_coordinate_space_sharing_status_update_handler_t;
#[cfg(all(feature = "objc2", feature = "skeleton_joint"))]
pub use self::__skeleton_joint::ar_skeleton_joint_enumerator_function_t;
#[cfg(all(feature = "block2", feature = "objc2", feature = "skeleton_joint"))]
pub use self::__skeleton_joint::ar_skeleton_joint_enumerator_t;
#[cfg(feature = "skeleton_joint")]
pub use self::__skeleton_joint::ar_skeleton_joint_t;
#[cfg(feature = "stereo_properties")]
pub use self::__stereo_properties::ar_stereo_properties_configuration_t;
#[cfg(feature = "stereo_properties")]
pub use self::__stereo_properties::ar_stereo_properties_provider_t;
#[cfg(feature = "stereo_properties")]
pub use self::__stereo_properties::ar_viewpoint_properties_t;
#[cfg(feature = "strings_collection")]
pub use self::__strings_collection::ar_strings_enumerator_function_t;
#[cfg(all(feature = "block2", feature = "strings_collection"))]
pub use self::__strings_collection::ar_strings_enumerator_t;
#[cfg(feature = "strings_collection")]
pub use self::__strings_collection::ar_strings_t;
#[cfg(feature = "transform_correction")]
pub use self::__transform_correction::ar_transform_correction_t;
#[cfg(feature = "world_tracking")]
pub use self::__world_tracking::ar_device_anchor_query_status_t;
#[cfg(feature = "world_tracking")]
pub use self::__world_tracking::ar_device_anchor_t;
#[cfg(feature = "world_tracking")]
pub use self::__world_tracking::ar_device_anchor_tracking_state_t;
#[cfg(feature = "world_tracking")]
pub use self::__world_tracking::ar_world_anchor_sharing_availability_t;
#[cfg(feature = "world_tracking")]
pub use self::__world_tracking::ar_world_anchor_sharing_availability_update_handler_function_t;
#[cfg(all(feature = "block2", feature = "world_tracking"))]
pub use self::__world_tracking::ar_world_anchor_sharing_availability_update_handler_t;
#[cfg(feature = "world_tracking")]
pub use self::__world_tracking::ar_world_anchor_t;
#[cfg(all(feature = "anchor", feature = "objc2", feature = "world_tracking"))]
pub use self::__world_tracking::ar_world_anchors_enumerator_function_t;
#[cfg(all(
    feature = "anchor",
    feature = "block2",
    feature = "objc2",
    feature = "world_tracking"
))]
pub use self::__world_tracking::ar_world_anchors_enumerator_t;
#[cfg(feature = "world_tracking")]
pub use self::__world_tracking::ar_world_anchors_t;
#[cfg(all(
    feature = "anchor",
    feature = "error",
    feature = "objc2",
    feature = "world_tracking"
))]
pub use self::__world_tracking::ar_world_tracking_add_anchor_completion_handler_function_t;
#[cfg(all(
    feature = "anchor",
    feature = "block2",
    feature = "error",
    feature = "objc2",
    feature = "world_tracking"
))]
pub use self::__world_tracking::ar_world_tracking_add_anchor_completion_handler_t;
#[cfg(all(feature = "objc2", feature = "world_tracking"))]
pub use self::__world_tracking::ar_world_tracking_anchor_update_handler_function_t;
#[cfg(all(feature = "block2", feature = "objc2", feature = "world_tracking"))]
pub use self::__world_tracking::ar_world_tracking_anchor_update_handler_t;
#[cfg(feature = "world_tracking")]
pub use self::__world_tracking::ar_world_tracking_configuration_t;
#[cfg(all(feature = "error", feature = "world_tracking"))]
pub use self::__world_tracking::ar_world_tracking_error_code_t;
#[cfg(all(feature = "objc2", feature = "world_tracking"))]
pub use self::__world_tracking::ar_world_tracking_provider_copy_all_world_anchors_completion_function_t;
#[cfg(all(feature = "block2", feature = "objc2", feature = "world_tracking"))]
pub use self::__world_tracking::ar_world_tracking_provider_copy_all_world_anchors_completion_handler_t;
#[cfg(feature = "world_tracking")]
pub use self::__world_tracking::ar_world_tracking_provider_t;
#[cfg(all(
    feature = "block2",
    feature = "error",
    feature = "objc2",
    feature = "world_tracking"
))]
pub use self::__world_tracking::ar_world_tracking_remove_all_anchors_completion_handler_function_t;
#[cfg(all(
    feature = "block2",
    feature = "error",
    feature = "objc2",
    feature = "world_tracking"
))]
pub use self::__world_tracking::ar_world_tracking_remove_all_anchors_completion_handler_t;
#[cfg(all(
    feature = "anchor",
    feature = "error",
    feature = "objc2",
    feature = "world_tracking"
))]
pub use self::__world_tracking::ar_world_tracking_remove_anchor_completion_handler_function_t;
#[cfg(all(
    feature = "anchor",
    feature = "block2",
    feature = "error",
    feature = "objc2",
    feature = "world_tracking"
))]
pub use self::__world_tracking::ar_world_tracking_remove_anchor_completion_handler_t;
