//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::cell::UnsafeCell;
use core::ffi::*;
use core::marker::{PhantomData, PhantomPinned};
use core::ptr::NonNull;
#[cfg(feature = "dispatch2")]
use dispatch2::*;
#[cfg(feature = "objc2")]
use objc2::__framework_prelude::*;
#[cfg(feature = "objc2-core-foundation")]
use objc2_core_foundation::*;

use crate::*;

/// An axis-aligned bounding box for the extent of an object.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_object_axis_aligned_bounding_box_t?language=objc)
#[repr(C)]
pub struct ar_object_axis_aligned_bounding_box_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_object_axis_aligned_bounding_box_t {}
);

/// An object that was detected in the environment.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_object_anchor_t?language=objc)
#[repr(C)]
pub struct ar_object_anchor_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_object_anchor_t {}
);

/// A collection of object anchors.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_object_anchors_t?language=objc)
#[repr(C)]
pub struct ar_object_anchors_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_object_anchors_t {}
);

/// Defines a physical object to detect in the environment.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_reference_object_t?language=objc)
#[repr(C)]
pub struct ar_reference_object_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_reference_object_t {}
);

/// A collection of reference objects.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_reference_objects_t?language=objc)
#[repr(C)]
pub struct ar_reference_objects_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_reference_objects_t {}
);

/// Object tracking configuration.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_object_tracking_configuration_t?language=objc)
#[repr(C)]
pub struct ar_object_tracking_configuration_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_object_tracking_configuration_t {}
);

/// Object tracking provider.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_object_tracking_provider_t?language=objc)
#[repr(C)]
pub struct ar_object_tracking_provider_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_object_tracking_provider_t {}
);

impl ar_object_axis_aligned_bounding_box_t {
    /// Returns a bool value that indicates whether the two bounding boxes are equal.
    ///
    ///
    /// Parameter `bounding_box`: A bounding box to be compared.
    ///
    /// Parameter `other_bounding_box`: The other bounding box to be compared to.
    ///
    ///
    /// Returns: YES if the bounding boxes are equal, otherwise NO.
    ///
    /// # Safety
    ///
    /// - `bounding_box` must implement OS_ar_object_axis_aligned_bounding_box.
    /// - `other_bounding_box` must implement OS_ar_object_axis_aligned_bounding_box.
    #[doc(alias = "ar_object_axis_aligned_bounding_box_is_equal_to_bounding_box")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn is_equal_to_bounding_box(
        bounding_box: Option<&ar_object_axis_aligned_bounding_box_t>,
        other_bounding_box: Option<&ar_object_axis_aligned_bounding_box_t>,
    ) -> bool {
        extern "C-unwind" {
            fn ar_object_axis_aligned_bounding_box_is_equal_to_bounding_box(
                bounding_box: Option<&ar_object_axis_aligned_bounding_box_t>,
                other_bounding_box: Option<&ar_object_axis_aligned_bounding_box_t>,
            ) -> bool;
        }
        unsafe {
            ar_object_axis_aligned_bounding_box_is_equal_to_bounding_box(
                bounding_box,
                other_bounding_box,
            )
        }
    }
}

impl ar_object_anchor_t {
    /// Returns a bool value that indicates whether the two object anchors are equal.
    ///
    ///
    /// Parameter `object_anchor`: An object anchor to be compared.
    ///
    /// Parameter `other_object_anchor`: The other object anchor to be compared to.
    ///
    ///
    /// Returns: YES if the object anchors are equal, otherwise NO.
    ///
    /// # Safety
    ///
    /// - `object_anchor` must implement OS_ar_object_anchor.
    /// - `other_object_anchor` must implement OS_ar_object_anchor.
    #[doc(alias = "ar_object_anchor_is_equal_to_object_anchor")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn is_equal_to_object_anchor(
        object_anchor: Option<&ar_object_anchor_t>,
        other_object_anchor: Option<&ar_object_anchor_t>,
    ) -> bool {
        extern "C-unwind" {
            fn ar_object_anchor_is_equal_to_object_anchor(
                object_anchor: Option<&ar_object_anchor_t>,
                other_object_anchor: Option<&ar_object_anchor_t>,
            ) -> bool;
        }
        unsafe { ar_object_anchor_is_equal_to_object_anchor(object_anchor, other_object_anchor) }
    }

    /// Get bounding box for the object. Aligned with frame defining object's center and axes.
    ///
    ///
    /// Parameter `object_anchor`: The object anchor.
    ///
    /// Returns: The bounding box.
    ///
    /// # Safety
    ///
    /// `object_anchor` must implement OS_ar_object_anchor.
    #[doc(alias = "ar_object_anchor_get_bounding_box")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn bounding_box(
        object_anchor: &ar_object_anchor_t,
    ) -> Retained<ar_object_axis_aligned_bounding_box_t> {
        extern "C-unwind" {
            fn ar_object_anchor_get_bounding_box(
                object_anchor: &ar_object_anchor_t,
            ) -> *mut ar_object_axis_aligned_bounding_box_t;
        }
        let ret = unsafe { ar_object_anchor_get_bounding_box(object_anchor) };
        unsafe { Retained::retain_autoreleased(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Get the underlying tracked reference object from an object anchor.
    ///
    ///
    /// Parameter `object_anchor`: The object anchor used for getting the reference object.
    ///
    ///
    /// Returns: The `ar_reference_object_t` from the anchor.
    ///
    /// # Safety
    ///
    /// `object_anchor` must implement OS_ar_object_anchor.
    #[doc(alias = "ar_object_anchor_get_reference_object")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn reference_object(
        object_anchor: &ar_object_anchor_t,
    ) -> Retained<ar_reference_object_t> {
        extern "C-unwind" {
            fn ar_object_anchor_get_reference_object(
                object_anchor: &ar_object_anchor_t,
            ) -> *mut ar_reference_object_t;
        }
        let ret = unsafe { ar_object_anchor_get_reference_object(object_anchor) };
        unsafe { Retained::retain_autoreleased(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }
}

impl ar_object_anchors_t {
    /// Get the count of object anchors in a collection.
    ///
    ///
    /// Parameter `object_anchors`: The collection of object anchors.
    ///
    ///
    /// Returns: The number of object anchors in the collection.
    ///
    /// # Safety
    ///
    /// `object_anchors` must implement OS_ar_object_anchors.
    #[doc(alias = "ar_object_anchors_get_count")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn count(object_anchors: &ar_object_anchors_t) -> usize {
        extern "C-unwind" {
            fn ar_object_anchors_get_count(object_anchors: &ar_object_anchors_t) -> usize;
        }
        unsafe { ar_object_anchors_get_count(object_anchors) }
    }
}

impl ar_object_anchor_t {
    /// Get the identifier of an anchor.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    /// Parameter `out_identifier`: A pointer to a UUID to fill out with the anchor identifier. Must be non-null.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_object_anchor.
    #[doc(alias = "ar_object_anchor_get_identifier")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn identifier(anchor: &ar_object_anchor_t, out_identifier: &mut uuid_t) {
        extern "C-unwind" {
            fn ar_object_anchor_get_identifier(
                anchor: &ar_object_anchor_t,
                out_identifier: &mut uuid_t,
            );
        }
        unsafe { ar_object_anchor_get_identifier(anchor, out_identifier) }
    }

    /// Get the timestamp corresponding to an anchor.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    ///
    /// Returns: The timestamp associated with the anchor.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_object_anchor.
    #[doc(alias = "ar_object_anchor_get_timestamp")]
    #[cfg(all(
        feature = "anchor",
        feature = "objc2",
        feature = "objc2-core-foundation"
    ))]
    #[inline]
    pub unsafe fn timestamp(anchor: &ar_object_anchor_t) -> CFTimeInterval {
        extern "C-unwind" {
            fn ar_object_anchor_get_timestamp(anchor: &ar_object_anchor_t) -> CFTimeInterval;
        }
        unsafe { ar_object_anchor_get_timestamp(anchor) }
    }

    /// Determine whether an anchor is tracked.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    ///
    /// Returns: `true` if the anchor is tracked, `false` otherwise.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_object_anchor.
    #[doc(alias = "ar_object_anchor_is_tracked")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn is_tracked(anchor: &ar_object_anchor_t) -> bool {
        extern "C-unwind" {
            fn ar_object_anchor_is_tracked(anchor: &ar_object_anchor_t) -> bool;
        }
        unsafe { ar_object_anchor_is_tracked(anchor) }
    }
}

/// Handler for enumerating a collection of object anchors.
///
///
/// Parameter `object_anchor`: The object anchor.
///
///
/// Returns: `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_object_anchors_enumerator_t?language=objc)
#[cfg(all(feature = "anchor", feature = "block2", feature = "objc2"))]
pub type ar_object_anchors_enumerator_t =
    block2::Block<'static, fn(NonNull<ar_object_anchor_t>) -> bool>;

impl ar_object_anchors_t {
    /// Enumerate a collection of object anchors.
    ///
    ///
    /// Parameter `object_anchors`: The collection of object anchors.
    ///
    /// Parameter `object_anchors_enumerator`: The enumerator handler.
    ///
    /// # Safety
    ///
    /// `object_anchors` must implement OS_ar_object_anchors.
    #[doc(alias = "ar_object_anchors_enumerate_anchors")]
    #[cfg(all(feature = "anchor", feature = "block2", feature = "objc2"))]
    #[inline]
    pub unsafe fn enumerate_anchors(
        object_anchors: &ar_object_anchors_t,
        object_anchors_enumerator: &ar_object_anchors_enumerator_t,
    ) {
        extern "C-unwind" {
            fn ar_object_anchors_enumerate_anchors(
                object_anchors: &ar_object_anchors_t,
                object_anchors_enumerator: &ar_object_anchors_enumerator_t,
            );
        }
        unsafe { ar_object_anchors_enumerate_anchors(object_anchors, object_anchors_enumerator) }
    }
}

/// Function for enumerating a collection of object anchors.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `object_anchor`: The object anchor.
///
///
/// Returns: `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_object_anchors_enumerator_function_t?language=objc)
#[cfg(all(feature = "anchor", feature = "objc2"))]
pub type ar_object_anchors_enumerator_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &ar_object_anchor_t) -> bool;

impl ar_object_anchors_t {
    /// Enumerate a collection of object anchors.
    ///
    ///
    /// Parameter `object_anchors`: The collection of object anchors.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `object_anchors_enumerator_function`: The enumerator function.
    ///
    /// # Safety
    ///
    /// - `object_anchors` must implement OS_ar_object_anchors.
    /// - `context` must be a valid pointer or null.
    /// - `object_anchors_enumerator_function` must be implemented correctly.
    #[doc(alias = "ar_object_anchors_enumerate_anchors_f")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn enumerate_anchors_f(
        object_anchors: &ar_object_anchors_t,
        context: *mut c_void,
        object_anchors_enumerator_function: ar_object_anchors_enumerator_function_t,
    ) {
        extern "C-unwind" {
            fn ar_object_anchors_enumerate_anchors_f(
                object_anchors: &ar_object_anchors_t,
                context: *mut c_void,
                object_anchors_enumerator_function: ar_object_anchors_enumerator_function_t,
            );
        }
        unsafe {
            ar_object_anchors_enumerate_anchors_f(
                object_anchors,
                context,
                object_anchors_enumerator_function,
            )
        }
    }
}

impl ar_reference_object_t {
    /// Returns a bool value that indicates whether the two reference objects are equal.
    ///
    ///
    /// Parameter `reference_object`: A reference object to be compared.
    ///
    /// Parameter `other_reference_object`: The other reference object to be compared to.
    ///
    ///
    /// Returns: YES if the reference objects are equal, otherwise NO.
    ///
    /// # Safety
    ///
    /// - `reference_object` must implement OS_ar_reference_object.
    /// - `other_reference_object` must implement OS_ar_reference_object.
    #[doc(alias = "ar_reference_object_is_equal_to_reference_object")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn is_equal_to_reference_object(
        reference_object: Option<&ar_reference_object_t>,
        other_reference_object: Option<&ar_reference_object_t>,
    ) -> bool {
        extern "C-unwind" {
            fn ar_reference_object_is_equal_to_reference_object(
                reference_object: Option<&ar_reference_object_t>,
                other_reference_object: Option<&ar_reference_object_t>,
            ) -> bool;
        }
        unsafe {
            ar_reference_object_is_equal_to_reference_object(
                reference_object,
                other_reference_object,
            )
        }
    }

    /// Get identifier for the reference object.
    ///
    /// Parameter `reference_object`: Reference object.
    ///
    /// Parameter `out_uuid`: Object to fill with UUID.
    ///
    /// # Safety
    ///
    /// `reference_object` must implement OS_ar_reference_object.
    #[doc(alias = "ar_reference_object_get_identifier")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn identifier(reference_object: &ar_reference_object_t, out_uuid: &mut uuid_t) {
        extern "C-unwind" {
            fn ar_reference_object_get_identifier(
                reference_object: &ar_reference_object_t,
                out_uuid: &mut uuid_t,
            );
        }
        unsafe { ar_reference_object_get_identifier(reference_object, out_uuid) }
    }

    /// Get the input file path used to load the reference object.
    ///
    /// Parameter `reference_object`: Reference object.
    ///
    /// Note: The returned value will have the same lifetime as the `ar_reference_object_t`.
    ///
    /// Returns: The input file path.
    ///
    /// # Safety
    ///
    /// `reference_object` must implement OS_ar_reference_object.
    #[doc(alias = "ar_reference_object_get_input_file_path")]
    #[cfg(all(feature = "objc2", feature = "objc2-core-foundation"))]
    #[inline]
    pub unsafe fn input_file_path(
        reference_object: &ar_reference_object_t,
    ) -> Option<CFRetained<CFURL>> {
        extern "C-unwind" {
            fn ar_reference_object_get_input_file_path(
                reference_object: &ar_reference_object_t,
            ) -> Option<NonNull<CFURL>>;
        }
        let ret = unsafe { ar_reference_object_get_input_file_path(reference_object) };
        ret.map(|ret| unsafe { CFRetained::retain(ret) })
    }

    /// Get path to a copy of the USDZ file for the object, if the object has one.
    ///
    /// Parameter `reference_object`: Reference object.
    ///
    /// Note: The returned value will have the same lifetime as the `ar_reference_object_t`.
    ///
    /// Returns: The path to the USDZ file.
    ///
    /// # Safety
    ///
    /// `reference_object` must implement OS_ar_reference_object.
    #[doc(alias = "ar_reference_object_get_usdz_file_path")]
    #[cfg(all(feature = "objc2", feature = "objc2-core-foundation"))]
    #[inline]
    pub unsafe fn usdz_file_path(
        reference_object: &ar_reference_object_t,
    ) -> Option<CFRetained<CFURL>> {
        extern "C-unwind" {
            fn ar_reference_object_get_usdz_file_path(
                reference_object: &ar_reference_object_t,
            ) -> Option<NonNull<CFURL>>;
        }
        let ret = unsafe { ar_reference_object_get_usdz_file_path(reference_object) };
        ret.map(|ret| unsafe { CFRetained::retain(ret) })
    }

    /// Get a reference object's name.
    ///
    ///
    /// Parameter `reference_object`: The reference object.
    ///
    ///
    /// Note: The returned value will have the same lifetime as the input `ar_reference_object_t`.
    ///
    /// Returns: The name of the reference object, or NULL if no name is set.
    ///
    /// # Safety
    ///
    /// `reference_object` must implement OS_ar_reference_object.
    #[doc(alias = "ar_reference_object_get_name")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn name(reference_object: &ar_reference_object_t) -> NonNull<c_char> {
        extern "C-unwind" {
            fn ar_reference_object_get_name(
                reference_object: &ar_reference_object_t,
            ) -> Option<NonNull<c_char>>;
        }
        let ret = unsafe { ar_reference_object_get_name(reference_object) };
        ret.expect("function was marked as returning non-null, but actually returned NULL")
    }
}

/// Handler triggered when a request to load a reference object from a URL has completed.
///
///
/// Parameter `url`: URL for the reference object that was being loaded.
///
/// Parameter `success`: `true` if loading succeeded, `false` otherwise.
///
/// Parameter `error`: The error that occurred, if any. The returned error supports ARC. In non-ARC files, use `ar_release()` to release the error.
///
/// Parameter `reference_object`: An instance of `ar_reference_object_t` (NULL if loading failed). The returned object supports ARC. In non-ARC files, use
/// `ar_release()` to release it.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_reference_object_url_load_completion_handler_t?language=objc)
#[cfg(all(
    feature = "block2",
    feature = "error",
    feature = "objc2",
    feature = "objc2-core-foundation"
))]
pub type ar_reference_object_url_load_completion_handler_t =
    block2::Block<'static, fn(NonNull<CFURL>, bool, *mut ar_error_t, *mut ar_reference_object_t)>;

impl ar_reference_object_t {
    /// Load a reference object from a URL.
    ///
    ///
    /// Parameter `url`: URL pointing to the reference object to load on the file system.
    ///
    /// Parameter `completion_handler`: Handler triggered after the request to load an object completes.
    #[doc(alias = "ar_reference_object_load_from_url")]
    #[cfg(all(
        feature = "block2",
        feature = "error",
        feature = "objc2",
        feature = "objc2-core-foundation"
    ))]
    #[inline]
    pub unsafe fn load_from_url(
        url: &CFURL,
        completion_handler: &ar_reference_object_url_load_completion_handler_t,
    ) {
        extern "C-unwind" {
            fn ar_reference_object_load_from_url(
                url: &CFURL,
                completion_handler: &ar_reference_object_url_load_completion_handler_t,
            );
        }
        unsafe { ar_reference_object_load_from_url(url, completion_handler) }
    }
}

/// Function called when a request to load a reference object from a URL has completed.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `url`: URL for the reference object that was being loaded.
///
/// Parameter `success`: `true` if loading succeeded, `false` otherwise.
///
/// Parameter `error`: The error that occurred, if any. The returned error supports ARC. In non-ARC files, use `ar_release()` to release the error.
///
/// Parameter `reference_object`: An instance of `ar_reference_object_t` (NULL if loading failed). The returned object supports ARC. In non-ARC files, use
/// `ar_release()` to release it.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_reference_object_url_load_completion_handler_function_t?language=objc)
#[cfg(all(
    feature = "error",
    feature = "objc2",
    feature = "objc2-core-foundation"
))]
pub type ar_reference_object_url_load_completion_handler_function_t =
    unsafe extern "C-unwind" fn(
        *mut c_void,
        &CFURL,
        bool,
        Option<&ar_error_t>,
        Option<&ar_reference_object_t>,
    );

impl ar_reference_object_t {
    /// Load a reference object from a URL.
    ///
    ///
    /// Parameter `url`: URL pointing to the reference object to load on the file system.
    ///
    /// Parameter `completion_handler_function`: The function to be called after the request to load an object completes.
    ///
    /// # Safety
    ///
    /// - `context` must be a valid pointer or null.
    /// - `completion_handler_function` must be implemented correctly.
    #[doc(alias = "ar_reference_object_load_from_url_f")]
    #[cfg(all(
        feature = "error",
        feature = "objc2",
        feature = "objc2-core-foundation"
    ))]
    #[inline]
    pub unsafe fn load_from_url_f(
        url: &CFURL,
        context: *mut c_void,
        completion_handler_function: ar_reference_object_url_load_completion_handler_function_t,
    ) {
        extern "C-unwind" {
            fn ar_reference_object_load_from_url_f(
                url: &CFURL,
                context: *mut c_void,
                completion_handler_function: ar_reference_object_url_load_completion_handler_function_t,
            );
        }
        unsafe { ar_reference_object_load_from_url_f(url, context, completion_handler_function) }
    }
}

/// Handler triggered when a request to load a reference object from a bundle has completed.
///
///
/// Parameter `name`: Name of reference object that was being loaded from bundle.
///
/// Parameter `bundle`: Bundle used for loading the reference object.
///
/// Parameter `success`: `true` if loading succeeded, `false` otherwise.
///
/// Parameter `error`: The error that occurred, if any. The returned error supports ARC. In non-ARC files, use `ar_release()` to release the error.
///
/// Parameter `reference_object`: An instance of `ar_reference_object_t` (NULL if loading failed). The returned object supports ARC. In non-ARC files, use
/// `ar_release()` to release it.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_reference_object_bundle_load_completion_handler_t?language=objc)
#[cfg(all(
    feature = "block2",
    feature = "error",
    feature = "objc2",
    feature = "objc2-core-foundation"
))]
pub type ar_reference_object_bundle_load_completion_handler_t = block2::Block<
    'static,
    fn(NonNull<c_char>, *mut CFBundle, bool, *mut ar_error_t, *mut ar_reference_object_t),
>;

impl ar_reference_object_t {
    /// Load a reference object from a bundle.
    ///
    ///
    /// Parameter `name`: Name of reference object to load from bundle.
    ///
    /// Parameter `bundle`: Bundle used for loading the reference object. The main bundle is used if NULL.
    ///
    /// Parameter `completion_handler`: Handler triggered after the request to load an object completes.
    ///
    /// # Safety
    ///
    /// `name` must be a valid pointer.
    #[doc(alias = "ar_reference_object_load_with_name")]
    #[cfg(all(
        feature = "block2",
        feature = "error",
        feature = "objc2",
        feature = "objc2-core-foundation"
    ))]
    #[inline]
    pub unsafe fn load_with_name(
        name: NonNull<c_char>,
        bundle: Option<&CFBundle>,
        completion_handler: &ar_reference_object_bundle_load_completion_handler_t,
    ) {
        extern "C-unwind" {
            fn ar_reference_object_load_with_name(
                name: NonNull<c_char>,
                bundle: Option<&CFBundle>,
                completion_handler: &ar_reference_object_bundle_load_completion_handler_t,
            );
        }
        unsafe { ar_reference_object_load_with_name(name, bundle, completion_handler) }
    }
}

/// Function called when a request to load a reference object from a bundle has completed.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `name`: Name of reference object that was being loaded from bundle.
///
/// Parameter `bundle`: Bundle used for loading the reference object.
///
/// Parameter `success`: `true` if loading succeeded, `false` otherwise.
///
/// Parameter `error`: The error that occurred, if any. The returned error supports ARC. In non-ARC files, use `ar_release()` to release the error.
///
/// Parameter `reference_object`: An instance of `ar_reference_object_t` (NULL if loading failed). The returned object supports ARC. In non-ARC files, use
/// `ar_release()` to release it.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_reference_object_bundle_load_completion_handler_function_t?language=objc)
#[cfg(all(
    feature = "error",
    feature = "objc2",
    feature = "objc2-core-foundation"
))]
pub type ar_reference_object_bundle_load_completion_handler_function_t =
    unsafe extern "C-unwind" fn(
        *mut c_void,
        NonNull<c_char>,
        Option<&CFBundle>,
        bool,
        Option<&ar_error_t>,
        Option<&ar_reference_object_t>,
    );

impl ar_reference_object_t {
    /// Load a reference object from a bundle.
    ///
    ///
    /// Parameter `name`: Name of reference object to load from bundle.
    ///
    /// Parameter `bundle`: Bundle used for loading the reference object. The main bundle is used if NULL.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `completion_handler_function`: The function to be called after the request to load an object completes.
    ///
    /// # Safety
    ///
    /// - `name` must be a valid pointer.
    /// - `context` must be a valid pointer or null.
    /// - `completion_handler_function` must be implemented correctly.
    #[doc(alias = "ar_reference_object_load_with_name_f")]
    #[cfg(all(
        feature = "error",
        feature = "objc2",
        feature = "objc2-core-foundation"
    ))]
    #[inline]
    pub unsafe fn load_with_name_f(
        name: NonNull<c_char>,
        bundle: Option<&CFBundle>,
        context: *mut c_void,
        completion_handler_function: ar_reference_object_bundle_load_completion_handler_function_t,
    ) {
        extern "C-unwind" {
            fn ar_reference_object_load_with_name_f(
                name: NonNull<c_char>,
                bundle: Option<&CFBundle>,
                context: *mut c_void,
                completion_handler_function: ar_reference_object_bundle_load_completion_handler_function_t,
            );
        }
        unsafe {
            ar_reference_object_load_with_name_f(name, bundle, context, completion_handler_function)
        }
    }
}

impl ar_reference_objects_t {
    /// Create an empty collection of reference objects.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_reference_objects_t`.
    #[doc(alias = "ar_reference_objects_create")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn new() -> Retained<ar_reference_objects_t> {
        extern "C-unwind" {
            fn ar_reference_objects_create() -> *mut ar_reference_objects_t;
        }
        let ret = unsafe { ar_reference_objects_create() };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Add a reference object to a collection.
    ///
    ///
    /// The object must be unique. A duplicate of any existing object in the collection will not be added.
    ///
    ///
    /// Parameter `reference_objects`: The collection of reference objects to expand.
    ///
    /// Parameter `object_to_add`: The reference object to add.
    ///
    /// # Safety
    ///
    /// - `reference_objects` must implement OS_ar_reference_objects.
    /// - `object_to_add` must implement OS_ar_reference_object.
    #[doc(alias = "ar_reference_objects_add_object")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn add_object(
        reference_objects: &ar_reference_objects_t,
        object_to_add: &ar_reference_object_t,
    ) {
        extern "C-unwind" {
            fn ar_reference_objects_add_object(
                reference_objects: &ar_reference_objects_t,
                object_to_add: &ar_reference_object_t,
            );
        }
        unsafe { ar_reference_objects_add_object(reference_objects, object_to_add) }
    }

    /// Add reference objects to a collection.
    ///
    ///
    /// The objects must be unique. Duplicates of any existing object in the collection will not be added.
    ///
    ///
    /// Parameter `reference_objects`: The collection of reference objects to expand.
    ///
    /// Parameter `objects_to_add`: The collection of reference objects to add.
    ///
    /// # Safety
    ///
    /// - `reference_objects` must implement OS_ar_reference_objects.
    /// - `objects_to_add` must implement OS_ar_reference_objects.
    #[doc(alias = "ar_reference_objects_add_objects")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn add_objects(
        reference_objects: &ar_reference_objects_t,
        objects_to_add: &ar_reference_objects_t,
    ) {
        extern "C-unwind" {
            fn ar_reference_objects_add_objects(
                reference_objects: &ar_reference_objects_t,
                objects_to_add: &ar_reference_objects_t,
            );
        }
        unsafe { ar_reference_objects_add_objects(reference_objects, objects_to_add) }
    }

    /// Get the count of reference objects in the collection.
    ///
    ///
    /// Parameter `reference_objects`: The collection of reference objects.
    ///
    ///
    /// Returns: The number of reference objects in the collection.
    ///
    /// # Safety
    ///
    /// `reference_objects` must implement OS_ar_reference_objects.
    #[doc(alias = "ar_reference_objects_get_count")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn count(reference_objects: &ar_reference_objects_t) -> usize {
        extern "C-unwind" {
            fn ar_reference_objects_get_count(reference_objects: &ar_reference_objects_t) -> usize;
        }
        unsafe { ar_reference_objects_get_count(reference_objects) }
    }
}

/// Handler for enumerating a collection of reference objects.
///
///
/// Parameter `reference_object`: The reference object.
///
///
/// Returns: `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_reference_objects_enumerator_t?language=objc)
#[cfg(all(feature = "block2", feature = "objc2"))]
pub type ar_reference_objects_enumerator_t =
    block2::Block<'static, fn(NonNull<ar_reference_object_t>) -> bool>;

impl ar_reference_objects_t {
    /// Enumerate a collection of reference objects.
    ///
    ///
    /// Parameter `reference_objects`: The collection of reference objects.
    ///
    /// Parameter `reference_objects_enumerator`: The enumerator handler.
    ///
    /// # Safety
    ///
    /// `reference_objects` must implement OS_ar_reference_objects.
    #[doc(alias = "ar_reference_objects_enumerate_objects")]
    #[cfg(all(feature = "block2", feature = "objc2"))]
    #[inline]
    pub unsafe fn enumerate_objects(
        reference_objects: &ar_reference_objects_t,
        reference_objects_enumerator: &ar_reference_objects_enumerator_t,
    ) {
        extern "C-unwind" {
            fn ar_reference_objects_enumerate_objects(
                reference_objects: &ar_reference_objects_t,
                reference_objects_enumerator: &ar_reference_objects_enumerator_t,
            );
        }
        unsafe {
            ar_reference_objects_enumerate_objects(reference_objects, reference_objects_enumerator)
        }
    }
}

/// Function for enumerating a collection of reference objects.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `reference_object`: The reference object.
///
///
/// Returns: `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_reference_objects_enumerator_function_t?language=objc)
#[cfg(feature = "objc2")]
pub type ar_reference_objects_enumerator_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &ar_reference_object_t) -> bool;

impl ar_reference_objects_t {
    /// Enumerate a collection of reference objects.
    ///
    ///
    /// Parameter `reference_objects`: The collection of reference objects.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `reference_objects_enumerator_function`: The enumerator function.
    ///
    /// # Safety
    ///
    /// - `reference_objects` must implement OS_ar_reference_objects.
    /// - `context` must be a valid pointer or null.
    /// - `reference_objects_enumerator_function` must be implemented correctly.
    #[doc(alias = "ar_reference_objects_enumerate_objects_f")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn enumerate_objects_f(
        reference_objects: &ar_reference_objects_t,
        context: *mut c_void,
        reference_objects_enumerator_function: ar_reference_objects_enumerator_function_t,
    ) {
        extern "C-unwind" {
            fn ar_reference_objects_enumerate_objects_f(
                reference_objects: &ar_reference_objects_t,
                context: *mut c_void,
                reference_objects_enumerator_function: ar_reference_objects_enumerator_function_t,
            );
        }
        unsafe {
            ar_reference_objects_enumerate_objects_f(
                reference_objects,
                context,
                reference_objects_enumerator_function,
            )
        }
    }
}

impl ar_object_tracking_configuration_t {
    /// Create an object tracking configuration.
    ///
    ///
    /// Note: Default values are set for configuration parameters as follows:
    /// - `maximum_trackable_instances`: 10
    /// - `maximum_instances_per_reference_object`: 1
    /// - `detection_rate`: 2 Hz
    /// - `stationary_object_tracking_rate`: 5 Hz
    /// - `moving_object_tracking_rate`: 5 Hz
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_object_tracking_configuration_t`.
    #[doc(alias = "ar_object_tracking_configuration_create")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn new() -> Retained<ar_object_tracking_configuration_t> {
        extern "C-unwind" {
            fn ar_object_tracking_configuration_create() -> *mut ar_object_tracking_configuration_t;
        }
        let ret = unsafe { ar_object_tracking_configuration_create() };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Add reference objects to the set of objects to be tracked. Object tracking will run without any reference objects, but will detect nothing.
    ///
    ///
    /// Parameter `object_tracking_configuration`: The configuration for object tracking.
    ///
    /// Parameter `reference_objects`: The reference objects to add.
    ///
    /// # Safety
    ///
    /// - `object_tracking_configuration` must implement OS_ar_object_tracking_configuration.
    /// - `reference_objects` must implement OS_ar_reference_objects.
    #[doc(alias = "ar_object_tracking_configuration_add_reference_objects")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn add_reference_objects(
        object_tracking_configuration: &ar_object_tracking_configuration_t,
        reference_objects: &ar_reference_objects_t,
    ) {
        extern "C-unwind" {
            fn ar_object_tracking_configuration_add_reference_objects(
                object_tracking_configuration: &ar_object_tracking_configuration_t,
                reference_objects: &ar_reference_objects_t,
            );
        }
        unsafe {
            ar_object_tracking_configuration_add_reference_objects(
                object_tracking_configuration,
                reference_objects,
            )
        }
    }

    /// Set the total number of instances of reference objects that can be tracked at one time.
    ///
    /// An enterprise license is required to modify the tracking configuration, and will be otherwise be a no-op.
    /// The app must include the following entitlement:
    /// com.apple.developer.arkit.object-tracking-parameter-adjustment.allow
    ///
    ///
    /// Parameter `object_tracking_configuration`: The object tracking configuration.
    ///
    /// Parameter `maximum_trackable_instances`: The number to set.
    ///
    /// # Safety
    ///
    /// `object_tracking_configuration` must implement OS_ar_object_tracking_configuration.
    #[doc(alias = "ar_object_tracking_configuration_set_maximum_trackable_instances")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn set_maximum_trackable_instances(
        object_tracking_configuration: &ar_object_tracking_configuration_t,
        maximum_trackable_instances: c_int,
    ) {
        extern "C-unwind" {
            fn ar_object_tracking_configuration_set_maximum_trackable_instances(
                object_tracking_configuration: &ar_object_tracking_configuration_t,
                maximum_trackable_instances: c_int,
            );
        }
        unsafe {
            ar_object_tracking_configuration_set_maximum_trackable_instances(
                object_tracking_configuration,
                maximum_trackable_instances,
            )
        }
    }

    /// Get the number to be configured for the maximum number of reference object instances to track.
    ///
    /// Parameter `object_tracking_configuration`: The object tracking configuration.
    ///
    /// Returns: The configured number.
    ///
    /// # Safety
    ///
    /// `object_tracking_configuration` must implement OS_ar_object_tracking_configuration.
    #[doc(alias = "ar_object_tracking_configuration_get_maximum_trackable_instances")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn maximum_trackable_instances(
        object_tracking_configuration: &ar_object_tracking_configuration_t,
    ) -> c_int {
        extern "C-unwind" {
            fn ar_object_tracking_configuration_get_maximum_trackable_instances(
                object_tracking_configuration: &ar_object_tracking_configuration_t,
            ) -> c_int;
        }
        unsafe {
            ar_object_tracking_configuration_get_maximum_trackable_instances(
                object_tracking_configuration,
            )
        }
    }

    /// Set the maximum number of instances of any one reference object type that can be tracked.
    ///
    /// An enterprise license is required to modify the tracking configuration, and will be otherwise be a no-op.
    /// The app must include the following entitlement:
    /// com.apple.developer.arkit.object-tracking-parameter-adjustment.allow
    ///
    ///
    /// Parameter `object_tracking_configuration`: The object tracking configuration.
    ///
    /// Parameter `maximum_instances_per_reference_object`: The number to set.
    ///
    /// # Safety
    ///
    /// `object_tracking_configuration` must implement OS_ar_object_tracking_configuration.
    #[doc(alias = "ar_object_tracking_configuration_set_maximum_instances_per_reference_object")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn set_maximum_instances_per_reference_object(
        object_tracking_configuration: &ar_object_tracking_configuration_t,
        maximum_instances_per_reference_object: c_int,
    ) {
        extern "C-unwind" {
            fn ar_object_tracking_configuration_set_maximum_instances_per_reference_object(
                object_tracking_configuration: &ar_object_tracking_configuration_t,
                maximum_instances_per_reference_object: c_int,
            );
        }
        unsafe {
            ar_object_tracking_configuration_set_maximum_instances_per_reference_object(
                object_tracking_configuration,
                maximum_instances_per_reference_object,
            )
        }
    }

    /// Get the number to be configured for the maximum number of instances of each reference object type to track.
    ///
    /// Parameter `object_tracking_configuration`: The object tracking configuration.
    ///
    /// Returns: The configured number.
    ///
    /// # Safety
    ///
    /// `object_tracking_configuration` must implement OS_ar_object_tracking_configuration.
    #[doc(alias = "ar_object_tracking_configuration_get_maximum_instances_per_reference_object")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn maximum_instances_per_reference_object(
        object_tracking_configuration: &ar_object_tracking_configuration_t,
    ) -> c_int {
        extern "C-unwind" {
            fn ar_object_tracking_configuration_get_maximum_instances_per_reference_object(
                object_tracking_configuration: &ar_object_tracking_configuration_t,
            ) -> c_int;
        }
        unsafe {
            ar_object_tracking_configuration_get_maximum_instances_per_reference_object(
                object_tracking_configuration,
            )
        }
    }

    /// Set the frequency at which object detection runs until it starts to track an object.
    ///
    /// An enterprise license is required to modify the tracking configuration, and will be otherwise be a no-op.
    /// The app must include the following entitlement:
    /// com.apple.developer.arkit.object-tracking-parameter-adjustment.allow.
    ///
    ///
    /// Parameter `object_tracking_configuration`: The object tracking configuration.
    ///
    /// Parameter `detection_rate`: The frequency to set, in Hz. Clamped between 0 and 30 Hz.
    ///
    /// # Safety
    ///
    /// `object_tracking_configuration` must implement OS_ar_object_tracking_configuration.
    #[doc(alias = "ar_object_tracking_configuration_set_detection_rate")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn set_detection_rate(
        object_tracking_configuration: &ar_object_tracking_configuration_t,
        detection_rate: c_float,
    ) {
        extern "C-unwind" {
            fn ar_object_tracking_configuration_set_detection_rate(
                object_tracking_configuration: &ar_object_tracking_configuration_t,
                detection_rate: c_float,
            );
        }
        unsafe {
            ar_object_tracking_configuration_set_detection_rate(
                object_tracking_configuration,
                detection_rate,
            )
        }
    }

    /// Get the frequency to be configured for running object detection.
    ///
    /// Parameter `object_tracking_configuration`: The object tracking configuration.
    ///
    /// Returns: The frequency, in Hz.
    ///
    /// # Safety
    ///
    /// `object_tracking_configuration` must implement OS_ar_object_tracking_configuration.
    #[doc(alias = "ar_object_tracking_configuration_get_detection_rate")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn detection_rate(
        object_tracking_configuration: &ar_object_tracking_configuration_t,
    ) -> c_float {
        extern "C-unwind" {
            fn ar_object_tracking_configuration_get_detection_rate(
                object_tracking_configuration: &ar_object_tracking_configuration_t,
            ) -> c_float;
        }
        unsafe {
            ar_object_tracking_configuration_get_detection_rate(object_tracking_configuration)
        }
    }

    /// Set the frequency at which object tracking runs for a stationary object that is detected.
    ///
    /// An enterprise license is required to modify the tracking configuration, and will be otherwise be a no-op.
    /// The app must include the following entitlement:
    /// com.apple.developer.arkit.object-tracking-parameter-adjustment.allow
    ///
    ///
    /// Parameter `object_tracking_configuration`: The object tracking configuration.
    ///
    /// Parameter `stationary_object_tracking_rate`: The frequency to set, in Hz. Clamped between 0 and 30 Hz.
    ///
    /// # Safety
    ///
    /// `object_tracking_configuration` must implement OS_ar_object_tracking_configuration.
    #[doc(alias = "ar_object_tracking_configuration_set_stationary_object_tracking_rate")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn set_stationary_object_tracking_rate(
        object_tracking_configuration: &ar_object_tracking_configuration_t,
        stationary_object_tracking_rate: c_float,
    ) {
        extern "C-unwind" {
            fn ar_object_tracking_configuration_set_stationary_object_tracking_rate(
                object_tracking_configuration: &ar_object_tracking_configuration_t,
                stationary_object_tracking_rate: c_float,
            );
        }
        unsafe {
            ar_object_tracking_configuration_set_stationary_object_tracking_rate(
                object_tracking_configuration,
                stationary_object_tracking_rate,
            )
        }
    }

    /// Get the frequency to be configured for object tracking to run for a stationary object.
    ///
    /// Parameter `object_tracking_configuration`: The object tracking configuration.
    ///
    /// Returns: The frequency, in Hz.
    ///
    /// # Safety
    ///
    /// `object_tracking_configuration` must implement OS_ar_object_tracking_configuration.
    #[doc(alias = "ar_object_tracking_configuration_get_stationary_object_tracking_rate")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn stationary_object_tracking_rate(
        object_tracking_configuration: &ar_object_tracking_configuration_t,
    ) -> c_float {
        extern "C-unwind" {
            fn ar_object_tracking_configuration_get_stationary_object_tracking_rate(
                object_tracking_configuration: &ar_object_tracking_configuration_t,
            ) -> c_float;
        }
        unsafe {
            ar_object_tracking_configuration_get_stationary_object_tracking_rate(
                object_tracking_configuration,
            )
        }
    }

    /// Set the frequency at which object tracking runs for a moving object that is detected.
    ///
    /// An enterprise license is required to modify the tracking configuration, and will be otherwise be a no-op.
    /// The app must include the following entitlement:
    /// com.apple.developer.arkit.object-tracking-parameter-adjustment.allow.
    ///
    ///
    /// Parameter `object_tracking_configuration`: The object tracking configuration.
    ///
    /// Parameter `moving_object_tracking_rate`: The frequency to set, in Hz. Clamped between 0 and 30 Hz.
    ///
    /// # Safety
    ///
    /// `object_tracking_configuration` must implement OS_ar_object_tracking_configuration.
    #[doc(alias = "ar_object_tracking_configuration_set_moving_object_tracking_rate")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn set_moving_object_tracking_rate(
        object_tracking_configuration: &ar_object_tracking_configuration_t,
        moving_object_tracking_rate: c_float,
    ) {
        extern "C-unwind" {
            fn ar_object_tracking_configuration_set_moving_object_tracking_rate(
                object_tracking_configuration: &ar_object_tracking_configuration_t,
                moving_object_tracking_rate: c_float,
            );
        }
        unsafe {
            ar_object_tracking_configuration_set_moving_object_tracking_rate(
                object_tracking_configuration,
                moving_object_tracking_rate,
            )
        }
    }

    /// Get the frequency to be configured for object tracking to run for a moving object.
    ///
    /// Parameter `object_tracking_configuration`: The object tracking configuration.
    ///
    /// Returns: The frequency, in Hz.
    ///
    /// # Safety
    ///
    /// `object_tracking_configuration` must implement OS_ar_object_tracking_configuration.
    #[doc(alias = "ar_object_tracking_configuration_get_moving_object_tracking_rate")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn moving_object_tracking_rate(
        object_tracking_configuration: &ar_object_tracking_configuration_t,
    ) -> c_float {
        extern "C-unwind" {
            fn ar_object_tracking_configuration_get_moving_object_tracking_rate(
                object_tracking_configuration: &ar_object_tracking_configuration_t,
            ) -> c_float;
        }
        unsafe {
            ar_object_tracking_configuration_get_moving_object_tracking_rate(
                object_tracking_configuration,
            )
        }
    }
}

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_object_tracking_error_code_t?language=objc)
#[cfg(feature = "error")]
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ar_object_tracking_error_code_t(pub ar_error_code_t);
#[cfg(feature = "error")]
impl ar_object_tracking_error_code_t {
    /// Error code indicating that a reference object failed to load.
    #[doc(alias = "ar_object_tracking_error_code_reference_object_loading_failed")]
    pub const reference_object_loading_failed: Self = Self(1101);
}

#[cfg(all(feature = "error", feature = "objc2"))]
unsafe impl Encode for ar_object_tracking_error_code_t {
    const ENCODING: Encoding = ar_error_code_t::ENCODING;
}

#[cfg(all(feature = "error", feature = "objc2"))]
unsafe impl RefEncode for ar_object_tracking_error_code_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

impl ar_object_tracking_provider_t {
    /// Create an object tracking provider.
    ///
    ///
    /// Parameter `object_tracking_configuration`: The configuration for object tracking.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_object_tracking_provider_t`.
    ///
    /// # Safety
    ///
    /// `object_tracking_configuration` must implement OS_ar_object_tracking_configuration.
    #[doc(alias = "ar_object_tracking_provider_create")]
    #[cfg(all(feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn new(
        object_tracking_configuration: &ar_object_tracking_configuration_t,
    ) -> Retained<ar_object_tracking_provider_t> {
        extern "C-unwind" {
            fn ar_object_tracking_provider_create(
                object_tracking_configuration: &ar_object_tracking_configuration_t,
            ) -> *mut ar_object_tracking_provider_t;
        }
        let ret = unsafe { ar_object_tracking_provider_create(object_tracking_configuration) };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }
}

/// Handler called when there are updates to object anchors.
///
///
/// Parameter `added_anchors`: The collection of anchors that were added.
///
/// Parameter `updated_anchors`: The collection of anchors that were updated.
///
/// Parameter `removed_anchors`: The collection of anchors that were removed.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_object_tracking_update_handler_t?language=objc)
#[cfg(all(feature = "block2", feature = "objc2"))]
pub type ar_object_tracking_update_handler_t = block2::Block<
    'static,
    fn(NonNull<ar_object_anchors_t>, NonNull<ar_object_anchors_t>, NonNull<ar_object_anchors_t>),
>;

impl ar_object_tracking_provider_t {
    /// Set the handler for receiving object tracking updates.
    ///
    ///
    /// Parameter `object_tracking_provider`: The object tracking provider.
    ///
    /// Parameter `object_tracking_updates_queue`: The queue on which the handler will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `object_tracking_update_handler`: The handler to be called when new object tracking data arrives.
    ///
    ///
    /// Note: Setting this handler will override the function set using `ar_object_tracking_provider_set_update_handler_f`.
    ///
    /// # Safety
    ///
    /// - `object_tracking_provider` must implement OS_ar_object_tracking_provider.
    /// - `object_tracking_updates_queue` possibly has additional threading requirements.
    #[doc(alias = "ar_object_tracking_provider_set_update_handler")]
    #[cfg(all(
        feature = "block2",
        feature = "data_provider",
        feature = "dispatch2",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn set_update_handler(
        object_tracking_provider: &ar_object_tracking_provider_t,
        object_tracking_updates_queue: Option<&DispatchQueue>,
        object_tracking_update_handler: Option<&ar_object_tracking_update_handler_t>,
    ) {
        extern "C-unwind" {
            fn ar_object_tracking_provider_set_update_handler(
                object_tracking_provider: &ar_object_tracking_provider_t,
                object_tracking_updates_queue: Option<&DispatchQueue>,
                object_tracking_update_handler: Option<&ar_object_tracking_update_handler_t>,
            );
        }
        unsafe {
            ar_object_tracking_provider_set_update_handler(
                object_tracking_provider,
                object_tracking_updates_queue,
                object_tracking_update_handler,
            )
        }
    }
}

/// Function called when there are updates to object anchors.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `added_anchors`: The collection of anchors that were added.
///
/// Parameter `updated_anchors`: The collection of anchors that were updated.
///
/// Parameter `removed_anchors`: The collection of anchors that were removed.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_object_tracking_update_handler_function_t?language=objc)
#[cfg(feature = "objc2")]
pub type ar_object_tracking_update_handler_function_t = unsafe extern "C-unwind" fn(
    *mut c_void,
    &ar_object_anchors_t,
    &ar_object_anchors_t,
    &ar_object_anchors_t,
);

impl ar_object_tracking_provider_t {
    /// Set the handler for receiving object tracking updates.
    ///
    ///
    /// Parameter `object_tracking_provider`: The object tracking provider.
    ///
    /// Parameter `object_tracking_updates_queue`: The queue on which the handler will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `object_tracking_update_handler_function`: The function to be called when new object tracking data arrives.
    ///
    ///
    /// Note: Setting this handler will override the function set using `ar_object_tracking_provider_set_update_handler`.
    ///
    /// # Safety
    ///
    /// - `object_tracking_provider` must implement OS_ar_object_tracking_provider.
    /// - `object_tracking_updates_queue` possibly has additional threading requirements.
    /// - `context` must be a valid pointer or null.
    /// - `object_tracking_update_handler_function` must be implemented correctly.
    #[doc(alias = "ar_object_tracking_provider_set_update_handler_f")]
    #[cfg(all(feature = "data_provider", feature = "dispatch2", feature = "objc2"))]
    #[inline]
    pub unsafe fn set_update_handler_f(
        object_tracking_provider: &ar_object_tracking_provider_t,
        object_tracking_updates_queue: Option<&DispatchQueue>,
        context: *mut c_void,
        object_tracking_update_handler_function: Option<
            ar_object_tracking_update_handler_function_t,
        >,
    ) {
        extern "C-unwind" {
            fn ar_object_tracking_provider_set_update_handler_f(
                object_tracking_provider: &ar_object_tracking_provider_t,
                object_tracking_updates_queue: Option<&DispatchQueue>,
                context: *mut c_void,
                object_tracking_update_handler_function: Option<
                    ar_object_tracking_update_handler_function_t,
                >,
            );
        }
        unsafe {
            ar_object_tracking_provider_set_update_handler_f(
                object_tracking_provider,
                object_tracking_updates_queue,
                context,
                object_tracking_update_handler_function,
            )
        }
    }

    /// Copy all object anchors.
    ///
    ///
    /// Parameter `object_tracking_provider`: The object tracking provider.
    ///
    ///
    /// Returns: The collection of all object anchors. This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release
    /// the object.
    ///
    /// # Safety
    ///
    /// `object_tracking_provider` must implement OS_ar_object_tracking_provider.
    #[doc(alias = "ar_object_tracking_provider_copy_all_object_anchors")]
    #[cfg(all(feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn all_object_anchors(
        object_tracking_provider: &ar_object_tracking_provider_t,
    ) -> Retained<ar_object_anchors_t> {
        extern "C-unwind" {
            fn ar_object_tracking_provider_copy_all_object_anchors(
                object_tracking_provider: &ar_object_tracking_provider_t,
            ) -> *mut ar_object_anchors_t;
        }
        let ret = unsafe {
            ar_object_tracking_provider_copy_all_object_anchors(object_tracking_provider)
        };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Determine whether this device supports the object tracking provider.
    ///
    ///
    /// Returns: `true` if the object tracking provider is supported on this device, `false` otherwise.
    #[doc(alias = "ar_object_tracking_provider_is_supported")]
    #[inline]
    pub unsafe fn is_supported() -> bool {
        extern "C-unwind" {
            fn ar_object_tracking_provider_is_supported() -> bool;
        }
        unsafe { ar_object_tracking_provider_is_supported() }
    }

    /// Get the authorization type required by the object tracking provider.
    ///
    ///
    /// Returns: The required authorization type.
    #[doc(alias = "ar_object_tracking_provider_get_required_authorization_type")]
    #[cfg(feature = "authorization")]
    #[inline]
    pub unsafe fn required_authorization_type() -> ar_authorization_type_t {
        extern "C-unwind" {
            fn ar_object_tracking_provider_get_required_authorization_type(
            ) -> ar_authorization_type_t;
        }
        unsafe { ar_object_tracking_provider_get_required_authorization_type() }
    }
}
