//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::cell::UnsafeCell;
use core::ffi::*;
use core::marker::{PhantomData, PhantomPinned};
use core::ptr::NonNull;
#[cfg(feature = "dispatch2")]
use dispatch2::*;
#[cfg(feature = "objc2")]
use objc2::__framework_prelude::*;

use crate::*;

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_device_t?language=objc)
#[repr(C)]
pub struct ar_device_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_device_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_session_t?language=objc)
#[repr(C)]
pub struct ar_session_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_session_t {}
);

impl ar_session_t {
    /// Create an ARKit session.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_session_t`.
    #[doc(alias = "ar_session_create")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn new() -> Retained<ar_session_t> {
        extern "C-unwind" {
            fn ar_session_create() -> *mut ar_session_t;
        }
        let ret = unsafe { ar_session_create() };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Create a session connected to the specified device.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Parameter `device`: The device to connect to.
    ///
    /// Returns: An instance of `ar_session_t`.
    ///
    /// # Safety
    ///
    /// `device` must implement OS_ar_device.
    #[doc(alias = "ar_session_create_with_device")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn with_device(device: &ar_device_t) -> Retained<ar_session_t> {
        extern "C-unwind" {
            fn ar_session_create_with_device(device: &ar_device_t) -> *mut ar_session_t;
        }
        let ret = unsafe { ar_session_create_with_device(device) };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }
}

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_session_error_code_t?language=objc)
#[cfg(feature = "error")]
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ar_session_error_code_t(pub ar_error_code_t);
#[cfg(feature = "error")]
impl ar_session_error_code_t {
    /// Error code indicating that a data provider requires an authorization that has not been granted by the user.
    #[doc(alias = "ar_session_error_code_data_provider_not_authorized")]
    pub const data_provider_not_authorized: Self = Self(100);
    /// Error code indicating a data provider has failed to run.
    #[doc(alias = "ar_session_error_code_data_provider_failed_to_run")]
    pub const data_provider_failed_to_run: Self = Self(101);
}

#[cfg(all(feature = "error", feature = "objc2"))]
unsafe impl Encode for ar_session_error_code_t {
    const ENCODING: Encoding = ar_error_code_t::ENCODING;
}

#[cfg(all(feature = "error", feature = "objc2"))]
unsafe impl RefEncode for ar_session_error_code_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// A handler that the session calls when one or more data providers associated with it change state.
///
/// - Parameters:
/// - data_providers: The collection of data providers that changed state.
/// - new_state: The data provider state that triggered the event.
/// - error: An error associated with the state change, if any. The returned error supports ARC. In non-ARC files, call `ar_release()` to release
/// the error. Also see `ar_session_error_code_t`.
/// - failed_data_provider: The data provider that failed and caused the error, if any.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_session_data_provider_state_change_handler_t?language=objc)
#[cfg(all(
    feature = "block2",
    feature = "data_provider",
    feature = "error",
    feature = "objc2"
))]
pub type ar_session_data_provider_state_change_handler_t = block2::Block<
    'static,
    fn(
        NonNull<ar_data_providers_t>,
        ar_data_provider_state_t,
        *mut ar_error_t,
        *mut ar_data_provider_t,
    ),
>;

impl ar_session_t {
    /// Sets the handler for responding to a state change of one or more data providers.
    ///
    /// - Parameters:
    /// - session: The `ar_session_t` instance.
    /// - queue: The queue on which the handler will be called. Passing NULL will default to the main queue.
    /// - data_provider_state_change_handler: The data provider state change handler.
    ///
    /// - Note: Setting this will override the function set using `ar_session_set_data_provider_state_change_handler_f`.
    ///
    /// # Safety
    ///
    /// - `session` must implement OS_ar_session.
    /// - `queue` possibly has additional threading requirements.
    #[doc(alias = "ar_session_set_data_provider_state_change_handler")]
    #[cfg(all(
        feature = "block2",
        feature = "data_provider",
        feature = "dispatch2",
        feature = "error",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn set_data_provider_state_change_handler(
        session: &ar_session_t,
        queue: Option<&DispatchQueue>,
        data_provider_state_change_handler: Option<
            &ar_session_data_provider_state_change_handler_t,
        >,
    ) {
        extern "C-unwind" {
            fn ar_session_set_data_provider_state_change_handler(
                session: &ar_session_t,
                queue: Option<&DispatchQueue>,
                data_provider_state_change_handler: Option<
                    &ar_session_data_provider_state_change_handler_t,
                >,
            );
        }
        unsafe {
            ar_session_set_data_provider_state_change_handler(
                session,
                queue,
                data_provider_state_change_handler,
            )
        }
    }
}

/// A handler function that the session calls when one or more data providers associated with it change state.
///
/// - Parameters:
/// - context: The application-defined context.
/// - data_providers: The collection of data providers that changed state.
/// - new_state: The data provider state that triggered the event.
/// - error: An error associated with the state change, if any. The returned error supports ARC. In non-ARC files, call `ar_release()` to
/// release the error. Also see `ar_session_error_code_t`.
/// - failed_data_provider: The data provider that failed and caused the error, if any.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_session_data_provider_state_change_handler_function_t?language=objc)
#[cfg(all(feature = "data_provider", feature = "error", feature = "objc2"))]
pub type ar_session_data_provider_state_change_handler_function_t = unsafe extern "C-unwind" fn(
    *mut c_void,
    &ar_data_providers_t,
    ar_data_provider_state_t,
    Option<&ar_error_t>,
    Option<&ar_data_provider_t>,
);

impl ar_session_t {
    /// Sets the handler function for responding to a state change of one or more data providers.
    ///
    /// - Parameters:
    /// - session: The `ar_session_t` instance.
    /// - queue: The queue on which the function will be called. Passing NULL will default to the main queue.
    /// - context: The application-defined context parameter to pass to the function.
    /// - data_provider_state_change_handler_function: The data provider state change handler function.
    ///
    /// - Note: Setting this will override the handler set using `ar_session_set_data_provider_state_change_handler`.
    ///
    /// # Safety
    ///
    /// - `session` must implement OS_ar_session.
    /// - `queue` possibly has additional threading requirements.
    /// - `context` must be a valid pointer or null.
    /// - `data_provider_state_change_handler_function` must be implemented correctly.
    #[doc(alias = "ar_session_set_data_provider_state_change_handler_f")]
    #[cfg(all(
        feature = "data_provider",
        feature = "dispatch2",
        feature = "error",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn set_data_provider_state_change_handler_f(
        session: &ar_session_t,
        queue: Option<&DispatchQueue>,
        context: *mut c_void,
        data_provider_state_change_handler_function: Option<
            ar_session_data_provider_state_change_handler_function_t,
        >,
    ) {
        extern "C-unwind" {
            fn ar_session_set_data_provider_state_change_handler_f(
                session: &ar_session_t,
                queue: Option<&DispatchQueue>,
                context: *mut c_void,
                data_provider_state_change_handler_function: Option<
                    ar_session_data_provider_state_change_handler_function_t,
                >,
            );
        }
        unsafe {
            ar_session_set_data_provider_state_change_handler_f(
                session,
                queue,
                context,
                data_provider_state_change_handler_function,
            )
        }
    }

    /// Run data providers on a session.
    ///
    ///
    /// Parameter `session`: The session.
    ///
    /// Parameter `data_providers`: The collection of data providers to run.
    ///
    /// # Safety
    ///
    /// - `session` must implement OS_ar_session.
    /// - `data_providers` must implement OS_ar_data_providers.
    #[doc(alias = "ar_session_run")]
    #[cfg(all(feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn run(session: &ar_session_t, data_providers: &ar_data_providers_t) {
        extern "C-unwind" {
            fn ar_session_run(session: &ar_session_t, data_providers: &ar_data_providers_t);
        }
        unsafe { ar_session_run(session, data_providers) }
    }

    /// Stop all running data providers on a session.
    ///
    ///
    /// Parameter `session`: The session.
    ///
    /// # Safety
    ///
    /// `session` must implement OS_ar_session.
    #[doc(alias = "ar_session_stop")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn stop(session: &ar_session_t) {
        extern "C-unwind" {
            fn ar_session_stop(session: &ar_session_t);
        }
        unsafe { ar_session_stop(session) }
    }

    /// Get a copy of the collection of all data providers on this session.
    ///
    /// Parameter `session`: The session.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: The collection of data providers.
    ///
    /// # Safety
    ///
    /// `session` must implement OS_ar_session.
    #[doc(alias = "ar_session_copy_data_providers")]
    #[cfg(all(feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn data_providers(session: &ar_session_t) -> Retained<ar_data_providers_t> {
        extern "C-unwind" {
            fn ar_session_copy_data_providers(session: &ar_session_t) -> *mut ar_data_providers_t;
        }
        let ret = unsafe { ar_session_copy_data_providers(session) };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }
}

/// Handler to be called when there are updates to authorization.
///
///
/// Parameter `authorization_result`: The authorization result.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_authorization_update_handler_t?language=objc)
#[cfg(all(feature = "authorization", feature = "block2", feature = "objc2"))]
pub type ar_authorization_update_handler_t =
    block2::Block<'static, fn(NonNull<ar_authorization_result_t>)>;

impl ar_session_t {
    /// Set the handler for receiving authorization status updates.
    ///
    ///
    /// Parameter `session`: The session.
    ///
    /// Parameter `authorization_update_queue`: The queue on which the handler will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `authorization_update_handler`: The handler to be called when there is an update to authorization status.
    ///
    ///
    /// Note: Setting this handler will override the function set using `ar_session_set_authorization_update_handler_f`.
    ///
    /// # Safety
    ///
    /// - `session` must implement OS_ar_session.
    /// - `authorization_update_queue` possibly has additional threading requirements.
    #[doc(alias = "ar_session_set_authorization_update_handler")]
    #[cfg(all(
        feature = "authorization",
        feature = "block2",
        feature = "dispatch2",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn set_authorization_update_handler(
        session: &ar_session_t,
        authorization_update_queue: Option<&DispatchQueue>,
        authorization_update_handler: Option<&ar_authorization_update_handler_t>,
    ) {
        extern "C-unwind" {
            fn ar_session_set_authorization_update_handler(
                session: &ar_session_t,
                authorization_update_queue: Option<&DispatchQueue>,
                authorization_update_handler: Option<&ar_authorization_update_handler_t>,
            );
        }
        unsafe {
            ar_session_set_authorization_update_handler(
                session,
                authorization_update_queue,
                authorization_update_handler,
            )
        }
    }
}

/// Function to be called when there are updates to authorization.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `authorization_result`: The authorization result.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_authorization_update_handler_function_t?language=objc)
#[cfg(all(feature = "authorization", feature = "objc2"))]
pub type ar_authorization_update_handler_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &ar_authorization_result_t);

impl ar_session_t {
    /// Set the function for receiving authorization status updates.
    ///
    ///
    /// Parameter `session`: The session.
    ///
    /// Parameter `authorization_update_queue`: The queue on which the function will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `authorization_update_handler_function`: The function to be called when there is an update to authorization status.
    ///
    ///
    /// Note: Setting this function will override the handler set using `ar_session_set_authorization_update_handler`.
    ///
    /// # Safety
    ///
    /// - `session` must implement OS_ar_session.
    /// - `authorization_update_queue` possibly has additional threading requirements.
    /// - `context` must be a valid pointer or null.
    /// - `authorization_update_handler_function` must be implemented correctly.
    #[doc(alias = "ar_session_set_authorization_update_handler_f")]
    #[cfg(all(feature = "authorization", feature = "dispatch2", feature = "objc2"))]
    #[inline]
    pub unsafe fn set_authorization_update_handler_f(
        session: &ar_session_t,
        authorization_update_queue: Option<&DispatchQueue>,
        context: *mut c_void,
        authorization_update_handler_function: Option<ar_authorization_update_handler_function_t>,
    ) {
        extern "C-unwind" {
            fn ar_session_set_authorization_update_handler_f(
                session: &ar_session_t,
                authorization_update_queue: Option<&DispatchQueue>,
                context: *mut c_void,
                authorization_update_handler_function: Option<
                    ar_authorization_update_handler_function_t,
                >,
            );
        }
        unsafe {
            ar_session_set_authorization_update_handler_f(
                session,
                authorization_update_queue,
                context,
                authorization_update_handler_function,
            )
        }
    }
}

/// Handler to be called upon completion of an authorization request.
///
///
/// Parameter `authorization_results`: The collection of authorization results.
///
/// Parameter `error`: The error that occurred during the authorization request, if any. The returned error supports ARC. In non-ARC files, use `ar_release()`
/// to release the error.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_authorization_results_handler_t?language=objc)
#[cfg(all(
    feature = "authorization",
    feature = "block2",
    feature = "error",
    feature = "objc2"
))]
pub type ar_authorization_results_handler_t =
    block2::Block<'static, fn(NonNull<ar_authorization_results_t>, *mut ar_error_t)>;

impl ar_session_t {
    /// Query the status of different authorization types.
    ///
    ///
    /// Parameter `session`: The session.
    ///
    /// Parameter `authorization_types`: The authorization types to query.
    ///
    /// Parameter `results_handler`: The handler to be called upon completion of the request. This handler will be called on an arbitrary queue.
    ///
    /// # Safety
    ///
    /// `session` must implement OS_ar_session.
    #[doc(alias = "ar_session_query_authorization_results")]
    #[cfg(all(
        feature = "authorization",
        feature = "block2",
        feature = "error",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn query_authorization_results(
        session: &ar_session_t,
        authorization_types: ar_authorization_type_t,
        results_handler: &ar_authorization_results_handler_t,
    ) {
        extern "C-unwind" {
            fn ar_session_query_authorization_results(
                session: &ar_session_t,
                authorization_types: ar_authorization_type_t,
                results_handler: &ar_authorization_results_handler_t,
            );
        }
        unsafe {
            ar_session_query_authorization_results(session, authorization_types, results_handler)
        }
    }

    /// Request authorization for accessing ARKit data.
    ///
    ///
    /// Parameter `session`: The session.
    ///
    /// Parameter `authorization_types`: The authorization types to request.
    ///
    /// Parameter `results_handler`: The handler to be called upon completion of the request. This handler will be called on an arbitrary queue.
    ///
    ///
    /// This will asynchronously prompt users for permission to access their data. If the authorization is already allowed or denied by the user,
    /// the handler will be called without prompting the user for permission again.
    ///
    /// # Safety
    ///
    /// `session` must implement OS_ar_session.
    #[doc(alias = "ar_session_request_authorization")]
    #[cfg(all(
        feature = "authorization",
        feature = "block2",
        feature = "error",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn request_authorization(
        session: &ar_session_t,
        authorization_types: ar_authorization_type_t,
        results_handler: &ar_authorization_results_handler_t,
    ) {
        extern "C-unwind" {
            fn ar_session_request_authorization(
                session: &ar_session_t,
                authorization_types: ar_authorization_type_t,
                results_handler: &ar_authorization_results_handler_t,
            );
        }
        unsafe { ar_session_request_authorization(session, authorization_types, results_handler) }
    }
}

/// Function to be called upon completion of an authorization request.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `authorization_results`: The collection of authorization results.
///
/// Parameter `error`: The error that occurred during the authorization request, if any. The returned error supports ARC. In non-ARC files, use `ar_release()`
/// to release the error.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_authorization_results_handler_function_t?language=objc)
#[cfg(all(feature = "authorization", feature = "error", feature = "objc2"))]
pub type ar_authorization_results_handler_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &ar_authorization_results_t, Option<&ar_error_t>);

impl ar_session_t {
    /// Query the status of different authorization types.
    ///
    ///
    /// Parameter `session`: The session.
    ///
    /// Parameter `authorization_types`: The authorization types to query.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `results_handler_function`: The function to be called upon completion of the request. This function will be called on an arbitrary queue.
    ///
    /// # Safety
    ///
    /// - `session` must implement OS_ar_session.
    /// - `context` must be a valid pointer or null.
    /// - `results_handler_function` must be implemented correctly.
    #[doc(alias = "ar_session_query_authorization_results_f")]
    #[cfg(all(feature = "authorization", feature = "error", feature = "objc2"))]
    #[inline]
    pub unsafe fn query_authorization_results_f(
        session: &ar_session_t,
        authorization_types: ar_authorization_type_t,
        context: *mut c_void,
        results_handler_function: ar_authorization_results_handler_function_t,
    ) {
        extern "C-unwind" {
            fn ar_session_query_authorization_results_f(
                session: &ar_session_t,
                authorization_types: ar_authorization_type_t,
                context: *mut c_void,
                results_handler_function: ar_authorization_results_handler_function_t,
            );
        }
        unsafe {
            ar_session_query_authorization_results_f(
                session,
                authorization_types,
                context,
                results_handler_function,
            )
        }
    }

    /// Request authorization for accessing ARKit data.
    ///
    ///
    /// Parameter `session`: The session.
    ///
    /// Parameter `authorization_types`: The authorization types to request.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `results_handler_function`: The function to be called upon completion of the request. This function will be called on an arbitrary queue.
    ///
    ///
    /// This will asynchronously prompt users for permission to access their data. If the authorization is already allowed or denied by the user,
    /// the function will be called without prompting the user for permission again.
    ///
    /// # Safety
    ///
    /// - `session` must implement OS_ar_session.
    /// - `context` must be a valid pointer or null.
    /// - `results_handler_function` must be implemented correctly.
    #[doc(alias = "ar_session_request_authorization_f")]
    #[cfg(all(feature = "authorization", feature = "error", feature = "objc2"))]
    #[inline]
    pub unsafe fn request_authorization_f(
        session: &ar_session_t,
        authorization_types: ar_authorization_type_t,
        context: *mut c_void,
        results_handler_function: ar_authorization_results_handler_function_t,
    ) {
        extern "C-unwind" {
            fn ar_session_request_authorization_f(
                session: &ar_session_t,
                authorization_types: ar_authorization_type_t,
                context: *mut c_void,
                results_handler_function: ar_authorization_results_handler_function_t,
            );
        }
        unsafe {
            ar_session_request_authorization_f(
                session,
                authorization_types,
                context,
                results_handler_function,
            )
        }
    }
}
