//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::cell::UnsafeCell;
use core::ffi::*;
use core::marker::{PhantomData, PhantomPinned};
use core::ptr::NonNull;
#[cfg(feature = "dispatch2")]
use dispatch2::*;
#[cfg(feature = "objc2")]
use objc2::__framework_prelude::*;
#[cfg(feature = "objc2-core-foundation")]
use objc2_core_foundation::*;

use crate::*;

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_coordinate_space_data_t?language=objc)
#[repr(C)]
pub struct ar_coordinate_space_data_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_coordinate_space_data_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_shared_coordinate_space_configuration_t?language=objc)
#[repr(C)]
pub struct ar_shared_coordinate_space_configuration_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_shared_coordinate_space_configuration_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_shared_coordinate_space_provider_t?language=objc)
#[repr(C)]
pub struct ar_shared_coordinate_space_provider_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_shared_coordinate_space_provider_t {}
);

/// Handler called when there is an update to shared coordinate space connected participants.
///
///
/// Parameter `connected_participant_identifiers`: List of all participant identifiers that have established a shared coordinate space.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_shared_coordinate_space_connected_participants_update_handler_t?language=objc)
#[cfg(all(feature = "block2", feature = "identifiers", feature = "objc2"))]
pub type ar_shared_coordinate_space_connected_participants_update_handler_t =
    block2::Block<'static, fn(NonNull<ar_identifiers_t>)>;

/// Handler called when there is an update to shared coordinate space sharing status.
///
///
/// Parameter `is_sharing_enabled`: Whether coordinate space sharing is enabled.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_shared_coordinate_space_sharing_status_update_handler_t?language=objc)
#[cfg(feature = "block2")]
pub type ar_shared_coordinate_space_sharing_status_update_handler_t =
    block2::Block<'static, fn(bool)>;

/// Function called when there are updates to shared coordinate space participant status.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `connected_participant_identifiers`: List of participant identifiers that have established a shared coordinate space.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_shared_coordinate_space_connected_participants_update_handler_function_t?language=objc)
#[cfg(all(feature = "identifiers", feature = "objc2"))]
pub type ar_shared_coordinate_space_connected_participants_update_handler_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &ar_identifiers_t);

/// Function called when there is an update to shared coordinate space sharing status.
///
///
/// Parameter `is_sharing_enabled`: Whether coordinate space sharing is enabled.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_shared_coordinate_space_sharing_status_update_handler_function_t?language=objc)
#[cfg(feature = "block2")]
pub type ar_shared_coordinate_space_sharing_status_update_handler_function_t =
    block2::Block<'static, fn(*mut c_void, bool)>;

impl ar_coordinate_space_data_t {
    /// Copy the list of participant identifiers of the intended recipient for this data. Data should be broadcast if the list is empty.
    ///
    ///
    /// Parameter `shared_coordinate_space_data`: Shared coordinate space data.
    ///
    ///
    /// Returns: List the participant identifiers to which the data should be sent. Data should be broadcast to all participants if the list is empty.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// # Safety
    ///
    /// `shared_coordinate_space_data` must implement OS_ar_coordinate_space_data.
    #[doc(alias = "ar_coordinate_space_data_copy_recipient_identifers")]
    #[cfg(all(feature = "identifiers", feature = "objc2"))]
    #[inline]
    pub unsafe fn recipient_identifers(
        shared_coordinate_space_data: &ar_coordinate_space_data_t,
    ) -> Retained<ar_identifiers_t> {
        extern "C-unwind" {
            fn ar_coordinate_space_data_copy_recipient_identifers(
                shared_coordinate_space_data: &ar_coordinate_space_data_t,
            ) -> *mut ar_identifiers_t;
        }
        let ret = unsafe {
            ar_coordinate_space_data_copy_recipient_identifers(shared_coordinate_space_data)
        };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Create and initialize an `ar_coordinate_space_data_t` from a `CFDataRef`.
    ///
    ///
    /// Parameter `cfData`: The CFDataRef object to set for the `ar_coordinate_space_data_t`.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    ///
    /// Returns: An instance of `ar_coordinate_space_data_t`.
    #[doc(alias = "ar_coordinate_space_data_create_from_cfdata")]
    #[cfg(all(feature = "objc2", feature = "objc2-core-foundation"))]
    #[inline]
    pub unsafe fn from_cfdata(cf_data: &CFData) -> Option<Retained<ar_coordinate_space_data_t>> {
        extern "C-unwind" {
            fn ar_coordinate_space_data_create_from_cfdata(
                cf_data: &CFData,
            ) -> *mut ar_coordinate_space_data_t;
        }
        let ret = unsafe { ar_coordinate_space_data_create_from_cfdata(cf_data) };
        unsafe { Retained::from_raw(ret) }
    }

    /// Copy out a `CFDataRef` that archives the coordinate space data.
    ///
    ///
    /// Parameter `data`: Coordinate space data.
    ///
    ///
    /// Returns: The `CFDataRef`. The caller is responsible for calling `CFRelease` on the returned pointer.
    ///
    /// # Safety
    ///
    /// `data` must implement OS_ar_coordinate_space_data.
    #[doc(alias = "ar_coordinate_space_data_copy_cfdata")]
    #[cfg(all(feature = "objc2", feature = "objc2-core-foundation"))]
    #[inline]
    pub unsafe fn cfdata(data: &ar_coordinate_space_data_t) -> CFRetained<CFData> {
        extern "C-unwind" {
            fn ar_coordinate_space_data_copy_cfdata(
                data: &ar_coordinate_space_data_t,
            ) -> Option<NonNull<CFData>>;
        }
        let ret = unsafe { ar_coordinate_space_data_copy_cfdata(data) };
        let ret =
            ret.expect("function was marked as returning non-null, but actually returned NULL");
        unsafe { CFRetained::from_raw(ret) }
    }
}

impl ar_shared_coordinate_space_configuration_t {
    /// Create a shared coordinate space configuration.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_shared_coordinate_space_configuration_t`.
    #[doc(alias = "ar_shared_coordinate_space_configuration_create")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn new() -> Retained<ar_shared_coordinate_space_configuration_t> {
        extern "C-unwind" {
            fn ar_shared_coordinate_space_configuration_create(
            ) -> *mut ar_shared_coordinate_space_configuration_t;
        }
        let ret = unsafe { ar_shared_coordinate_space_configuration_create() };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }
}

impl ar_shared_coordinate_space_provider_t {
    /// Create a shared coordinate space provider.
    ///
    ///
    /// Parameter `shared_coordinate_space_configuration`: shared coordinate space configuration.
    ///
    ///
    /// See: `ar_session_t` to run this shared coordinate space provider.
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_shared_coordinate_space_provider_t`.
    ///
    /// # Safety
    ///
    /// `shared_coordinate_space_configuration` must implement OS_ar_shared_coordinate_space_configuration.
    #[doc(alias = "ar_shared_coordinate_space_provider_create")]
    #[cfg(all(feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn new(
        shared_coordinate_space_configuration: &ar_shared_coordinate_space_configuration_t,
    ) -> Retained<ar_shared_coordinate_space_provider_t> {
        extern "C-unwind" {
            fn ar_shared_coordinate_space_provider_create(
                shared_coordinate_space_configuration: &ar_shared_coordinate_space_configuration_t,
            ) -> *mut ar_shared_coordinate_space_provider_t;
        }
        let ret = unsafe {
            ar_shared_coordinate_space_provider_create(shared_coordinate_space_configuration)
        };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Get the identifier used to identify the participant in the shared coordinate space.
    ///
    ///
    /// Parameter `shared_coordinate_space_provider`: Shared coordinate space provider.
    ///
    /// Parameter `out_identifier`: A pointer to a UUID to fill out with the identifier of the participant. Must be non-null.
    ///
    /// # Safety
    ///
    /// `shared_coordinate_space_provider` must implement OS_ar_shared_coordinate_space_provider.
    #[doc(alias = "ar_shared_coordinate_space_provider_get_participant_identifier")]
    #[cfg(all(feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn participant_identifier(
        shared_coordinate_space_provider: &ar_shared_coordinate_space_provider_t,
        out_identifier: &mut uuid_t,
    ) {
        extern "C-unwind" {
            fn ar_shared_coordinate_space_provider_get_participant_identifier(
                shared_coordinate_space_provider: &ar_shared_coordinate_space_provider_t,
                out_identifier: &mut uuid_t,
            );
        }
        unsafe {
            ar_shared_coordinate_space_provider_get_participant_identifier(
                shared_coordinate_space_provider,
                out_identifier,
            )
        }
    }

    /// Get the latest sharing status.
    ///
    ///
    /// Parameter `shared_coordinate_space_provider`: Shared coordinate space provider.
    ///
    ///
    /// Returns: `true` if coordinate space sharing is enabled, `false` otherwise.
    ///
    /// # Safety
    ///
    /// `shared_coordinate_space_provider` must implement OS_ar_shared_coordinate_space_provider.
    #[doc(alias = "ar_shared_coordinate_space_provider_is_sharing_enabled")]
    #[cfg(all(feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn is_sharing_enabled(
        shared_coordinate_space_provider: &ar_shared_coordinate_space_provider_t,
    ) -> bool {
        extern "C-unwind" {
            fn ar_shared_coordinate_space_provider_is_sharing_enabled(
                shared_coordinate_space_provider: &ar_shared_coordinate_space_provider_t,
            ) -> bool;
        }
        unsafe {
            ar_shared_coordinate_space_provider_is_sharing_enabled(shared_coordinate_space_provider)
        }
    }

    /// Push data to the shared coordinate space provider.
    ///
    ///
    /// Parameter `shared_coordinate_space_provider`: The shared coordinate space provider.
    ///
    /// Parameter `coordinate_space_data`: Coordinate space data.
    ///
    /// # Safety
    ///
    /// - `shared_coordinate_space_provider` must implement OS_ar_shared_coordinate_space_provider.
    /// - `coordinate_space_data` must implement OS_ar_coordinate_space_data.
    #[doc(alias = "ar_shared_coordinate_space_provider_push_data")]
    #[cfg(all(feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn push_data(
        shared_coordinate_space_provider: &ar_shared_coordinate_space_provider_t,
        coordinate_space_data: &ar_coordinate_space_data_t,
    ) {
        extern "C-unwind" {
            fn ar_shared_coordinate_space_provider_push_data(
                shared_coordinate_space_provider: &ar_shared_coordinate_space_provider_t,
                coordinate_space_data: &ar_coordinate_space_data_t,
            );
        }
        unsafe {
            ar_shared_coordinate_space_provider_push_data(
                shared_coordinate_space_provider,
                coordinate_space_data,
            )
        }
    }

    /// Determines whether this device supports the shared coordinate space provider.
    ///
    /// Returns: Returns `true` if provider is supported on this device, `false` otherwise.
    #[doc(alias = "ar_shared_coordinate_space_provider_is_supported")]
    #[inline]
    pub unsafe fn is_supported() -> bool {
        extern "C-unwind" {
            fn ar_shared_coordinate_space_provider_is_supported() -> bool;
        }
        unsafe { ar_shared_coordinate_space_provider_is_supported() }
    }

    /// Copy the next collaboration data.
    ///
    ///
    /// Parameter `shared_coordinate_space_provider`: The shared coordinate space provider.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: Coordinate space data if available, `nil` otherwise.
    ///
    /// # Safety
    ///
    /// `shared_coordinate_space_provider` must implement OS_ar_shared_coordinate_space_provider.
    #[doc(alias = "ar_shared_coordinate_space_provider_copy_next_coordinate_space_data")]
    #[cfg(all(feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn next_coordinate_space_data(
        shared_coordinate_space_provider: &ar_shared_coordinate_space_provider_t,
    ) -> Option<Retained<ar_coordinate_space_data_t>> {
        extern "C-unwind" {
            fn ar_shared_coordinate_space_provider_copy_next_coordinate_space_data(
                shared_coordinate_space_provider: &ar_shared_coordinate_space_provider_t,
            ) -> *mut ar_coordinate_space_data_t;
        }
        let ret = unsafe {
            ar_shared_coordinate_space_provider_copy_next_coordinate_space_data(
                shared_coordinate_space_provider,
            )
        };
        unsafe { Retained::from_raw(ret) }
    }

    /// Set the handler for receiving shared coordinate space connected participants updates.
    ///
    ///
    /// Parameter `shared_coordinate_space_provider`: The shared coordinate space provider.
    ///
    /// Parameter `connected_participants_update_queue`: The queue on which the handler will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `connected_participants_update_handler`: The handler to be called when there is an update to shared coordinate space connected participants.
    ///
    /// # Safety
    ///
    /// - `shared_coordinate_space_provider` must implement OS_ar_shared_coordinate_space_provider.
    /// - `connected_participants_update_queue` possibly has additional threading requirements.
    #[doc(alias = "ar_shared_coordinate_space_provider_set_connected_participants_update_handler")]
    #[cfg(all(
        feature = "block2",
        feature = "data_provider",
        feature = "dispatch2",
        feature = "identifiers",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn set_connected_participants_update_handler(
        shared_coordinate_space_provider: &ar_shared_coordinate_space_provider_t,
        connected_participants_update_queue: Option<&DispatchQueue>,
        connected_participants_update_handler: Option<
            &ar_shared_coordinate_space_connected_participants_update_handler_t,
        >,
    ) {
        extern "C-unwind" {
            fn ar_shared_coordinate_space_provider_set_connected_participants_update_handler(
                shared_coordinate_space_provider: &ar_shared_coordinate_space_provider_t,
                connected_participants_update_queue: Option<&DispatchQueue>,
                connected_participants_update_handler: Option<
                    &ar_shared_coordinate_space_connected_participants_update_handler_t,
                >,
            );
        }
        unsafe {
            ar_shared_coordinate_space_provider_set_connected_participants_update_handler(
                shared_coordinate_space_provider,
                connected_participants_update_queue,
                connected_participants_update_handler,
            )
        }
    }
}

/// Set the function for receiving shared coordinate space connected participants updates.
///
///
/// Parameter `shared_coordinate_space_provider`: Shared coordinate space provider.
///
/// Parameter `connected_participants_update_queue`: Queue on which the function will be executed. Defaults to main queue when NULL is passed in.
///
/// Parameter `context`: The application-defined context parameter to pass to the function.
///
/// Parameter `connected_participants_update_handler_function`: Function to be called when there is an update to shared coordinate space connected
/// participants. Refer to `ar_shared_coordinate_space_connected_participants_update_handler_function_t` for function signature.
///
///
/// Note: Setting this function will override the handler set using `ar_shared_coordinate_space_provider_set_connected_participants_update_handler`.
///
/// # Safety
///
/// - `shared_coordinate_space_provider` must implement OS_ar_shared_coordinate_space_provider.
/// - `connected_participants_update_queue` possibly has additional threading requirements.
/// - `context` must be a valid pointer or null.
/// - `connected_participants_update_handler_function` must be implemented correctly.
#[cfg(all(
    feature = "data_provider",
    feature = "dispatch2",
    feature = "identifiers",
    feature = "objc2"
))]
#[inline]
pub unsafe fn ar_shared_coordinate_provider_set_connected_participants_update_handler_f(
    shared_coordinate_space_provider: &ar_shared_coordinate_space_provider_t,
    connected_participants_update_queue: Option<&DispatchQueue>,
    context: *mut c_void,
    connected_participants_update_handler_function: Option<
        ar_shared_coordinate_space_connected_participants_update_handler_function_t,
    >,
) {
    extern "C-unwind" {
        fn ar_shared_coordinate_provider_set_connected_participants_update_handler_f(
            shared_coordinate_space_provider: &ar_shared_coordinate_space_provider_t,
            connected_participants_update_queue: Option<&DispatchQueue>,
            context: *mut c_void,
            connected_participants_update_handler_function: Option<
                ar_shared_coordinate_space_connected_participants_update_handler_function_t,
            >,
        );
    }
    unsafe {
        ar_shared_coordinate_provider_set_connected_participants_update_handler_f(
            shared_coordinate_space_provider,
            connected_participants_update_queue,
            context,
            connected_participants_update_handler_function,
        )
    }
}

impl ar_shared_coordinate_space_provider_t {
    /// Set the handler for receiving sharing status updates.
    ///
    ///
    /// Parameter `shared_coordinate_space_provider`: The shared coordinate space provider.
    ///
    /// Parameter `status_updates_queue`: The queue on which the handler will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `sharing_status_update_handler`: The handler to be called when there is an update to shared coordinate space sharing status.
    ///
    ///
    /// Note: Setting this function will override the handler set using `ar_shared_coordinate_space_provider_set_sharing_status_update_handler_f`.
    ///
    ///
    /// Set the sharing status update handler to be informed when the provider starts producing data and when the user can push data.
    ///
    /// # Safety
    ///
    /// - `shared_coordinate_space_provider` must implement OS_ar_shared_coordinate_space_provider.
    /// - `status_updates_queue` possibly has additional threading requirements.
    #[doc(alias = "ar_shared_coordinate_space_provider_set_sharing_status_update_handler")]
    #[cfg(all(
        feature = "block2",
        feature = "data_provider",
        feature = "dispatch2",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn set_sharing_status_update_handler(
        shared_coordinate_space_provider: &ar_shared_coordinate_space_provider_t,
        status_updates_queue: Option<&DispatchQueue>,
        sharing_status_update_handler: Option<
            &ar_shared_coordinate_space_sharing_status_update_handler_t,
        >,
    ) {
        extern "C-unwind" {
            fn ar_shared_coordinate_space_provider_set_sharing_status_update_handler(
                shared_coordinate_space_provider: &ar_shared_coordinate_space_provider_t,
                status_updates_queue: Option<&DispatchQueue>,
                sharing_status_update_handler: Option<
                    &ar_shared_coordinate_space_sharing_status_update_handler_t,
                >,
            );
        }
        unsafe {
            ar_shared_coordinate_space_provider_set_sharing_status_update_handler(
                shared_coordinate_space_provider,
                status_updates_queue,
                sharing_status_update_handler,
            )
        }
    }

    /// Set the function for receiving sharing status updates.
    ///
    ///
    /// Parameter `shared_coordinate_space_provider`: The shared coordinate space provider.
    ///
    /// Parameter `status_updates_queue`: The queue on which the handler will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `sharing_status_update_handler_function`: The handler to be called when there is an update to shared coordinate space sharing status.
    ///
    ///
    /// Note: Setting this function will override the handler set using `ar_shared_coordinate_space_provider_set_sharing_status_update_handler`.
    ///
    ///
    /// Set the sharing status update handler to be informed when the provider starts producing data and when the user can push data.
    ///
    /// # Safety
    ///
    /// - `shared_coordinate_space_provider` must implement OS_ar_shared_coordinate_space_provider.
    /// - `status_updates_queue` possibly has additional threading requirements.
    /// - `context` must be a valid pointer or null.
    #[doc(alias = "ar_shared_coordinate_space_provider_set_sharing_status_update_handler_f")]
    #[cfg(all(
        feature = "block2",
        feature = "data_provider",
        feature = "dispatch2",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn set_sharing_status_update_handler_f(
        shared_coordinate_space_provider: &ar_shared_coordinate_space_provider_t,
        status_updates_queue: Option<&DispatchQueue>,
        context: *mut c_void,
        sharing_status_update_handler_function: Option<
            &ar_shared_coordinate_space_sharing_status_update_handler_function_t,
        >,
    ) {
        extern "C-unwind" {
            fn ar_shared_coordinate_space_provider_set_sharing_status_update_handler_f(
                shared_coordinate_space_provider: &ar_shared_coordinate_space_provider_t,
                status_updates_queue: Option<&DispatchQueue>,
                context: *mut c_void,
                sharing_status_update_handler_function: Option<
                    &ar_shared_coordinate_space_sharing_status_update_handler_function_t,
                >,
            );
        }
        unsafe {
            ar_shared_coordinate_space_provider_set_sharing_status_update_handler_f(
                shared_coordinate_space_provider,
                status_updates_queue,
                context,
                sharing_status_update_handler_function,
            )
        }
    }

    /// Get the authorization type required by the shared coordinate space provider.
    ///
    ///
    /// Returns: Authorization type.
    #[doc(alias = "ar_shared_coordinate_space_provider_get_required_authorization_type")]
    #[cfg(feature = "authorization")]
    #[inline]
    pub unsafe fn required_authorization_type() -> ar_authorization_type_t {
        extern "C-unwind" {
            fn ar_shared_coordinate_space_provider_get_required_authorization_type(
            ) -> ar_authorization_type_t;
        }
        unsafe { ar_shared_coordinate_space_provider_get_required_authorization_type() }
    }
}
