//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::cell::UnsafeCell;
use core::ffi::*;
use core::marker::{PhantomData, PhantomPinned};
use core::ptr::NonNull;
#[cfg(feature = "dispatch2")]
use dispatch2::*;
#[cfg(feature = "objc2")]
use objc2::__framework_prelude::*;

use crate::*;

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_skeleton_joint_t?language=objc)
#[repr(C)]
pub struct ar_skeleton_joint_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_skeleton_joint_t {}
);

impl ar_skeleton_joint_t {
    /// Returns a bool value that indicates whether the two skeleton joints are equal.
    ///
    ///
    /// Parameter `skeleton_joint`: A skeleton joint to be compared.
    ///
    /// Parameter `other_skeleton_joint`: The other skeleton joint to be compared to.
    ///
    ///
    /// Returns: YES if the skeleton joints are equal, otherwise NO.
    ///
    /// # Safety
    ///
    /// - `skeleton_joint` must implement OS_ar_skeleton_joint.
    /// - `other_skeleton_joint` must implement OS_ar_skeleton_joint.
    #[doc(alias = "ar_skeleton_joint_is_equal_to_skeleton_joint")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn is_equal_to_skeleton_joint(
        skeleton_joint: Option<&ar_skeleton_joint_t>,
        other_skeleton_joint: Option<&ar_skeleton_joint_t>,
    ) -> bool {
        extern "C-unwind" {
            fn ar_skeleton_joint_is_equal_to_skeleton_joint(
                skeleton_joint: Option<&ar_skeleton_joint_t>,
                other_skeleton_joint: Option<&ar_skeleton_joint_t>,
            ) -> bool;
        }
        unsafe {
            ar_skeleton_joint_is_equal_to_skeleton_joint(skeleton_joint, other_skeleton_joint)
        }
    }

    /// Get a joint's index.
    ///
    ///
    /// Parameter `joint`: The joint.
    ///
    ///
    /// Returns: The index of the joint.
    ///
    /// # Safety
    ///
    /// `joint` must implement OS_ar_skeleton_joint.
    #[doc(alias = "ar_skeleton_joint_get_index")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn index(joint: &ar_skeleton_joint_t) -> u64 {
        extern "C-unwind" {
            fn ar_skeleton_joint_get_index(joint: &ar_skeleton_joint_t) -> u64;
        }
        unsafe { ar_skeleton_joint_get_index(joint) }
    }

    /// Get a joint's parent joint.
    ///
    ///
    /// Parameter `joint`: the joint.
    ///
    ///
    /// Returns: Parent joint. This function will return null for the root node.
    ///
    /// # Safety
    ///
    /// `joint` must implement OS_ar_skeleton_joint.
    #[doc(alias = "ar_skeleton_joint_get_parent")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn parent(joint: &ar_skeleton_joint_t) -> Option<Retained<ar_skeleton_joint_t>> {
        extern "C-unwind" {
            fn ar_skeleton_joint_get_parent(
                joint: &ar_skeleton_joint_t,
            ) -> *mut ar_skeleton_joint_t;
        }
        let ret = unsafe { ar_skeleton_joint_get_parent(joint) };
        unsafe { Retained::retain_autoreleased(ret) }
    }

    /// Determine whether a joint is tracked.
    ///
    ///
    /// Parameter `joint`: The joint.
    ///
    ///
    /// Returns: `true` if the joint is tracked, `false` otherwise.
    ///
    /// # Safety
    ///
    /// `joint` must implement OS_ar_skeleton_joint.
    #[doc(alias = "ar_skeleton_joint_is_tracked")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn is_tracked(joint: &ar_skeleton_joint_t) -> bool {
        extern "C-unwind" {
            fn ar_skeleton_joint_is_tracked(joint: &ar_skeleton_joint_t) -> bool;
        }
        unsafe { ar_skeleton_joint_is_tracked(joint) }
    }
}

/// Handler for enumerating skeleton joints.
///
///
/// Parameter `joint`: The joint.
///
///
/// Returns: `true` to continue enumerating to the next joint name, `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_skeleton_joint_enumerator_t?language=objc)
#[cfg(all(feature = "block2", feature = "objc2"))]
pub type ar_skeleton_joint_enumerator_t =
    block2::Block<'static, fn(NonNull<ar_skeleton_joint_t>) -> bool>;

/// Function for enumerating skeleton joints.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `joint`: The joint.
///
/// Returns: `true` to continue enumerating to the next joint, `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_skeleton_joint_enumerator_function_t?language=objc)
#[cfg(feature = "objc2")]
pub type ar_skeleton_joint_enumerator_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &ar_skeleton_joint_t) -> bool;
