//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::cell::UnsafeCell;
use core::marker::{PhantomData, PhantomPinned};
use core::ptr::NonNull;
#[cfg(feature = "dispatch2")]
use dispatch2::*;
#[cfg(feature = "objc2")]
use objc2::__framework_prelude::*;

use crate::*;

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_stereo_properties_configuration_t?language=objc)
#[repr(C)]
pub struct ar_stereo_properties_configuration_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_stereo_properties_configuration_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_stereo_properties_provider_t?language=objc)
#[repr(C)]
pub struct ar_stereo_properties_provider_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_stereo_properties_provider_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_viewpoint_properties_t?language=objc)
#[repr(C)]
pub struct ar_viewpoint_properties_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_viewpoint_properties_t {}
);

impl ar_viewpoint_properties_t {
    /// Create an `ar_viewpoint_properties_t`.
    ///
    ///
    /// Returns: A new `ar_viewpoint_properties_t`.
    #[doc(alias = "ar_viewpoint_properties_create")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn new() -> Retained<ar_viewpoint_properties_t> {
        extern "C-unwind" {
            fn ar_viewpoint_properties_create() -> *mut ar_viewpoint_properties_t;
        }
        let ret = unsafe { ar_viewpoint_properties_create() };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }
}

impl ar_stereo_properties_configuration_t {
    /// Create a stereo properties configuration object.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_stereo_properties_configuration_t`.
    #[doc(alias = "ar_stereo_properties_configuration_create")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn new() -> Retained<ar_stereo_properties_configuration_t> {
        extern "C-unwind" {
            fn ar_stereo_properties_configuration_create(
            ) -> *mut ar_stereo_properties_configuration_t;
        }
        let ret = unsafe { ar_stereo_properties_configuration_create() };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }
}

impl ar_stereo_properties_provider_t {
    /// Create a stereo properties provider.
    ///
    ///
    /// Parameter `configuration`: The configuration for the stereo properties provider.
    ///
    /// See: `ar_session_t` to run this provider.
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_stereo_properties_provider_t`.
    ///
    /// # Safety
    ///
    /// `configuration` must implement OS_ar_stereo_properties_configuration.
    #[doc(alias = "ar_stereo_properties_provider_create")]
    #[cfg(all(feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn new(
        configuration: &ar_stereo_properties_configuration_t,
    ) -> Retained<ar_stereo_properties_provider_t> {
        extern "C-unwind" {
            fn ar_stereo_properties_provider_create(
                configuration: &ar_stereo_properties_configuration_t,
            ) -> *mut ar_stereo_properties_provider_t;
        }
        let ret = unsafe { ar_stereo_properties_provider_create(configuration) };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Determines whether this device supports the stereo properties provider.
    ///
    ///
    /// Returns: Returns `true` if the stereo properties provider is supported on this device, `false` otherwise.
    #[doc(alias = "ar_stereo_properties_provider_is_supported")]
    #[inline]
    pub unsafe fn is_supported() -> bool {
        extern "C-unwind" {
            fn ar_stereo_properties_provider_is_supported() -> bool;
        }
        unsafe { ar_stereo_properties_provider_is_supported() }
    }

    /// Get the authorization type required by the stereo properties provider.
    ///
    ///
    /// Returns: Authorization type.
    #[doc(alias = "ar_stereo_properties_provider_get_required_authorization_type")]
    #[cfg(feature = "authorization")]
    #[inline]
    pub unsafe fn required_authorization_type() -> ar_authorization_type_t {
        extern "C-unwind" {
            fn ar_stereo_properties_provider_get_required_authorization_type(
            ) -> ar_authorization_type_t;
        }
        unsafe { ar_stereo_properties_provider_get_required_authorization_type() }
    }

    /// Returns the latest viewpoint properties.
    ///
    ///
    /// Parameter `stereo_properties_provider`: The stereo properties provider.
    ///
    /// Parameter `viewpoint_properties`: The viewpoint properties to fill out.
    ///
    /// Returns: True, if the viewpoint properties were updated.
    ///
    /// # Safety
    ///
    /// - `stereo_properties_provider` must implement OS_ar_stereo_properties_provider.
    /// - `viewpoint_properties` must implement OS_ar_viewpoint_properties.
    #[doc(alias = "ar_stereo_properties_provider_get_viewpoint_properties")]
    #[cfg(all(feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn viewpoint_properties(
        stereo_properties_provider: &ar_stereo_properties_provider_t,
        viewpoint_properties: &ar_viewpoint_properties_t,
    ) -> bool {
        extern "C-unwind" {
            fn ar_stereo_properties_provider_get_viewpoint_properties(
                stereo_properties_provider: &ar_stereo_properties_provider_t,
                viewpoint_properties: &ar_viewpoint_properties_t,
            ) -> bool;
        }
        unsafe {
            ar_stereo_properties_provider_get_viewpoint_properties(
                stereo_properties_provider,
                viewpoint_properties,
            )
        }
    }
}
