//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
#[cfg(feature = "objc2")]
use objc2::__framework_prelude::*;

use crate::*;

/// A correction type to apply for transforms returned from ARKit APIs.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_transform_correction_t?language=objc)
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct ar_transform_correction_t(pub isize);
impl ar_transform_correction_t {
    /// Transforms are unaltered and represent actual locations.
    #[doc(alias = "ar_transform_correction_none")]
    pub const none: Self = Self(0);
    /// Transforms are corrected to render over physical objects in passthrough displays.
    #[doc(alias = "ar_transform_correction_rendered")]
    pub const rendered: Self = Self(1);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ar_transform_correction_t {
    const ENCODING: Encoding = isize::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ar_transform_correction_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}
