//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use core::cell::UnsafeCell;
use core::ffi::*;
use core::marker::{PhantomData, PhantomPinned};
use core::ptr::NonNull;
#[cfg(feature = "dispatch2")]
use dispatch2::*;
#[cfg(feature = "objc2")]
use objc2::__framework_prelude::*;
#[cfg(feature = "objc2-core-foundation")]
use objc2_core_foundation::*;

use crate::*;

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_anchor_t?language=objc)
#[repr(C)]
pub struct ar_world_anchor_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_world_anchor_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_anchors_t?language=objc)
#[repr(C)]
pub struct ar_world_anchors_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_world_anchors_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_tracking_configuration_t?language=objc)
#[repr(C)]
pub struct ar_world_tracking_configuration_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_world_tracking_configuration_t {}
);

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_tracking_provider_t?language=objc)
#[repr(C)]
pub struct ar_world_tracking_provider_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_world_tracking_provider_t {}
);

impl ar_world_anchor_t {
    /// Returns a bool value that indicates whether the two world anchors are equal.
    ///
    ///
    /// Parameter `anchor`: A world anchor to be compared.
    ///
    /// Parameter `other_anchor`: The other world anchor to be compared to.
    ///
    ///
    /// Returns: YES if the world anchors are equal, otherwise NO.
    ///
    /// # Safety
    ///
    /// - `anchor` must implement OS_ar_world_anchor.
    /// - `other_anchor` must implement OS_ar_world_anchor.
    #[doc(alias = "ar_world_anchor_is_equal_to_world_anchor")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn is_equal_to_world_anchor(
        anchor: Option<&ar_world_anchor_t>,
        other_anchor: Option<&ar_world_anchor_t>,
    ) -> bool {
        extern "C-unwind" {
            fn ar_world_anchor_is_equal_to_world_anchor(
                anchor: Option<&ar_world_anchor_t>,
                other_anchor: Option<&ar_world_anchor_t>,
            ) -> bool;
        }
        unsafe { ar_world_anchor_is_equal_to_world_anchor(anchor, other_anchor) }
    }

    /// Get the identifier of an anchor.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    /// Parameter `out_identifier`: A pointer to a UUID to fill out with the anchor identifier. Must be non-null.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_world_anchor.
    #[doc(alias = "ar_world_anchor_get_identifier")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn identifier(anchor: &ar_world_anchor_t, out_identifier: &mut uuid_t) {
        extern "C-unwind" {
            fn ar_world_anchor_get_identifier(
                anchor: &ar_world_anchor_t,
                out_identifier: &mut uuid_t,
            );
        }
        unsafe { ar_world_anchor_get_identifier(anchor, out_identifier) }
    }

    /// Get the timestamp corresponding to an anchor.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    ///
    /// Returns: The timestamp associated with the anchor.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_world_anchor.
    #[doc(alias = "ar_world_anchor_get_timestamp")]
    #[cfg(all(
        feature = "anchor",
        feature = "objc2",
        feature = "objc2-core-foundation"
    ))]
    #[inline]
    pub unsafe fn timestamp(anchor: &ar_world_anchor_t) -> CFTimeInterval {
        extern "C-unwind" {
            fn ar_world_anchor_get_timestamp(anchor: &ar_world_anchor_t) -> CFTimeInterval;
        }
        unsafe { ar_world_anchor_get_timestamp(anchor) }
    }

    /// Determine whether an anchor is tracked.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    ///
    /// Returns: `true` if the anchor is tracked, `false` otherwise.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_world_anchor.
    #[doc(alias = "ar_world_anchor_is_tracked")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn is_tracked(anchor: &ar_world_anchor_t) -> bool {
        extern "C-unwind" {
            fn ar_world_anchor_is_tracked(anchor: &ar_world_anchor_t) -> bool;
        }
        unsafe { ar_world_anchor_is_tracked(anchor) }
    }
}

impl ar_world_anchors_t {
    /// Get the count of world anchors in a collection.
    ///
    ///
    /// Parameter `world_anchors`: The collection of world anchors.
    ///
    ///
    /// Returns: The number of world anchors in the collection.
    ///
    /// # Safety
    ///
    /// `world_anchors` must implement OS_ar_world_anchors.
    #[doc(alias = "ar_world_anchors_get_count")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn count(world_anchors: &ar_world_anchors_t) -> usize {
        extern "C-unwind" {
            fn ar_world_anchors_get_count(world_anchors: &ar_world_anchors_t) -> usize;
        }
        unsafe { ar_world_anchors_get_count(world_anchors) }
    }
}

/// Handler for enumerating a collection of world anchors.
///
///
/// Parameter `world_anchor`: The world anchor.
///
///
/// Returns: `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_anchors_enumerator_t?language=objc)
#[cfg(all(feature = "anchor", feature = "block2", feature = "objc2"))]
pub type ar_world_anchors_enumerator_t =
    block2::Block<'static, fn(NonNull<ar_world_anchor_t>) -> bool>;

impl ar_world_anchors_t {
    /// Enumerate a collection of world anchors.
    ///
    ///
    /// Parameter `world_anchors`: The collection of world anchors.
    ///
    /// Parameter `world_anchors_enumerator`: The enumerator handler.
    ///
    /// # Safety
    ///
    /// `world_anchors` must implement OS_ar_world_anchors.
    #[doc(alias = "ar_world_anchors_enumerate_anchors")]
    #[cfg(all(feature = "anchor", feature = "block2", feature = "objc2"))]
    #[inline]
    pub unsafe fn enumerate_anchors(
        world_anchors: &ar_world_anchors_t,
        world_anchors_enumerator: &ar_world_anchors_enumerator_t,
    ) {
        extern "C-unwind" {
            fn ar_world_anchors_enumerate_anchors(
                world_anchors: &ar_world_anchors_t,
                world_anchors_enumerator: &ar_world_anchors_enumerator_t,
            );
        }
        unsafe { ar_world_anchors_enumerate_anchors(world_anchors, world_anchors_enumerator) }
    }
}

/// Function for enumerating a collection of world anchors.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `world_anchor`: The world anchor.
///
///
/// Returns: `true` to continue enumerating, or `false` to stop enumerating.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_anchors_enumerator_function_t?language=objc)
#[cfg(all(feature = "anchor", feature = "objc2"))]
pub type ar_world_anchors_enumerator_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &ar_world_anchor_t) -> bool;

impl ar_world_anchors_t {
    /// Enumerate a collection of world anchors using a function.
    ///
    ///
    /// Parameter `world_anchors`: The collection of world anchors.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `world_anchors_enumerator_function`: The enumerator function.
    ///
    /// # Safety
    ///
    /// - `world_anchors` must implement OS_ar_world_anchors.
    /// - `context` must be a valid pointer or null.
    /// - `world_anchors_enumerator_function` must be implemented correctly.
    #[doc(alias = "ar_world_anchors_enumerate_anchors_f")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn enumerate_anchors_f(
        world_anchors: &ar_world_anchors_t,
        context: *mut c_void,
        world_anchors_enumerator_function: ar_world_anchors_enumerator_function_t,
    ) {
        extern "C-unwind" {
            fn ar_world_anchors_enumerate_anchors_f(
                world_anchors: &ar_world_anchors_t,
                context: *mut c_void,
                world_anchors_enumerator_function: ar_world_anchors_enumerator_function_t,
            );
        }
        unsafe {
            ar_world_anchors_enumerate_anchors_f(
                world_anchors,
                context,
                world_anchors_enumerator_function,
            )
        }
    }
}

impl ar_world_tracking_configuration_t {
    /// Create a world tracking configuration.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_world_tracking_configuration_t`.
    #[doc(alias = "ar_world_tracking_configuration_create")]
    #[cfg(feature = "objc2")]
    #[inline]
    pub unsafe fn new() -> Retained<ar_world_tracking_configuration_t> {
        extern "C-unwind" {
            fn ar_world_tracking_configuration_create() -> *mut ar_world_tracking_configuration_t;
        }
        let ret = unsafe { ar_world_tracking_configuration_create() };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }
}

impl ar_world_tracking_provider_t {
    /// Create a world tracking provider.
    ///
    ///
    /// Parameter `world_tracking_configuration`: The configuration for world tracking.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_world_tracking_provider_t`.
    ///
    /// # Safety
    ///
    /// `world_tracking_configuration` must implement OS_ar_world_tracking_configuration.
    #[doc(alias = "ar_world_tracking_provider_create")]
    #[cfg(all(feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn new(
        world_tracking_configuration: &ar_world_tracking_configuration_t,
    ) -> Retained<ar_world_tracking_provider_t> {
        extern "C-unwind" {
            fn ar_world_tracking_provider_create(
                world_tracking_configuration: &ar_world_tracking_configuration_t,
            ) -> *mut ar_world_tracking_provider_t;
        }
        let ret = unsafe { ar_world_tracking_provider_create(world_tracking_configuration) };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }
}

/// Function called when a request to copy all known world anchors has completed (successfully or not).
///
///
/// Parameter `all_anchors`: The nullable collection of known world anchors. Passes null if data provider is not running and for other errors.
///
///
/// Note: The results will be accurate at the time of callback, but not necessarily at the time of the request.
///
/// Note: The returned anchors support ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the anchors.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_tracking_provider_copy_all_world_anchors_completion_function_t?language=objc)
#[cfg(feature = "objc2")]
pub type ar_world_tracking_provider_copy_all_world_anchors_completion_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, Option<&ar_world_anchors_t>);

impl ar_world_tracking_provider_t {
    /// Copies all known world anchors from the world tracking provider asynchronously.
    ///
    ///
    /// Parameter `world_tracking_provider`: The world tracking provider.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `copy_all_anchors_completion_handler_function`: The function to be called with the result of the request for all known world anchors.
    ///
    ///
    /// Note: This is not a blocking call. It will return all anchors that have been added successfully before the completion handler is called.
    ///
    /// # Safety
    ///
    /// - `world_tracking_provider` must implement OS_ar_world_tracking_provider.
    /// - `context` must be a valid pointer or null.
    /// - `copy_all_anchors_completion_handler_function` must be implemented correctly.
    #[doc(alias = "ar_world_tracking_provider_copy_all_world_anchors_f")]
    #[cfg(all(feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn copy_all_world_anchors_f(
        world_tracking_provider: &ar_world_tracking_provider_t,
        context: *mut c_void,
        copy_all_anchors_completion_handler_function: Option<
            ar_world_tracking_provider_copy_all_world_anchors_completion_function_t,
        >,
    ) {
        extern "C-unwind" {
            fn ar_world_tracking_provider_copy_all_world_anchors_f(
                world_tracking_provider: &ar_world_tracking_provider_t,
                context: *mut c_void,
                copy_all_anchors_completion_handler_function: Option<
                    ar_world_tracking_provider_copy_all_world_anchors_completion_function_t,
                >,
            );
        }
        unsafe {
            ar_world_tracking_provider_copy_all_world_anchors_f(
                world_tracking_provider,
                context,
                copy_all_anchors_completion_handler_function,
            )
        }
    }
}

/// Handler called when a request to copy all known world anchors has completed (successfully or not).
///
///
/// Parameter `all_anchors`: The nullable collection of known world anchors. Passes null if data provider is not running and for other errors.
///
///
/// Note: The results will be accurate at the time of callback, but not necessarily at the time of the request.
///
/// Note: The returned anchors support ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the anchors.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_tracking_provider_copy_all_world_anchors_completion_handler_t?language=objc)
#[cfg(all(feature = "block2", feature = "objc2"))]
pub type ar_world_tracking_provider_copy_all_world_anchors_completion_handler_t =
    block2::Block<'static, fn(*mut ar_world_anchors_t)>;

impl ar_world_tracking_provider_t {
    /// Copies all known world anchors from the world tracking provider asynchronously.
    ///
    ///
    /// Parameter `world_tracking_provider`: The world tracking provider.
    ///
    /// Parameter `copy_all_anchors_completion_handler`: The handler to be called with the result of the request for all known world anchors.
    ///
    ///
    /// Note: This is not a blocking call. It will return all anchors that have been added successfully before the completion handler is called.
    ///
    /// # Safety
    ///
    /// `world_tracking_provider` must implement OS_ar_world_tracking_provider.
    #[doc(alias = "ar_world_tracking_provider_copy_all_world_anchors")]
    #[cfg(all(feature = "block2", feature = "data_provider", feature = "objc2"))]
    #[inline]
    pub unsafe fn copy_all_world_anchors(
        world_tracking_provider: &ar_world_tracking_provider_t,
        copy_all_anchors_completion_handler: &ar_world_tracking_provider_copy_all_world_anchors_completion_handler_t,
    ) {
        extern "C-unwind" {
            fn ar_world_tracking_provider_copy_all_world_anchors(
                world_tracking_provider: &ar_world_tracking_provider_t,
                copy_all_anchors_completion_handler: &ar_world_tracking_provider_copy_all_world_anchors_completion_handler_t,
            );
        }
        unsafe {
            ar_world_tracking_provider_copy_all_world_anchors(
                world_tracking_provider,
                copy_all_anchors_completion_handler,
            )
        }
    }
}

/// Handler called when there are updates to world anchors. This includes updates to persisted world anchors from previous runs of the app.
///
///
/// Parameter `added_anchors`: The collection of world anchors that were added.
///
/// Parameter `updated_anchors`: The collection of world anchors that were updated.
///
/// Parameter `removed_anchors`: The collection of world anchors that were removed.
///
///
/// Note: This handler will also be called for persisted world anchors from previous runs of the app, after the world tracking provider has been started.
/// World anchors persist across device restarts until they are explicitly removed. Identify the anchors you want to react to using
/// `ar_anchor_get_identifier`.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_tracking_anchor_update_handler_t?language=objc)
#[cfg(all(feature = "block2", feature = "objc2"))]
pub type ar_world_tracking_anchor_update_handler_t = block2::Block<
    'static,
    fn(NonNull<ar_world_anchors_t>, NonNull<ar_world_anchors_t>, NonNull<ar_world_anchors_t>),
>;

impl ar_world_tracking_provider_t {
    /// Set the handler for receiving world tracking anchor updates.
    ///
    ///
    /// Parameter `world_tracking_provider`: The world tracking provider.
    ///
    /// Parameter `world_tracking_updates_queue`: The queue on which the handler will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `world_tracking_anchor_update_handler`: The handler to be called when new world anchor data arrives.
    ///
    ///
    /// Note: Setting this handler will override the function set using `ar_world_tracking_provider_set_anchor_update_handler_f`.
    ///
    /// # Safety
    ///
    /// - `world_tracking_provider` must implement OS_ar_world_tracking_provider.
    /// - `world_tracking_updates_queue` possibly has additional threading requirements.
    #[doc(alias = "ar_world_tracking_provider_set_anchor_update_handler")]
    #[cfg(all(
        feature = "block2",
        feature = "data_provider",
        feature = "dispatch2",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn set_anchor_update_handler(
        world_tracking_provider: &ar_world_tracking_provider_t,
        world_tracking_updates_queue: Option<&DispatchQueue>,
        world_tracking_anchor_update_handler: Option<&ar_world_tracking_anchor_update_handler_t>,
    ) {
        extern "C-unwind" {
            fn ar_world_tracking_provider_set_anchor_update_handler(
                world_tracking_provider: &ar_world_tracking_provider_t,
                world_tracking_updates_queue: Option<&DispatchQueue>,
                world_tracking_anchor_update_handler: Option<
                    &ar_world_tracking_anchor_update_handler_t,
                >,
            );
        }
        unsafe {
            ar_world_tracking_provider_set_anchor_update_handler(
                world_tracking_provider,
                world_tracking_updates_queue,
                world_tracking_anchor_update_handler,
            )
        }
    }
}

/// Function called when there are updates to world anchors. This includes updates to persisted world anchors from previous runs of the app.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `added_anchors`: The collection of world anchors that were added.
///
/// Parameter `updated_anchors`: The collection of world anchors that were updated.
///
/// Parameter `removed_anchors`: The collection of world anchors that were removed.
///
///
/// Note: This function will also be called for persisted world anchors from previous runs of the app, after the world tracking provider has been
/// started. World anchors persist across device restarts until they are explicitly removed. Identify the anchors you want to react to using
/// `ar_anchor_get_identifier`.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_tracking_anchor_update_handler_function_t?language=objc)
#[cfg(feature = "objc2")]
pub type ar_world_tracking_anchor_update_handler_function_t = unsafe extern "C-unwind" fn(
    *mut c_void,
    &ar_world_anchors_t,
    &ar_world_anchors_t,
    &ar_world_anchors_t,
);

impl ar_world_tracking_provider_t {
    /// Set the function for receiving world tracking anchor updates.
    ///
    ///
    /// Parameter `world_tracking_provider`: The world tracking provider.
    ///
    /// Parameter `world_tracking_updates_queue`: The queue on which the function will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `world_tracking_anchor_update_handler_function`: The function to be called when new world anchor data arrives.
    ///
    ///
    /// Note: Setting this function will override the handler set using `ar_world_tracking_provider_set_anchor_update_handler`.
    ///
    /// # Safety
    ///
    /// - `world_tracking_provider` must implement OS_ar_world_tracking_provider.
    /// - `world_tracking_updates_queue` possibly has additional threading requirements.
    /// - `context` must be a valid pointer or null.
    /// - `world_tracking_anchor_update_handler_function` must be implemented correctly.
    #[doc(alias = "ar_world_tracking_provider_set_anchor_update_handler_f")]
    #[cfg(all(feature = "data_provider", feature = "dispatch2", feature = "objc2"))]
    #[inline]
    pub unsafe fn set_anchor_update_handler_f(
        world_tracking_provider: &ar_world_tracking_provider_t,
        world_tracking_updates_queue: Option<&DispatchQueue>,
        context: *mut c_void,
        world_tracking_anchor_update_handler_function: Option<
            ar_world_tracking_anchor_update_handler_function_t,
        >,
    ) {
        extern "C-unwind" {
            fn ar_world_tracking_provider_set_anchor_update_handler_f(
                world_tracking_provider: &ar_world_tracking_provider_t,
                world_tracking_updates_queue: Option<&DispatchQueue>,
                context: *mut c_void,
                world_tracking_anchor_update_handler_function: Option<
                    ar_world_tracking_anchor_update_handler_function_t,
                >,
            );
        }
        unsafe {
            ar_world_tracking_provider_set_anchor_update_handler_f(
                world_tracking_provider,
                world_tracking_updates_queue,
                context,
                world_tracking_anchor_update_handler_function,
            )
        }
    }
}

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_tracking_error_code_t?language=objc)
#[cfg(feature = "error")]
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ar_world_tracking_error_code_t(pub ar_error_code_t);
#[cfg(feature = "error")]
impl ar_world_tracking_error_code_t {
    /// Error code indicating that a world anchor failed to be added.
    #[doc(alias = "ar_world_tracking_error_code_add_anchor_failed")]
    pub const add_anchor_failed: Self = Self(200);
    /// Error code indicating that the maximum amount of world anchors have been added.
    #[doc(alias = "ar_world_tracking_error_code_anchor_max_limit_reached")]
    pub const anchor_max_limit_reached: Self = Self(201);
    /// Error code indicating that a world anchor failed to be removed.
    #[doc(alias = "ar_world_tracking_error_code_remove_anchor_failed")]
    pub const remove_anchor_failed: Self = Self(202);
}

#[cfg(all(feature = "error", feature = "objc2"))]
unsafe impl Encode for ar_world_tracking_error_code_t {
    const ENCODING: Encoding = ar_error_code_t::ENCODING;
}

#[cfg(all(feature = "error", feature = "objc2"))]
unsafe impl RefEncode for ar_world_tracking_error_code_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

impl ar_world_tracking_provider_t {
    /// Determine whether this device supports the world tracking provider.
    ///
    ///
    /// Returns: `true` if the world tracking provider is supported on this device, `false` otherwise.
    #[doc(alias = "ar_world_tracking_provider_is_supported")]
    #[inline]
    pub unsafe fn is_supported() -> bool {
        extern "C-unwind" {
            fn ar_world_tracking_provider_is_supported() -> bool;
        }
        unsafe { ar_world_tracking_provider_is_supported() }
    }
}

/// Handler called when a request to add a world anchor has completed (successfully or not).
///
///
/// Parameter `world_anchor`: The world anchor to be added to the world tracking provider.
///
/// Parameter `successful`: `true` if the world anchor was successfully added to the world tracking provider, `false` otherwise.
///
/// Parameter `error`: The error that occurred, if any. The returned error supports ARC. In non-ARC files, use `ar_release()` to release the error.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_tracking_add_anchor_completion_handler_t?language=objc)
#[cfg(all(
    feature = "anchor",
    feature = "block2",
    feature = "error",
    feature = "objc2"
))]
pub type ar_world_tracking_add_anchor_completion_handler_t =
    block2::Block<'static, fn(NonNull<ar_world_anchor_t>, bool, *mut ar_error_t)>;

impl ar_world_tracking_provider_t {
    /// Add a world anchor to the world tracking provider. This anchor will be persisted across device restarts unless explicitly removed.
    ///
    ///
    /// Parameter `world_tracking_provider`: The world tracking provider.
    ///
    /// Parameter `world_anchor`: The world anchor to add.
    ///
    /// Parameter `add_anchor_completion_handler`: The handler to be called after the request to add the world anchor to the world tracking provider completes.
    ///
    /// # Safety
    ///
    /// - `world_tracking_provider` must implement OS_ar_world_tracking_provider.
    /// - `world_anchor` must implement OS_ar_world_anchor.
    #[doc(alias = "ar_world_tracking_provider_add_anchor")]
    #[cfg(all(
        feature = "anchor",
        feature = "block2",
        feature = "data_provider",
        feature = "error",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn add_anchor(
        world_tracking_provider: &ar_world_tracking_provider_t,
        world_anchor: &ar_world_anchor_t,
        add_anchor_completion_handler: &ar_world_tracking_add_anchor_completion_handler_t,
    ) {
        extern "C-unwind" {
            fn ar_world_tracking_provider_add_anchor(
                world_tracking_provider: &ar_world_tracking_provider_t,
                world_anchor: &ar_world_anchor_t,
                add_anchor_completion_handler: &ar_world_tracking_add_anchor_completion_handler_t,
            );
        }
        unsafe {
            ar_world_tracking_provider_add_anchor(
                world_tracking_provider,
                world_anchor,
                add_anchor_completion_handler,
            )
        }
    }
}

/// Function called when a request to add a world anchor has completed (successfully or not).
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `world_anchor`: The world anchor to be added to the world tracking provider.
///
/// Parameter `successful`: `true` if the world anchor was successfully added to the world tracking provider, `false` otherwise.
///
/// Parameter `error`: The error that occurred, if any. The returned error supports ARC. In non-ARC files, use `ar_release()` to release the error.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_tracking_add_anchor_completion_handler_function_t?language=objc)
#[cfg(all(feature = "anchor", feature = "error", feature = "objc2"))]
pub type ar_world_tracking_add_anchor_completion_handler_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &ar_world_anchor_t, bool, Option<&ar_error_t>);

impl ar_world_tracking_provider_t {
    /// Add a world anchor to the world tracking provider. This anchor will be persisted across device restarts unless explicitly removed.
    ///
    ///
    /// Parameter `world_tracking_provider`: The world tracking provider.
    ///
    /// Parameter `world_anchor`: The world anchor to add.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `add_anchor_completion_handler_function`: The function to be called after the request to add the world anchor to the world tracking provider
    /// completes.
    ///
    /// # Safety
    ///
    /// - `world_tracking_provider` must implement OS_ar_world_tracking_provider.
    /// - `world_anchor` must implement OS_ar_world_anchor.
    /// - `context` must be a valid pointer or null.
    /// - `add_anchor_completion_handler_function` must be implemented correctly.
    #[doc(alias = "ar_world_tracking_provider_add_anchor_f")]
    #[cfg(all(
        feature = "anchor",
        feature = "data_provider",
        feature = "error",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn add_anchor_f(
        world_tracking_provider: &ar_world_tracking_provider_t,
        world_anchor: &ar_world_anchor_t,
        context: *mut c_void,
        add_anchor_completion_handler_function: ar_world_tracking_add_anchor_completion_handler_function_t,
    ) {
        extern "C-unwind" {
            fn ar_world_tracking_provider_add_anchor_f(
                world_tracking_provider: &ar_world_tracking_provider_t,
                world_anchor: &ar_world_anchor_t,
                context: *mut c_void,
                add_anchor_completion_handler_function: ar_world_tracking_add_anchor_completion_handler_function_t,
            );
        }
        unsafe {
            ar_world_tracking_provider_add_anchor_f(
                world_tracking_provider,
                world_anchor,
                context,
                add_anchor_completion_handler_function,
            )
        }
    }
}

/// Handler called when a request to remove a world anchor has completed (successfully or not).
///
///
/// Parameter `world_anchor`: The world anchor to be removed from the world tracking provider.
///
/// Parameter `successful`: `true` if the world anchor was successfully removed from the world tracking provider, `false` otherwise.
///
/// Parameter `error`: The error that occurred, if any. The returned error supports ARC. In non-ARC files, use `ar_release()` to release the error.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_tracking_remove_anchor_completion_handler_t?language=objc)
#[cfg(all(
    feature = "anchor",
    feature = "block2",
    feature = "error",
    feature = "objc2"
))]
pub type ar_world_tracking_remove_anchor_completion_handler_t =
    block2::Block<'static, fn(NonNull<ar_world_anchor_t>, bool, *mut ar_error_t)>;

impl ar_world_tracking_provider_t {
    /// Remove a world anchor from the world tracking provider.
    ///
    ///
    /// Parameter `world_tracking_provider`: The world tracking provider.
    ///
    /// Parameter `world_anchor`: The world anchor to remove.
    ///
    /// Parameter `remove_anchor_completion_handler`: The handler to be called after the request to remove the world anchor from the world tracking provider
    /// completes.
    ///
    /// # Safety
    ///
    /// - `world_tracking_provider` must implement OS_ar_world_tracking_provider.
    /// - `world_anchor` must implement OS_ar_world_anchor.
    #[doc(alias = "ar_world_tracking_provider_remove_anchor")]
    #[cfg(all(
        feature = "anchor",
        feature = "block2",
        feature = "data_provider",
        feature = "error",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn remove_anchor(
        world_tracking_provider: &ar_world_tracking_provider_t,
        world_anchor: &ar_world_anchor_t,
        remove_anchor_completion_handler: &ar_world_tracking_remove_anchor_completion_handler_t,
    ) {
        extern "C-unwind" {
            fn ar_world_tracking_provider_remove_anchor(
                world_tracking_provider: &ar_world_tracking_provider_t,
                world_anchor: &ar_world_anchor_t,
                remove_anchor_completion_handler: &ar_world_tracking_remove_anchor_completion_handler_t,
            );
        }
        unsafe {
            ar_world_tracking_provider_remove_anchor(
                world_tracking_provider,
                world_anchor,
                remove_anchor_completion_handler,
            )
        }
    }

    /// Remove a world anchor from the world tracking provider using its identifier.
    ///
    ///
    /// Parameter `world_tracking_provider`: The world tracking provider.
    ///
    /// Parameter `anchor_identifier`: The identifier of the world anchor to remove.
    ///
    /// Parameter `remove_anchor_completion_handler`: The handler to be called after the request to remove the world anchor from the world tracking provider
    /// completes.
    ///
    /// # Safety
    ///
    /// `world_tracking_provider` must implement OS_ar_world_tracking_provider.
    #[doc(alias = "ar_world_tracking_provider_remove_anchor_with_identifier")]
    #[cfg(all(
        feature = "anchor",
        feature = "block2",
        feature = "data_provider",
        feature = "error",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn remove_anchor_with_identifier(
        world_tracking_provider: &ar_world_tracking_provider_t,
        anchor_identifier: &mut uuid_t,
        remove_anchor_completion_handler: &ar_world_tracking_remove_anchor_completion_handler_t,
    ) {
        extern "C-unwind" {
            fn ar_world_tracking_provider_remove_anchor_with_identifier(
                world_tracking_provider: &ar_world_tracking_provider_t,
                anchor_identifier: &mut uuid_t,
                remove_anchor_completion_handler: &ar_world_tracking_remove_anchor_completion_handler_t,
            );
        }
        unsafe {
            ar_world_tracking_provider_remove_anchor_with_identifier(
                world_tracking_provider,
                anchor_identifier,
                remove_anchor_completion_handler,
            )
        }
    }
}

/// Function called when a request to remove a world anchor has completed (successfully or not).
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `world_anchor`: The world anchor to be removed from the world tracking provider.
///
/// Parameter `successful`: `true` if the world anchor was successfully removed from the world tracking provider, `false` otherwise.
///
/// Parameter `error`: The error that occurred, if any. The returned error supports ARC. In non-ARC files, use `ar_release()` to release the error.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_tracking_remove_anchor_completion_handler_function_t?language=objc)
#[cfg(all(feature = "anchor", feature = "error", feature = "objc2"))]
pub type ar_world_tracking_remove_anchor_completion_handler_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, &ar_world_anchor_t, bool, Option<&ar_error_t>);

impl ar_world_tracking_provider_t {
    /// Remove a world anchor from the world tracking provider.
    ///
    ///
    /// Parameter `world_tracking_provider`: The world tracking provider.
    ///
    /// Parameter `world_anchor`: The world anchor to remove.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `remove_anchor_completion_handler_function`: The function to be called after the request to remove the world anchor from the world tracking
    /// provider completes.
    ///
    /// # Safety
    ///
    /// - `world_tracking_provider` must implement OS_ar_world_tracking_provider.
    /// - `world_anchor` must implement OS_ar_world_anchor.
    /// - `context` must be a valid pointer or null.
    /// - `remove_anchor_completion_handler_function` must be implemented correctly.
    #[doc(alias = "ar_world_tracking_provider_remove_anchor_f")]
    #[cfg(all(
        feature = "anchor",
        feature = "data_provider",
        feature = "error",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn remove_anchor_f(
        world_tracking_provider: &ar_world_tracking_provider_t,
        world_anchor: &ar_world_anchor_t,
        context: *mut c_void,
        remove_anchor_completion_handler_function: ar_world_tracking_remove_anchor_completion_handler_function_t,
    ) {
        extern "C-unwind" {
            fn ar_world_tracking_provider_remove_anchor_f(
                world_tracking_provider: &ar_world_tracking_provider_t,
                world_anchor: &ar_world_anchor_t,
                context: *mut c_void,
                remove_anchor_completion_handler_function: ar_world_tracking_remove_anchor_completion_handler_function_t,
            );
        }
        unsafe {
            ar_world_tracking_provider_remove_anchor_f(
                world_tracking_provider,
                world_anchor,
                context,
                remove_anchor_completion_handler_function,
            )
        }
    }

    /// Remove a world anchor from the world tracking provider using its identifier.
    ///
    ///
    /// Parameter `world_tracking_provider`: The world tracking provider.
    ///
    /// Parameter `anchor_identifier`: The identifier of the world anchor to remove.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `remove_anchor_completion_handler_function`: The function to be called after the request to remove the world anchor from the world tracking
    /// provider completes.
    ///
    /// # Safety
    ///
    /// - `world_tracking_provider` must implement OS_ar_world_tracking_provider.
    /// - `context` must be a valid pointer or null.
    /// - `remove_anchor_completion_handler_function` must be implemented correctly.
    #[doc(alias = "ar_world_tracking_provider_remove_anchor_with_identifier_f")]
    #[cfg(all(
        feature = "anchor",
        feature = "data_provider",
        feature = "error",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn remove_anchor_with_identifier_f(
        world_tracking_provider: &ar_world_tracking_provider_t,
        anchor_identifier: &mut uuid_t,
        context: *mut c_void,
        remove_anchor_completion_handler_function: ar_world_tracking_remove_anchor_completion_handler_function_t,
    ) {
        extern "C-unwind" {
            fn ar_world_tracking_provider_remove_anchor_with_identifier_f(
                world_tracking_provider: &ar_world_tracking_provider_t,
                anchor_identifier: &mut uuid_t,
                context: *mut c_void,
                remove_anchor_completion_handler_function: ar_world_tracking_remove_anchor_completion_handler_function_t,
            );
        }
        unsafe {
            ar_world_tracking_provider_remove_anchor_with_identifier_f(
                world_tracking_provider,
                anchor_identifier,
                context,
                remove_anchor_completion_handler_function,
            )
        }
    }
}

/// Function called when a request to remove all known world anchors has completed (successfully or not).
///
///
/// Parameter `successful`: `true` if all anchors were successfully removed from the world tracking provider, `false` otherwise.
///
/// Parameter `error`: The error that occurred, if any. The returned error supports ARC. In non-ARC files, use `ar_release()` to release the error.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_tracking_remove_all_anchors_completion_handler_t?language=objc)
#[cfg(all(feature = "block2", feature = "error", feature = "objc2"))]
pub type ar_world_tracking_remove_all_anchors_completion_handler_t =
    block2::Block<'static, fn(bool, *mut ar_error_t)>;

impl ar_world_tracking_provider_t {
    /// Removes all known world anchors from the world tracking provider asynchronously.
    ///
    ///
    /// Parameter `world_tracking_provider`: The world tracking provider.
    ///
    /// Parameter `remove_all_anchors_completion_handler`: The handler to be called after the request to remove all known world anchors from
    /// the world tracking provider completes.
    ///
    /// # Safety
    ///
    /// `world_tracking_provider` must implement OS_ar_world_tracking_provider.
    #[doc(alias = "ar_world_tracking_provider_remove_all_anchors")]
    #[cfg(all(
        feature = "block2",
        feature = "data_provider",
        feature = "error",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn remove_all_anchors(
        world_tracking_provider: &ar_world_tracking_provider_t,
        remove_all_anchors_completion_handler: &ar_world_tracking_remove_all_anchors_completion_handler_t,
    ) {
        extern "C-unwind" {
            fn ar_world_tracking_provider_remove_all_anchors(
                world_tracking_provider: &ar_world_tracking_provider_t,
                remove_all_anchors_completion_handler: &ar_world_tracking_remove_all_anchors_completion_handler_t,
            );
        }
        unsafe {
            ar_world_tracking_provider_remove_all_anchors(
                world_tracking_provider,
                remove_all_anchors_completion_handler,
            )
        }
    }
}

/// Function called when a request to remove all known world anchors has completed (successfully or not).
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `successful`: `true` if all anchors were successfully removed from the world tracking provider, `false` otherwise.
///
/// Parameter `error`: The error that occurred, if any. The returned error supports ARC. In non-ARC files, use `ar_release()` to release the error.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_tracking_remove_all_anchors_completion_handler_function_t?language=objc)
#[cfg(all(feature = "block2", feature = "error", feature = "objc2"))]
pub type ar_world_tracking_remove_all_anchors_completion_handler_function_t =
    block2::Block<'static, fn(*mut c_void, bool, *mut ar_error_t)>;

impl ar_world_tracking_provider_t {
    /// Removes all known world anchors from the world tracking provider asynchronously.
    ///
    ///
    /// Parameter `world_tracking_provider`: The world tracking provider.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `remove_all_anchors_completion_handler_function`: The handler to be called after the request to remove all known world anchors from
    /// the world tracking provider completes.
    ///
    /// # Safety
    ///
    /// - `world_tracking_provider` must implement OS_ar_world_tracking_provider.
    /// - `context` must be a valid pointer or null.
    #[doc(alias = "ar_world_tracking_provider_remove_all_anchors_f")]
    #[cfg(all(
        feature = "block2",
        feature = "data_provider",
        feature = "error",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn remove_all_anchors_f(
        world_tracking_provider: &ar_world_tracking_provider_t,
        context: *mut c_void,
        remove_all_anchors_completion_handler_function: &ar_world_tracking_remove_all_anchors_completion_handler_function_t,
    ) {
        extern "C-unwind" {
            fn ar_world_tracking_provider_remove_all_anchors_f(
                world_tracking_provider: &ar_world_tracking_provider_t,
                context: *mut c_void,
                remove_all_anchors_completion_handler_function: &ar_world_tracking_remove_all_anchors_completion_handler_function_t,
            );
        }
        unsafe {
            ar_world_tracking_provider_remove_all_anchors_f(
                world_tracking_provider,
                context,
                remove_all_anchors_completion_handler_function,
            )
        }
    }
}

impl ar_world_anchor_t {
    /// Check if a world anchor is marked to be shared with nearby participants.
    ///
    ///
    /// Parameter `world_anchor`: The world anchor.
    ///
    ///
    /// Returns: `true` if the world anchor is marked to be shared with nearby participants, `false` otherwise.
    ///
    /// # Safety
    ///
    /// `world_anchor` must implement OS_ar_world_anchor.
    #[doc(alias = "ar_world_anchor_is_shared_with_nearby_participants")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn is_shared_with_nearby_participants(world_anchor: &ar_world_anchor_t) -> bool {
        extern "C-unwind" {
            fn ar_world_anchor_is_shared_with_nearby_participants(
                world_anchor: &ar_world_anchor_t,
            ) -> bool;
        }
        unsafe { ar_world_anchor_is_shared_with_nearby_participants(world_anchor) }
    }
}

/// Enumeration indicating the availability of world anchor sharing.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_anchor_sharing_availability_t?language=objc)
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct ar_world_anchor_sharing_availability_t(pub isize);
impl ar_world_anchor_sharing_availability_t {
    /// Enumeration indicating the availability of world anchor sharing.
    #[doc(alias = "ar_world_anchor_sharing_availability_available")]
    pub const available: Self = Self(0);
    /// Enumeration indicating the availability of world anchor sharing.
    #[doc(alias = "ar_world_anchor_sharing_availability_unavailable")]
    pub const unavailable: Self = Self(1);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ar_world_anchor_sharing_availability_t {
    const ENCODING: Encoding = isize::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ar_world_anchor_sharing_availability_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// Handler called when there is a change in world anchor sharing availability.
///
///
/// Parameter `sharing_availability`: World anchor sharing availability.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_anchor_sharing_availability_update_handler_t?language=objc)
#[cfg(feature = "block2")]
pub type ar_world_anchor_sharing_availability_update_handler_t =
    block2::Block<'static, fn(ar_world_anchor_sharing_availability_t)>;

impl ar_world_tracking_provider_t {
    /// Set the handler for receiving world anchor sharing availability updates.
    ///
    ///
    /// Parameter `world_tracking_provider`: The world tracking provider.
    ///
    /// Parameter `world_tracking_updates_queue`: The queue on which the handler will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `world_anchor_sharing_availability_update_handler`: The handler to be called when there is a change in world anchor sharing availability.
    ///
    /// # Safety
    ///
    /// - `world_tracking_provider` must implement OS_ar_world_tracking_provider.
    /// - `world_tracking_updates_queue` possibly has additional threading requirements.
    #[doc(
        alias = "ar_world_tracking_provider_set_world_anchor_sharing_availability_update_handler"
    )]
    #[cfg(all(
        feature = "block2",
        feature = "data_provider",
        feature = "dispatch2",
        feature = "objc2"
    ))]
    #[inline]
    pub unsafe fn set_world_anchor_sharing_availability_update_handler(
        world_tracking_provider: &ar_world_tracking_provider_t,
        world_tracking_updates_queue: Option<&DispatchQueue>,
        world_anchor_sharing_availability_update_handler: Option<
            &ar_world_anchor_sharing_availability_update_handler_t,
        >,
    ) {
        extern "C-unwind" {
            fn ar_world_tracking_provider_set_world_anchor_sharing_availability_update_handler(
                world_tracking_provider: &ar_world_tracking_provider_t,
                world_tracking_updates_queue: Option<&DispatchQueue>,
                world_anchor_sharing_availability_update_handler: Option<
                    &ar_world_anchor_sharing_availability_update_handler_t,
                >,
            );
        }
        unsafe {
            ar_world_tracking_provider_set_world_anchor_sharing_availability_update_handler(
                world_tracking_provider,
                world_tracking_updates_queue,
                world_anchor_sharing_availability_update_handler,
            )
        }
    }
}

/// Function pointer called when there is a change in world anchor sharing availability.
///
///
/// Parameter `context`: The application-defined context.
///
/// Parameter `sharing_availability`: World anchor sharing availability.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_world_anchor_sharing_availability_update_handler_function_t?language=objc)
pub type ar_world_anchor_sharing_availability_update_handler_function_t =
    unsafe extern "C-unwind" fn(*mut c_void, ar_world_anchor_sharing_availability_t);

impl ar_world_tracking_provider_t {
    /// Set the function for receiving world anchor sharing availability updates
    ///
    ///
    /// Parameter `world_tracking_provider`: The world tracking provider.
    ///
    /// Parameter `world_tracking_updates_queue`: The queue on which the handler will be called. Passing NULL will default to the main queue.
    ///
    /// Parameter `context`: The application-defined context parameter to pass to the function.
    ///
    /// Parameter `world_anchor_sharing_availability_update_handler_function`: The function to be called when there is a change in world anchor sharing
    /// availability.
    ///
    /// # Safety
    ///
    /// - `world_tracking_provider` must implement OS_ar_world_tracking_provider.
    /// - `world_tracking_updates_queue` possibly has additional threading requirements.
    /// - `context` must be a valid pointer or null.
    /// - `world_anchor_sharing_availability_update_handler_function` must be implemented correctly.
    #[doc(
        alias = "ar_world_tracking_provider_set_world_anchor_sharing_availability_update_handler_f"
    )]
    #[cfg(all(feature = "data_provider", feature = "dispatch2", feature = "objc2"))]
    #[inline]
    pub unsafe fn set_world_anchor_sharing_availability_update_handler_f(
        world_tracking_provider: &ar_world_tracking_provider_t,
        world_tracking_updates_queue: Option<&DispatchQueue>,
        context: *mut c_void,
        world_anchor_sharing_availability_update_handler_function: Option<
            ar_world_anchor_sharing_availability_update_handler_function_t,
        >,
    ) {
        extern "C-unwind" {
            fn ar_world_tracking_provider_set_world_anchor_sharing_availability_update_handler_f(
                world_tracking_provider: &ar_world_tracking_provider_t,
                world_tracking_updates_queue: Option<&DispatchQueue>,
                context: *mut c_void,
                world_anchor_sharing_availability_update_handler_function: Option<
                    ar_world_anchor_sharing_availability_update_handler_function_t,
                >,
            );
        }
        unsafe {
            ar_world_tracking_provider_set_world_anchor_sharing_availability_update_handler_f(
                world_tracking_provider,
                world_tracking_updates_queue,
                context,
                world_anchor_sharing_availability_update_handler_function,
            )
        }
    }
}

/// [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_device_anchor_t?language=objc)
#[repr(C)]
pub struct ar_device_anchor_t {
    inner: [u8; 0],
    _p: UnsafeCell<PhantomData<(*const UnsafeCell<()>, PhantomPinned)>>,
}

dispatch_object!(
    unsafe impl ar_device_anchor_t {}
);

/// Return status enum values for getting the device anchor at a specified timestamp from the world tracking provider.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_device_anchor_query_status_t?language=objc)
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct ar_device_anchor_query_status_t(pub isize);
impl ar_device_anchor_query_status_t {
    /// Return status enum values for getting the device anchor at a specified timestamp from the world tracking provider.
    #[doc(alias = "ar_device_anchor_query_status_success")]
    pub const success: Self = Self(0);
    /// Return status enum values for getting the device anchor at a specified timestamp from the world tracking provider.
    #[doc(alias = "ar_device_anchor_query_status_failure")]
    pub const failure: Self = Self(1);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ar_device_anchor_query_status_t {
    const ENCODING: Encoding = isize::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ar_device_anchor_query_status_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

/// Tracking states of a device anchor.
///
/// See also [Apple's documentation](https://developer.apple.com/documentation/arkit/ar_device_anchor_tracking_state_t?language=objc)
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
pub struct ar_device_anchor_tracking_state_t(pub isize);
impl ar_device_anchor_tracking_state_t {
    /// Tracking states of a device anchor.
    #[doc(alias = "ar_device_anchor_tracking_state_untracked")]
    pub const untracked: Self = Self(0);
    /// Tracking states of a device anchor.
    #[doc(alias = "ar_device_anchor_tracking_state_orientation_tracked")]
    pub const orientation_tracked: Self = Self(1);
    /// Tracking states of a device anchor.
    #[doc(alias = "ar_device_anchor_tracking_state_tracked")]
    pub const tracked: Self = Self(2);
}

#[cfg(feature = "objc2")]
unsafe impl Encode for ar_device_anchor_tracking_state_t {
    const ENCODING: Encoding = isize::ENCODING;
}

#[cfg(feature = "objc2")]
unsafe impl RefEncode for ar_device_anchor_tracking_state_t {
    const ENCODING_REF: Encoding = Encoding::Pointer(&Self::ENCODING);
}

impl ar_device_anchor_t {
    /// Create a device anchor.
    ///
    ///
    /// Note: This type supports ARC. In non-ARC files, use `ar_retain()` and `ar_release()` to retain and release the object.
    ///
    /// Returns: An instance of `ar_device_anchor_t`.
    #[doc(alias = "ar_device_anchor_create")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn new() -> Retained<ar_device_anchor_t> {
        extern "C-unwind" {
            fn ar_device_anchor_create() -> *mut ar_device_anchor_t;
        }
        let ret = unsafe { ar_device_anchor_create() };
        unsafe { Retained::from_raw(ret) }
            .expect("function was marked as returning non-null, but actually returned NULL")
    }

    /// Get the identifier of an anchor.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    /// Parameter `out_identifier`: A pointer to a UUID to fill out with the anchor identifier. Must be non-null.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_device_anchor.
    #[doc(alias = "ar_device_anchor_get_identifier")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn identifier(anchor: &ar_device_anchor_t, out_identifier: &mut uuid_t) {
        extern "C-unwind" {
            fn ar_device_anchor_get_identifier(
                anchor: &ar_device_anchor_t,
                out_identifier: &mut uuid_t,
            );
        }
        unsafe { ar_device_anchor_get_identifier(anchor, out_identifier) }
    }

    /// Get the timestamp corresponding to an anchor.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    ///
    /// Returns: The timestamp associated with the anchor.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_device_anchor.
    #[doc(alias = "ar_device_anchor_get_timestamp")]
    #[cfg(all(
        feature = "anchor",
        feature = "objc2",
        feature = "objc2-core-foundation"
    ))]
    #[inline]
    pub unsafe fn timestamp(anchor: &ar_device_anchor_t) -> CFTimeInterval {
        extern "C-unwind" {
            fn ar_device_anchor_get_timestamp(anchor: &ar_device_anchor_t) -> CFTimeInterval;
        }
        unsafe { ar_device_anchor_get_timestamp(anchor) }
    }

    /// Determine whether an anchor is tracked.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    ///
    /// Returns: `true` if the anchor is tracked, `false` otherwise.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_device_anchor.
    #[doc(alias = "ar_device_anchor_is_tracked")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn is_tracked(anchor: &ar_device_anchor_t) -> bool {
        extern "C-unwind" {
            fn ar_device_anchor_is_tracked(anchor: &ar_device_anchor_t) -> bool;
        }
        unsafe { ar_device_anchor_is_tracked(anchor) }
    }

    /// Get the tracking state of the device anchor.
    ///
    ///
    /// Parameter `anchor`: The anchor.
    ///
    ///
    /// Returns: Tracking state of this anchor.
    ///
    /// # Safety
    ///
    /// `anchor` must implement OS_ar_device_anchor.
    #[doc(alias = "ar_device_anchor_get_tracking_state")]
    #[cfg(all(feature = "anchor", feature = "objc2"))]
    #[inline]
    pub unsafe fn tracking_state(anchor: &ar_device_anchor_t) -> ar_device_anchor_tracking_state_t {
        extern "C-unwind" {
            fn ar_device_anchor_get_tracking_state(
                anchor: &ar_device_anchor_t,
            ) -> ar_device_anchor_tracking_state_t;
        }
        unsafe { ar_device_anchor_get_tracking_state(anchor) }
    }
}

impl ar_world_tracking_provider_t {
    /// Query a device anchor at the given timestamp.
    /// The origin is a right-handed coordinate system and is defined such that X points to the right, Y points up, and Z points backward.
    ///
    /// Example usage:
    /// ```text
    /// auto timing_info = cp_drawable_get_frame_timing(drawable);
    /// auto time = cp_time_to_cf_time_interval(cp_frame_timing_get_presentation_time(timing_info));
    /// const ar_device_anchor_query_status_t status = ar_world_tracking_provider_query_device_anchor_at_timestamp(_provider, time,
    /// &device
    /// _anchor);
    /// ```
    ///
    ///
    /// Note: This API is not thread safe.
    ///
    /// Parameter `world_tracking_provider`: The world tracking provider.
    ///
    /// Parameter `timestamp`: The timestamp to get the device anchor at. The timestamp should be provided as mach absolute time in seconds.
    ///
    /// Parameter `device_anchor`: The output device anchor.
    ///
    ///
    /// Returns: An `ar_device_anchor_query_status_t` value indicating whether the device anchor was successfully retrieved at the given timestamp or not.
    ///
    /// # Safety
    ///
    /// - `world_tracking_provider` must implement OS_ar_world_tracking_provider.
    /// - `device_anchor` must implement OS_ar_device_anchor.
    #[doc(alias = "ar_world_tracking_provider_query_device_anchor_at_timestamp")]
    #[cfg(all(
        feature = "anchor",
        feature = "data_provider",
        feature = "objc2",
        feature = "objc2-core-foundation"
    ))]
    #[inline]
    pub unsafe fn query_device_anchor_at_timestamp(
        world_tracking_provider: &ar_world_tracking_provider_t,
        timestamp: CFTimeInterval,
        device_anchor: &ar_device_anchor_t,
    ) -> ar_device_anchor_query_status_t {
        extern "C-unwind" {
            fn ar_world_tracking_provider_query_device_anchor_at_timestamp(
                world_tracking_provider: &ar_world_tracking_provider_t,
                timestamp: CFTimeInterval,
                device_anchor: &ar_device_anchor_t,
            ) -> ar_device_anchor_query_status_t;
        }
        unsafe {
            ar_world_tracking_provider_query_device_anchor_at_timestamp(
                world_tracking_provider,
                timestamp,
                device_anchor,
            )
        }
    }

    /// Get the authorization type required by the world tracking provider.
    ///
    ///
    /// Returns: The required authorization type.
    #[doc(alias = "ar_world_tracking_provider_get_required_authorization_type")]
    #[cfg(feature = "authorization")]
    #[inline]
    pub unsafe fn required_authorization_type() -> ar_authorization_type_t {
        extern "C-unwind" {
            fn ar_world_tracking_provider_get_required_authorization_type(
            ) -> ar_authorization_type_t;
        }
        unsafe { ar_world_tracking_provider_get_required_authorization_type() }
    }
}
